dockstore/dockstore-ui2

package.json
src/app/app.module.ts
src/app/containers/containers.module.ts
src/app/shared/list-containers.module.ts
src/app/shared/list-workflows.module.ts
src/app/workflows/workflows.module.ts

Updating to Angular 4 before more work is done.  forRoot() is added to some modules or else it will not work.  Also adding ngx-bootstrap for its directives.

Updating to angular 4

---

src/app/app.module.ts
src/app/container/container.component.html
src/app/container/container.component.ts
src/app/container/container.service.ts
src/app/container/files/files.component.html
src/app/container/launch/launch.component.html
src/app/container/versions/versions.component.html
src/app/containers/containers.module.ts
src/app/shared/modules/container.module.ts
src/app/shared/modules/tabs.module.ts
src/app/workflows/workflows.module.ts

Issue ga4gh/dockstore#703 has been updated.
Please note that I replaced Kitty's app-tab with the ngx-bootstrap tab for the Info, Versions, Files tab.
Apparently the workflows page is not working properly yet.
Please let me know if I am missing something.
Thanks

Created tooltips for the Tools. 

---

src/app/app.module.ts
src/app/container/container.component.html
src/app/container/container.component.ts
src/app/container/descriptors/descriptors.component.html
src/app/container/dockerfile/dockerfile.component.html
src/app/container/versions/versions.component.html
src/app/container/versions/versions.component.ts
src/app/containers/containers.module.ts
src/app/containers/list/list.component.html
src/app/containers/list/list.component.ts
src/app/home/home.component.ts
src/app/shared/date.service.ts
src/app/shared/dockstore.service.ts
src/app/shared/modules/container.module.ts
src/app/shared/modules/list-containers.module.ts
src/styles.css

Issue ga4gh/dockstore#705 has been updated.
Note that I rearranged the formate of the new UI so that it matches the look of the old UI.
Please let me know if there is any problem.
Thanks!
Jennifer

Verified Update

---

src/app/shared/date.service.ts
src/assets/docs/faq.md

Update to document verified tools for https://github.com/ga4gh/dockstore/issues/714

Document verified tools feature

---

src/app/workflow/dag/dag.component.html
src/app/workflow/dag/dag.component.ts

- Fix for the version not changing properly
- Got rid of promise to avoid multiple API calls

Fix for version change, remove promise

---

package.json
src/app/container/container.component.html
src/app/container/files/files.component.html
src/app/container/paramfiles/paramfiles.component.html
src/app/containers/list/list.component.ts
src/app/mytools/mytools.component.html
src/app/mytools/mytools.component.ts
src/app/myworkflows/myworkflows.component.html
src/app/myworkflows/myworkflows.component.ts
src/app/workflow/files/files.component.html
src/app/workflow/paramfiles/paramfiles.component.html
src/app/workflow/workflow.component.html
src/app/workflows/list/list.component.ts
src/ds-style-fix.scss
src/styles.scss

Fixed the tab hover styling issue.

fixed the tab style

---

src/app/app.module.ts
src/app/container/container.component.html
src/app/container/container.component.ts
src/app/container/register-tool/register-tool.component.ts
src/app/container/register-tool/register-tool.service.ts
src/app/container/view/view.component.html
src/app/container/view/view.component.ts
src/app/mytools/mytools.component.html
src/app/mytools/mytools.component.ts
src/app/mytools/mytools.module.ts
src/app/mytools/mytools.service.ts
src/app/myworkflows/myworkflows.component.ts
src/app/myworkflows/myworkflows.service.ts
src/app/shared/containerWeb.service.ts
src/app/shared/modules/container.module.ts
src/app/shared/refresh.service.ts
src/app/shared/state.service.ts
src/app/shared/tool.ts
src/app/shared/webservice/users.service.ts
src/app/workflow/workflow.component.ts

- The large code deleted is to fix the previous pull request which was accidentally added during the merge conflict
- Added Refresh functionality to button
- Added Refresh All Tools functionality to button

Fix for previous pull request, added refresh

---

src/app/container/container.component.html
src/app/container/container.component.ts
src/app/container/register-tool/register-tool.component.html
src/app/container/register-tool/register-tool.component.ts
src/app/container/register-tool/register-tool.service.ts
src/app/mytools/mytools.component.ts
src/app/mytools/mytools.module.ts
src/app/myworkflows/myworkflows.component.html
src/app/myworkflows/myworkflows.component.ts
src/app/shared/modules/container.module.ts
src/app/shared/modules/workflow.module.ts
src/app/shared/refresh.service.ts
src/app/shared/tool.ts
src/app/shared/webservice/users-web.service.ts
src/app/shared/webservice/workflow-web.service.ts
src/app/workflow/dag/dag.component.ts
src/app/workflow/register-workflow-modal/register-workflow-modal.component.html
src/app/workflow/workflow.component.html
src/app/workflow/workflow.component.ts
src/app/workflows/workflows.component.html
src/app/workflows/workflows.module.ts

This adds the following to MyWorkflows page:
- Refresh button
- Refresh all button
- Publish button
It also fixes the DAG using ngOnChanges but ideally, this should be done using an observable.

Adds publish and refresh buttons to workflow

---

.travis.yml
src/app/mytools/mytools.component.html
src/app/mytools/mytools.component.ts
src/app/myworkflows/myworkflows.component.html
src/app/myworkflows/myworkflows.component.ts

Fix for when the user does not have any tools or workflows.  There were also some small reformatting.

Fix for when no personal tools or workflows exist

---

README.md
src/app/containers/list/list.component.html
src/app/containers/list/list.component.ts
src/app/workflows/list/list.component.html
src/app/workflows/list/list.component.ts

https://github.com/ga4gh/dockstore-ui/pull/184

Implement starring sort for ui2

---

src/app/search/search.component.html
src/app/search/search.component.ts
src/app/search/search.service.spec.ts
src/app/search/search.service.ts

This fixes ga4gh/dockstore#883

Mutually exclusive _type, hide tab when no hits

---

src/app/container/view/view.component.html
src/app/container/view/view.component.ts

Fixes the remaining ga4gh/dockstore#874 issue

Remove delete tag from non-manual mode tools

---

src/app/container/versions/versions.component.ts
src/app/shared/refresh.service.spec.ts
src/app/shared/refresh.service.ts

Wrong import
https://github.com/flauc/angular2-notifications/issues/215

Fixed import

---

src/app/container/versions/versions.component.html
src/app/container/versions/versions.component.ts

Only have 'Add Tag' in manual tools, slight formatting

---

src/assets/docs/faq.md

https://github.com/ga4gh/dockstore/issues/628

Add back a piece of missing documentation

---

src/assets/docs/getting-started.md

- to improve clarity
- More GitLab
- Update versions
- Capitals

Update getting started document

---

src/app/container/version-modal/version-modal.component.html

* Small fix gary mentioned in default test parameter PR

changed to always disabled, removed unused modal close function

---

src/app/loginComponents/onboarding/downloadcliclient/downloadcliclient.component.ts
src/assets/docs/advanced-features.md

(FYI, decided against mentioning docker compose in user docs)

Add small reference to running with bunny

---

src/app/container/version-modal/version-modal.component.html
src/app/container/version-modal/version-modal.component.ts
src/app/workflow/version-modal/version-modal.component.html
src/app/workflow/version-modal/version-modal.component.ts
src/ds-style-fix.scss

* Makes test parameter file editing for versions more straightforward/pretty
[Issue #1012](https://github.com/ga4gh/dockstore/issues/1012)

Test parameter usability fix

---

src/app/container/container.component.ts
src/app/container/version-modal/version-modal.component.html
src/app/containers/list/list.component.html
src/app/containers/list/list.component.ts
src/app/listentry/listentry.component.html
src/app/workflow/version-modal/version-modal.component.html

* Fixed docker pull [issue #1006](https://github.com/ga4gh/dockstore/issues/1006)
* Shows none provided if no test parameter files provided in public viewing of entry

Docker pull fix

---

src/app/container/container.component.html
src/app/container/deregister-modal/deregister-modal.component.html
src/ds-style-fix.scss

Changed the deregister button to delete, now also deletes auto tools.

Deregister is now delete, and works on all tool types

---

src/app/containers/list/list.component.html
src/app/listentry/listentry.component.html
src/app/search/search.service.ts
src/app/workflow/info-tab/info-tab.service.ts

Tied to https://github.com/ga4gh/dockstore/issues/1055

Implement language search

---

src/polyfills.ts

Working on https://github.com/ga4gh/dockstore/issues/1085

Polyfill workaround for googlebot issue

---

.travis.yml

Test out new dockstore webservice version

---

src/app/container/container.component.html
src/app/container/container.component.ts
src/app/container/email.service.spec.ts
src/app/container/email.service.ts
src/app/shared/dockstore.service.ts
src/app/shared/models/ExtendedDockstoreTool.ts
src/app/shared/modules/container.module.ts

Just moving the commit to hotfix branch.
* Display Request Access button and Contact Author button
* Add tests, moved functions to separate service
See https://github.com/dockstore/dockstore-ui2/pull/173 for similarities/differences

Feature/private access (#173)

---

src/app/container/add-tag/add-tag.component.html

Simple modification for ga4gh/dockstore#542

Require one of the descriptors

---

src/app/container/info-tab/info-tab.component.html
src/app/workflow/info-tab/info-tab.component.html

Quick fix for issue ga4gh/dockstore#1187.  Never remove the field if it's in mytools or myworkflows even when it's empty

Fix for missing text fields

---

src/app/app.module.ts
src/app/container/container.component.ts
src/app/mytools/mytools.component.ts
src/app/mytools/mytools.routing.ts
src/app/myworkflows/myworkflows.component.spec.ts
src/app/myworkflows/myworkflows.component.ts
src/app/myworkflows/myworkflows.routing.ts
src/app/shared/entry.ts
src/app/shared/url-resolver.service.spec.ts
src/app/shared/url-resolver.service.ts
src/app/test/router-stubs.ts
src/app/test/service-stubs.ts
src/app/workflow/workflow.component.ts

Partial ga4gh/dockstore#1170
Allows the logged in user to browse to their own workflows/tools directly with their tool/workflow path.

Resolve entry paths in the mytools/myworkflows URL

---

src/app/container/info-tab/info-tab.component.html
src/app/container/launch/launch.component.ts
src/app/shared/launch.service.ts
src/app/workflow/info-tab/info-tab.component.html
src/app/workflow/launch/launch.component.html
src/app/workflow/launch/launch.component.ts
src/app/workflow/launch/workflow-launch.service.ts

Associated with https://github.com/ga4gh/dockstore/pull/1207

Add examples for nextflow launch with

---

src/app/listentry/listentry.component.html

For issue ga4gh/dockstore#1097
Don't encode the search entries either

Don't encode search urls either

---

src/app/container/launch/launch.component.ts

Fixes the launch commands showing the workflow name twice when present.

Fix for tool path

---

src/app/shared/extended-workflow.service.ts

Other half of https://github.com/ga4gh/dockstore/issues/1140 for github

Migrate to proper workflow dates

---

src/app/home-foot-note/home-foot-note.component.html

Fixes the links on the home page, before they were pointed at the old docs.

updated doc links on home page

---

src/app/loginComponents/onboarding/onboarding.component.html
src/app/loginComponents/onboarding/quickstart.component.html

For https://github.com/ga4gh/dockstore/issues/1286

Fix links in wizards

---

src/app/footer/footer.component.html

For issue ga4gh/dockstore#1287
Put the status link at the footer similar to how GitHub does it.

Add status

---

src/app/search/search-results/search-results.component.ts
src/app/search/search.component.ts

Simple workaround to prevent console spam when search fails.

Fix for empty elasticsearch results error

---

src/app/container/launch/launch.component.html
src/app/workflow/launch/launch.component.html
src/app/workflow/versions/versions.component.html

The launch with section is only shown if the version selected is valid.
If it isn't then a message is shown.
Deals with https://github.com/ga4gh/dockstore/issues/1303

Now launch with is only shown if the selected version is valid

---

src/app/shared/error.service.spec.ts
src/app/shared/error.service.ts

Better error message for webservice.
https://github.com/ga4gh/dockstore/issues/1321

updated error message when webservice cannot be connected to

---

src/app/container/versions/versions.component.css
src/app/container/versions/versions.component.html
src/app/container/view/view.component.html
src/app/workflow/view/view.component.html

Small cleanup of the add tag button.

add tag looks nicer

---

src/app/container/add-tag/add-tag.component.ts

After adding a tag, the tag dialog is reset.
https://github.com/ga4gh/dockstore/issues/1086

tag is cleared after adding

---

src/app/search/search.service.ts

Allows users to filter by source control for workflows.
https://github.com/ga4gh/dockstore/issues/1245

filter by source control

---

src/app/container/register-tool/register-tool.service.ts
src/app/workflow/register-workflow-modal/register-workflow-modal.service.spec.ts
src/app/workflow/register-workflow-modal/register-workflow-modal.service.ts

For ga4gh/dockstore#1344 
Simple change to change url upon successful register

Change url on register success

---

src/app/container/container.component.ts
src/app/myworkflows/my-workflow/my-workflow.component.ts
src/app/shared/entry.ts
src/app/workflow/workflow.component.ts

Fix unsubscribes (switching from my-workflows to workflows, then selecting workflow causes unsubscribe error depending on database)
Fixes selecting workflow redirecting to my-workflow too

Fix unsubscribes

---

.travis.yml
cypress/integration/checkerWorkflowFromTools.js
src/app/myworkflows/myworkflows.service.spec.ts
src/app/shared/entry.ts
src/app/shared/refresh.service.spec.ts
src/app/shared/workflow.service.spec.ts
src/app/test/mocked-objects.ts
src/app/test/service-stubs.ts
src/app/workflow/dag/dag.component.spec.ts
travisci/db_dump.sql
travisci/web.yml

Update to 1.5.0 webservice for staging release
* also syncs ui2 database structure with main dockstore repo in terms of user names, performed migrations

Update to alpha webservice release

---

src/app/container/versions/versions.component.html
src/app/workflow/versions/versions.component.html

Tag - https://fontawesome.com/v4.7.0/icon/tag/
Branch - https://fontawesome.com/v4.7.0/icon/code-fork/
https://github.com/ga4gh/dockstore/issues/1336

show tag and branch icon in versions table

---

cypress/integration/checkerWorkflowFromMyTools.js
cypress/integration/checkerWorkflowFromMyWorkflow.js
cypress/integration/checkerWorkflowFromTools.js
cypress/integration/checkerWorkflowFromWorkflows.js
cypress/integration/dropdown.js
cypress/integration/myworkflows.js
cypress/integration/toolDetails.js
cypress/integration/workflowDetails.js
src/app/container/container.component.html
src/app/container/container.component.ts
src/app/shared/entry.ts
src/app/shared/url-resolver.service.ts
src/app/workflow/workflow.component.html
src/app/workflow/workflow.component.ts

Fixes linked to entry versions, also adds linking to tabs and deals with discourse creation.
https://github.com/ga4gh/dockstore/issues/1407

Link to entry fix

---

src/app/container/launch/tool-launch.service.spec.ts
src/app/shared/launch.service.ts
src/app/workflow/launch/workflow-launch.service.spec.ts

Checker Launch Command Fix

---

src/app/shared/launch.service.ts
src/app/workflow/launch/launch.component.ts
src/app/workflow/launch/workflow-launch.service.spec.ts

Fixes the wget test parameter file command 
TODO: return proper error message on webservice when source repo doesn't match.

Fix wget test parameter file command

---

cypress/integration/dropdown.js
src/app/container/container.component.html
src/app/container/register-tool/register-tool.component.ts
src/app/containers/list/list.component.html
src/app/containers/list/list.component.ts
src/app/home/home.component.html
src/app/home/home.component.ts
src/app/loginComponents/accounts/external/accounts.component.ts
src/app/myworkflows/myworkflows.component.css
src/app/shared/dockstore.model.ts
src/app/workflow/register-workflow-modal/register-workflow-modal.component.ts
src/app/workflow/versions/versions.component.html
src/app/workflow/workflow.component.html
src/app/workflows/list/list.component.html
src/app/workflows/list/list.component.ts
src/styles.scss

* Fixes layout of tables on the homepage and tools/workflows pages
* Fixes layout of entry versions table
* Comment out GitLab

Homepage fix tools

---

src/app/container/container.component.html
src/app/workflow/workflow.component.html

Now opens remote repo links in a new tab
https://github.com/ga4gh/dockstore/issues/1089

open source code repos links in a new tab

---

.travis.yml
src/app/container/container.component.ts
src/app/shared/dockstore.service.ts
src/app/shared/entry.ts
src/app/workflow/workflow.component.ts

Awaiting release linked in commit

Delete hiding code

---

src/app/container/container.component.html
src/app/shared/entry.ts
src/app/workflow/workflow.component.html

Now clicking on a label properly goes to search page.
https://github.com/ga4gh/dockstore/issues/1197

fix search label link

---

src/app/shared/launch.service.ts
src/app/workflow/launch/launch.component.ts
src/app/workflow/launch/workflow-launch.service.spec.ts

Cherry-picking the commit to fix the first part of ga4gh/dockstore#1548
* Fix wget test parameter file command
* Properly handle nextflow

Fix wget test parameter file command (#290)

---

src/app/loginComponents/accounts/external/accounts.component.ts
src/app/workflow/register-workflow-modal/register-workflow-modal.component.ts

I needed this to test https://github.com/ga4gh/dockstore/issues/1397 on Gitlab

Gitlab re-enable

---

src/app/container/container.component.html
src/app/shared/versions.ts
src/app/workflow/workflow.component.html

Showing all versions instead of just the ones on the sidebar.
Tried altering the sortVersions function to show more than 5, but the table sorting will overwrite it regardless.

Show all versions

---

src/app/shared/entry.ts

https://github.com/ga4gh/dockstore/issues/1514

fix weird back button issue

---

cypress/integration/toolDetails.js
src/app/container/container.component.ts
src/app/shared/entry.ts
src/app/workflow/workflow.component.ts

FYI, re-created by cherry-picking the non-dnastack/firecloud commit.
See https://github.com/dockstore/dockstore-ui2/pull/338

2.1.5 merge

---

src/app/container/launch/launch.component.html
src/app/container/launch/launch.component.ts
src/app/shared/entry/descriptor-language.service.ts

GET descriptor-languages was actually being called every time when needed. fixing it so it's called once during service construction.  Also using the languages$ instead of languagesBean$

Fix descriptor-language service doing HTTP call every time

---

package-lock.json
package.json
src/app/loginComponents/accounts/internal/accounts.component.ts
src/app/workflow/dag/cwl-viewer/cwl-viewer.component.ts
src/app/workflow/dag/cwl-viewer/cwl-viewer.service.spec.ts
src/app/workflow/dag/cwl-viewer/cwl-viewer.service.ts
tslint.json

Reverts dockstore/dockstore-ui2#335
Oops, got trigger-happy

Revert "Feature/rxjs6 lint"

---

src/app/workflows/list/list.component.html
src/app/workflows/list/list.component.ts

Working on https://github.com/ga4gh/dockstore/issues/1590

Properly hook up descriptor type sorting

---

cypress/integration/myworkflows.js
src/app/container/refresh-tool-organization/refresh-tool-organization.component.spec.ts
src/app/myworkflows/my-workflow/my-workflow.component.html
src/app/myworkflows/my-workflow/my-workflow.component.scss
src/app/myworkflows/sidebar-accordion/sidebar-accordion.component.html
src/app/myworkflows/sidebar-accordion/sidebar-accordion.component.scss
src/app/myworkflows/sidebar-accordion/sidebar-accordion.component.spec.ts
src/app/myworkflows/sidebar-accordion/sidebar-accordion.component.ts
src/app/shared/refresh-organization/refresh-organization.component.html
src/app/workflow/refresh-workflow-organization/refresh-workflow-organization.component.spec.ts
src/ds-style-fix.scss

The my workflows page org accordion is now material.

My workflow accordion is now material

---

package-lock.json
package.json

Literally just ran `npm i karma@latest` which locks at the version 2.0.5.  No known side effects so far.

npm i karma@latest

---

src/app/loginComponents/accounts/internal/accounts.component.html

Working on https://github.com/ga4gh/dockstore/issues/1622

Deal with Firefox copy-and-paste annoyance

---

src/app/container/launch/launch.component.html
src/app/shared/entry/launch-checker-workflow/launch-checker-workflow.component.html
src/app/shared/entry/launch-checker-workflow/launch-checker-workflow.component.spec.ts
src/app/workflow/launch/launch.component.html

https://github.com/ga4gh/dockstore/issues/1648
No more nested wells :tada:

change launch component to be material cards and fix nextflow launch

---

src/app/container/descriptors/descriptors.component.html
src/app/container/dockerfile/dockerfile.component.html
src/app/container/paramfiles/paramfiles.component.html
src/app/workflow/descriptors/descriptors.component.html
src/app/workflow/paramfiles/paramfiles.component.html

I added the screenshot in my last PR but forgot to push my final changes.

Material buttons for files

---

src/app/workflow/register-workflow-modal/register-workflow-modal.component.html

changed descriptor dropdown to radio buttons

---

src/app/app.module.ts
src/app/login/login.service.ts
src/app/loginComponents/accounts/controls/delete-account-dialog/delete-account-dialog.component.ts
src/app/register/register.service.ts
src/app/shared/refresh.service.ts
src/app/workflow/permissions/permissions.component.ts

For ga4gh/dockstore#1701
Adds a default 5 sec duration to all snackbars, can be overridden like normal.

Add default 5 sec duration

---

cypress/integration/disabledAccountControls.js
cypress/integration/dropdown.js
src/app/loginComponents/accounts/controls/delete-account-dialog/delete-account-dialog.component.html
src/app/loginComponents/accounts/controls/delete-account-dialog/delete-account-dialog.component.ts

Adds a quick test to check that both self-destruct form buttons are disabled/enabled correctly and that it goes to login page afterwards. 
Also adds progress bar and fixes unsubscribe.

Add test for self destruct

---

src/app/home/home.component.html
src/app/shared/twitter.service.ts

Needed to reload the twitter script after page change.  Still doesn't solve the first twitter issue that polls every 30 seconds even after route change.
Partial ga4gh/dockstore#1630
Removed the async script, didn't seem necessary

Reload twitter upload revisit

---

src/app/mytools/my-tool/my-tool.component.html
src/app/mytools/my-tool/my-tool.component.ts
src/app/myworkflows/my-workflow/my-workflow.component.html
src/app/myworkflows/my-workflow/my-workflow.component.ts

Shows a loading bar when fetching my tools/workflows, instead of showing blank or showing the alert that they have no tools/workflows/

show loading bar when checking for entries

---

src/app/workflow/dag/dag.component.html

#1572
I wasn't sure whether to check against `Workflow.sourceControl` or `Workflow.source_control_provider`. I went with the latter.

Hide CWL Viewer if Workflow not on GitHub

---

.travis.yml
cypress/integration/hostedTools.js

Update dockstore webservice version

---

src/app/loginComponents/onboarding/onboarding.component.html
src/app/loginComponents/onboarding/onboarding.component.ts

Working on https://github.com/ga4gh/dockstore/issues/1711 follow-up

Skip username change prompt if the user has already changed username

---

src/app/workflow/dag/dag.component.html

For nextflow dags, always show a warning that nextflow dag is experimental.

always show warning for nextflow dag

---

src/app/myworkflows/my-workflow/my-workflow.component.spec.ts
src/app/myworkflows/my-workflow/my-workflow.component.ts

For ga4gh/dockstore#1588 Split HTTP request to better handle errors.

Handle errors in HTTP calls

---

src/app/loginComponents/accounts/internal/accounts.component.html
src/app/mytools/sidebar-accordion/sidebar-accordion.component.html
src/app/mytools/sidebar-accordion/sidebar-accordion.component.ts
src/app/myworkflows/sidebar-accordion/sidebar-accordion.component.ts

Working on https://github.com/ga4gh/dockstore/issues/1751

Type this stuff to help catch typos

---

src/app/workflow/launch-third-party/launch-third-party.component.html

Use Material Toolip in Launch with 3rd Party

---

src/app/loginComponents/onboarding/onboarding.component.html

For ga4gh/dockstore#1743
Wait for user and extenduser before creating any steppers.

Wait for user and extendeduser before constructing

---

src/app/shared/refresh.service.ts
src/app/test/service-stubs.ts

Clears error messages on refresh success, also fixes some indenting. https://github.com/ga4gh/dockstore/issues/1729

clear errors on refresh success

---

src/app/loginComponents/onboarding/downloadcliclient/downloadcliclient.component.html

No more spaces in textarea for config file
https://github.com/ga4gh/dockstore/issues/1753

fix spacing issue

---

src/app/workflow/permissions/permissions.component.spec.ts
src/app/workflow/permissions/permissions.component.ts

A 409 error in this case means the admins will have to get involved.
Screenshot, using local webservice build that has message generated in ga4gh/dockstore#1759.

More prominent display of 409 error

---

src/app/container/container.component.html
src/app/mytools/my-tool/my-tool.component.html
src/app/myworkflows/my-workflow/my-workflow.component.html
src/app/workflow/workflow.component.html

Slightly better tooltips for ga4gh/dockstore#1554

Slightly better tooltips

---

src/app/container/container.component.html

Wording is up for discussion.
https://github.com/ga4gh/dockstore/issues/1045

show alert for manual tools with no versions

---

src/app/starredentries/starredentries.component.ts

Filters out the unpublished workflows/tools for ga4gh/dockstore#1765 enhancement

Filter out unpublished entries

---

src/app/search/map-friendly-values.pipe.ts
src/app/workflow/register-workflow-modal/register-workflow-modal.component.html
src/app/workflow/register-workflow-modal/register-workflow-modal.service.ts

* would prefer tooltip, but for  https://github.com/angular/material2/issues/7953

Hide disabled option altogether

---

src/app/select/select.component.html

For ga4gh/dockstore#1769
Show tooltips on all dropdown options in file selection

Add tooltips to dropdown

---

src/app/shared/validationMessages.model.ts

allow internal hyphens and underscores for amazon registry

---

src/app/loginComponents/onboarding/downloadcliclient/downloadcliclient.component.ts

Updates the link in the onboarding from Docker EE to Docker CE.

updated link to docker ce

---

src/app/container/register-tool/register-tool.component.ts

Remove 'Dockstore' from selection in register tool source code repo

Remove 'Dockstore' from selection in register tool

---

src/app/container/container.component.html
src/ds-style-fix.scss

Changed the contact buttons (request access and contact author) to be material.

changed to material

---

src/app/shared/entry/GA4GHFiles.state.service.ts
src/app/shared/my-entry.ts

Null check when setting authorization header

---

src/app/search/search.component.html

https://github.com/ga4gh/dockstore/issues/1832

Search facet margin fix

---

angular.json
src/index.html
src/manifest.json

Bump up PWA score by 20 points or so by adding a manifest.json and setting theme color 
Partial ga4gh/dockstore#1600

Bump up PWA score

---

.travis.yml
cypress/integration/WorkflowsSearch.js
src/app/container/paramfiles/paramfiles.service.spec.ts
src/app/test/mocked-objects.ts

* Suspected fixes needed to get hotfix to build and deploy via compose_setup

Fix calls to swagger methods

---

src/app/loginComponents/accounts/internal/accounts.component.html

Removes an extra refresh loading icon shown on the profiles page.

removed refresh in profiles

---

.travis.yml
cypress/integration/group2/workflowDetails.ts
scripts/wait-for.sh
src/app/container/versions/versions.component.html
src/app/header/header.component.ts
src/app/mytools/my-tool/my-tool.component.ts
src/app/myworkflows/my-workflow/my-workflow.component.ts
src/app/navbar/navbar.component.ts
src/app/organizations/collection/collection.component.ts
src/app/organizations/organization/organization.component.ts
src/app/organizations/state/collections.service.ts
src/app/organizations/state/organization.service.spec.ts
src/app/organizations/state/organization.service.ts
src/app/shared/entry.ts
src/app/sponsors/sponsors.component.ts
src/app/test/service-stubs.ts
src/app/workflow/dag/dag.component.html
src/app/workflow/dag/dag.component.scss
src/app/workflow/dag/dag.component.spec.ts
src/app/workflow/dag/dag.component.ts
src/app/workflow/dag/dag.module.ts
src/app/workflow/dag/state/dag.service.ts
src/app/workflow/versions/versions.component.html
src/styles.scss

Initially added the npm cache as per Cypress instruction, somehow turned into random fixes for other issues
- Fixes the collections and collection store merge.
- Added NPM cache (even keeping the typo), doesn't seem to have any effects.  Can revert if causing issues.
- Wait for the webservice in hopes that it might fix the psql timeout issue
- Use activatedRoute for getting the path parameters
- Many DAG changes, fixes the sidebar overlapping (ga4gh/dockstore#1993), barely  increased performance by rendering the DAG outside of Angular (to prevent change detection).  Can't seem to test this in Cypress because full screen functionality must be user driven.
- Reduce Date function calls by a bajllion (should get rid of that function altogether eventually).  Format changed slightly (Mar. 29 …

Feature/cache + others

---

.circleci/config.yml

CircleCI insurance

---

.semaphore/semaphore.yml
cypress/integration/group1/checkerWorkflowFromTools.ts
cypress/support/commands.ts

For my personal use and those who wish to fork repo and test separate from Dockstore.  Shouldn't affect the rest of the team.
Also attempts ga4gh/dockstore#2145 (a better fix would be implement progress bar when switching between tools/workflows and have Cypress check that there's no progress bar before proceeding with other actions)

Semaphore CI setup

---

src/app/footer/footer.component.html
src/app/home-foot-note/home-foot-note.component.html

Small edit to https://github.com/ga4gh/dockstore/issues/1934

Move sitemap link

---

src/app/workflow/dag/dag.component.html
src/app/workflow/dag/dag.component.ts
src/app/workflow/dag/wdl-viewer/wdl-viewer.component.ts

* Removes event emitter, which is no longer needed

Removes Event Emitter from wdl-viewer component

---

src/app/container/info-tab/info-tab.component.html
src/app/workflow/info-tab/info-tab.component.html

https://github.com/ga4gh/dockstore/issues/2072

display current version in info tab

---

src/app/footer/footer.component.html

update date [skip travis]

---

.gitignore
README.md
cypress/integration/group3/organizations.ts
cypress/support/commands.ts
package-lock.json
package.json
scripts/resetDb.sql
src/tsconfig.compodoc.json

Add command for documentation.  Creates docs in the `docs` folder.  In the future github pages can be pointed to the docs folder of the master branch (Travis can auto-generate docs on master branch).
Also try to remove some snyk warnings (bootstrap lied, there's a newer non-breaking version)
Another shot at resetDb

Add random stuff

---

src/app/shared/dockstore.model.ts
src/app/workflow/launch-third-party/launch-third-party.component.html

ga4gh/dockstore#2235
Another PR coming for compose_setup.

Restore feature flag for Launch/w FireCloud

---

src/app/sitemap/sitemap.component.html

sitemap typo 

---

src/app/organizations/state/collections.service.ts

Changes collection URL when the collection is updated

---

src/app/app.component.spec.ts
src/app/app.component.ts
src/app/search/search.component.ts

ga4gh/dockstore#2124
ga4gh/dockstore#2230
Alert state gets cleared when route changes.

Clear alert state on route change

---

cypress/integration/group1/disabledAccountControls.ts
cypress/integration/group1/dropdown.ts
src/app/loginComponents/accounts/controls/controls.component.html

Don't display error message if user cannot perform account changes

---

src/app/organizations/collection/state/add-entry.service.ts

Show rejected/pending orgs when adding an entry to a collection.
https://github.com/ga4gh/dockstore/issues/2244

be able to add entry to rejected/pending collection

---

src/app/container/container.component.html
src/app/workflow/workflow.component.html

https://github.com/ga4gh/dockstore/issues/1305

fix discourse location

---

src/app/shared/code-editor-list/code-editor-list.component.ts

Hosted entry paths default to be absolute.

Hosted entry path

---

package.json
scripts/generate-openapi-script.sh
src/app/container/paramfiles/paramfiles.service.ts
src/app/shared/descriptor-type-compat.service.ts
src/app/shared/descriptor.service.ts
src/app/shared/file-editing.ts
src/app/shared/ga4gh-files/ga4gh-files.service.ts
src/app/workflow/dag/wdl-viewer/state/wdl-viewer.service.ts
src/app/workflow/launch-third-party/launch-third-party.component.ts
travisci/web.yml

* adapt to simplification of descriptor endpoints
* document places to add a new language
Accompanies https://github.com/dockstore/dockstore/pull/2428

Generalizable work for new workflow languages

---

src/app/funding/funding.component.html

https://github.com/dockstore/dockstore/issues/2493
https://github.com/dockstore/dockstore/issues/2465
Adds text to funding page and updates Ontario logo. Also adds BISTI and STAGE funding info

add text to funding page and update ontario logo

---

package.json
src/app/app.component.ts
src/app/configuration.service.ts
src/app/shared/dockstore.model.ts
src/app/shared/state/checker-workflow.query.ts
src/app/shared/state/checker-workflow.service.ts
src/app/workflows/list/published-workflows.datasource.ts

dockstore/dockstore-ui2#2444
Also fix build errors caused by changes to webservice endpoints.

Read GTM ID from config.json

---

package.json
src/app/container/add-tag/add-tag.component.ts
src/app/container/container.component.html
src/app/container/container.component.ts
src/app/container/info-tab/info-tab.component.ts
src/app/container/info-tab/info-tab.service.ts
src/app/container/launch/launch.component.ts
src/app/container/version-modal/version-modal.component.ts
src/app/container/view/view.component.ts
src/app/containers/list/list.component.ts
src/app/myworkflows/myworkflows.service.spec.ts
src/app/search/search-tool-table/search-tool-table.component.ts
src/app/shared/descriptor-type-compat.service.ts
src/app/shared/dockstore.service.spec.ts
src/app/shared/dockstore.service.ts
src/app/shared/entry/descriptor-language.service.ts
src/app/shared/extended-dockstoreTool/extended-dockstoreTool.service.ts
src/app/shared/refresh.service.spec.ts
src/app/shared/state/checker-workflow.query.ts
src/app/shared/state/checker-workflow.service.ts
src/app/shared/tool/tool.service.ts
src/app/test/mocked-objects.ts
src/app/test/service-stubs.ts
src/app/workflow/launch-third-party/launch-third-party.component.html
src/app/workflow/register-workflow-modal/register-workflow-modal.component.ts
src/app/workflow/register-workflow-modal/register-workflow-modal.service.ts
travisci/web.yml

Changes for workflow language enum refactor

---

src/app/loginComponents/accounts/external/accounts.service.ts
src/app/loginComponents/accounts/external/links.model.ts
tslint.json

Linking your account wasn't working anymore. Thanks @coverbeck for the fix.

fix linking accounts

---

package-lock.json
package.json

For dockstore/dockstore#2535
Oddly enough, the closest ones to node 10.13.0 are 10.12.30 or 10.14.0.  There isn't anything closer.

npm i @types/node@10.14.0

---

src/app/shared/bioschema.service.spec.ts
src/app/shared/bioschema.service.ts
src/app/shared/date.service.ts
src/app/workflow/workflow.component.ts

Added tests for getWorkflowSchema() and getToolSchema() checking that their properties are filled in correctly using test values

Bioschema tests

---

src/app/login/login.component.html

Passive TOS acceptance for registering and logging in

---

cypress/integration/group1/admin.ts
cypress/integration/group1/app-spec.ts
cypress/integration/group1/curator.ts
cypress/integration/group1/disabledAccountControls.ts
cypress/integration/group1/dropdown.ts
cypress/integration/group3/mytools.ts
cypress/integration/group3/myworkflows.ts
cypress/integration/group3/starEntry.ts
src/app/navbar/navbar.component.html

Navbar was not quite working for mobile sizes (missing the my-entries in the dropdown menu).  This just uses one dropdown menu and one login button to avoid repetition of code
Makes the mobile version of the login identical to what it is for the normal size

Fix navbar

---

package.json

run testing for new release

---

src/app/loginComponents/requests/requests.component.ts
src/app/shared/user/user.query.ts

`updateCuratorOrganizations()` requires admin permissions. Added a condition so this does not display an error when non-admin users open their accounts page. Also removed unused variable `currentOrgId`.

#2520 added admin condition

---

package.json
src/app/container/container.component.html
src/app/container/container.component.ts
src/app/container/versions/versions.component.html
src/app/container/versions/versions.component.ts
src/app/shared/entry.ts
src/app/shared/versions.ts
src/app/workflow/versions/versions.component.ts
src/app/workflow/workflow.component.ts

Part of #2548
Changes for renaming lastmodified column in tag table to lastbuild. There are 2 other recommendations. I'd rather split this out and do this while I work on other things for dockstore or put this on hold in general. Thoughts?

portion of feature/2458/databasechanges

---

cypress/integration/group1/checkerWorkflowFromWorkflow.ts
cypress/integration/group2/mytools.ts

Not so great fixes for https://github.com/cypress-io/cypress/issues/695#issuecomment-459270583
Checking width greater than 0 doesn't seem to work as reliably as simply waiting.  Hopefully there's a better fix at some point

Add hacky check for test

---

src/app/sitemap/sitemap.component.html

Fix sitemap link

---

src/app/shared/myentries.service.ts

https://github.com/dockstore/dockstore/issues/2685

Case insensitive sorting for workflows/services

---

src/app/organizations/state/organization-members.service.ts

Visitors not logged in will be able to see org members.
https://github.com/dockstore/dockstore/issues/2458

also show org members when not logged in

---

src/app/workflow/launch-third-party/launch-third-party.component.ts

#1852
Describe in fuller detail all of the steps needed for adding a
launch with button.

Update doc for adding launch with button

---

src/app/workflow/permissions/permissions.component.html

For dockstore/dockstore#2663
If you're wondering why CircleCI didn't run...I have no idea either

Clarify message

---

cypress/integration/group2/mytools.ts

Part of SEAB-244.
Seems to fix one flaky test sometimes.

Fix Cypress detached error

---

src/app/home-page/old-home-page/old-home-page.component.ts

Setting the entryType when tabbing to the Browse Workflow on the old home page.

Set entryType

---

src/app/search/advancedsearch/advanced-search.service.ts
src/app/search/search.component.ts

For dockstore/dockstore#2679
Bandage for the search from homepage.

Fixed bug, add comment

---

src/app/workflow/info-tab/info-tab.component.html

A simple fix for the descriptor type in STUB
dockstore/dockstore#2657

Fix descriptor types for STUBs

---

src/app/myworkflows/my-services.service.ts

Getting shared workflows was being done in my-services for some reason.  The fix applied to my-workflows was not applied to my-services (because it shouldn't even be there).  This is why the progress bar was not being shown.
for dockstore/dockstore#2782

Remove shared workflows from my-services

---

src/app/container/files/files.component.html
src/app/workflow/files/files.component.html

https://github.com/dockstore/dockstore/issues/2354
* Change first tab for files to be lazy loaded

lazy load first tab as well

---

src/app/organizations/collection/collection.component.html
src/app/organizations/collection/collection.component.ts

https://github.com/dockstore/dockstore/issues/2717
Linking to a service from a collection now works.

fix collection link to service

---

src/app/workflow/view/view.component.ts

* Clear sourcefiles for update workflow request to snapshot so that request is smaller (issue was a lot of sourcefiles made the request huge, exceeding 50K limit)
https://github.com/dockstore/dockstore/issues/2762

clear sourcefiles from versions to shrink request size

---

cypress/integration/immutableDatabaseTests/workflowDetails.ts
src/app/workflow/view/view.component.html

Fix for dockstore/dockstore#2742 again

Fix for snapshot in public page

---

src/app/loginComponents/onboarding/downloadcliclient/downloadcliclient.component.ts

Remove Python 2 instructions

---

src/app/workflow/dag/dag.component.html
src/app/workflow/dag/dag.component.ts
src/app/workflow/dag/dag.module.ts
src/app/workflow/dag/state/dag.service.ts

For dockstore/dockstore#2806
Adds a dag progress bar so that the error message doesn't instantly appear before loading

Add progress bar to dag tab

---

src/app/app.module.ts
src/app/interceptors/workflow-versions.interceptor.spec.ts
src/app/interceptors/workflow-versions.interceptor.ts

dockstore/dockstore#2833
dockstore/dockstore#2836

Set sourceFiles to empty array on workflowVersions endpoint

---

src/app/home-page/old-home-page/old-home-page.component.html
src/app/sitemap/sitemap.component.html

Fix the links to the news page on read the docs.

fix links to news

---

src/app/shared/file.service.spec.ts
src/app/shared/file.service.ts
src/app/test/mocked-objects.ts

dockstore/dockstore#2819
See in particular comments starting at
https://github.com/dockstore/dockstore/issues/2819#issuecomment-529957708

Disable CGC button for CWL with run http

---

src/app/loginComponents/onboarding/downloadcliclient/downloadcliclient.component.ts

Update account set up for CWL, moved docker install to dependencies (Part 1), separated out CWL since optional

Update account setup instructions

---

src/app/entry/entry-file-tab/entry-file-tab.component.html
src/app/entry/entry-file-tab/entry-file-tab.component.ts
src/app/entry/entry-file-tab/state/entry-file-tab.query.ts
src/app/entry/entry-file-tab/state/entry-file-tab.service.ts
src/app/entry/entry-file-tab/state/entry-file-tab.store.ts
src/app/home-page/old-home-page/old-home-page.component.html
src/app/loginComponents/onboarding/downloadcliclient/downloadcliclient.component.ts
src/app/shared/file.service.spec.ts
src/app/shared/file.service.ts
src/app/sitemap/sitemap.component.html
src/app/test/mocked-objects.ts
src/app/workflow/workflow.component.html

Merge release/1.7.0 content back to develop

Feature/merge 1.7 stuff

---

src/app/home-page/home-logged-out/home.component.html

https://github.com/dockstore/dockstore/issues/2901
Updates buttons to better link to docs. Open to suggestions for additional links/button text.

link for launching on docs and developer tutorial

---

README.md
src/app/app.component.css
src/app/footer/footer.component.html
src/app/home-page/home-logged-out/home.component.html
src/app/home-page/home-page.component.html
src/app/navbar/navbar.component.html
src/app/sponsors/sponsors.component.html
src/index.html
src/styles.scss

Addressed easy-to-fix items in the Google Lighthouse audit of staging.dockstore.org. A lot of these things seem to be more complicated than I expected:
Some of these are only flagged as problems when using 4G throttling in the audit.
* Ensure text remains visible during web font load: Addressed for local Gotham fonts and Google font. Not sure if this fix can be done for Fontawesome font as it's in a library.
* Preload key requests: fix for this is commented out in index.html. While this fix addresses the audit warning, it doesn't seem to actually help, as it introduces a console warning that the preloaded files aren't used. They end up being downloaded twice. Not sure if this is fixable.
* Serve static assets with an efficient cache policy: Made a new ticket for this.
* Properly size …

SEAB-434 lighthouse audit quick fixes

---

src/app/search/search.component.html
src/app/search/search.component.ts

For dockstore/dockstore#2947
Also, reduce joinComma calls by a bajillion

Add missing space, remove template function

---

cypress/integration/group2/starErrorMessage.ts
src/app/starring/starring.component.ts
src/app/starring/starring.service.spec.ts
src/app/starring/starring.service.ts

Use the new restful starring endpoint
For dockstore/dockstore#2395

Use new restful starring endpoints

---

src/app/container/container.component.ts
src/app/workflow/workflow.component.ts

Not really part of any current issues, but this handles label errors.

Handle error

---

src/app/shared/entry.ts

For dockstore/dockstore#3022
~Check that it's not already added before adding again~
Remove it if it's already present.

Prevent discourse from adding every time

---

src/app/shared/entry-wizard/entry-wizard.component.html

Add tooltip to disabled slider

---

src/app/workflow/workflow-file-editor/workflow-file-editor.component.ts

give better success message for saving hosted workflow versions

---

package-lock.json
package.json

Fix some GitHub security alerts.
Just updated those 2 to latest

Update karma and @angular-devkit/build-angular

---

src/app/sponsors/sponsors.component.css
src/app/sponsors/sponsors.component.html

Once again we should basic sponsors on the logged in homepage.
https://github.com/dockstore/dockstore/issues/3082

show in affiliation with on home page

---

src/app/search/search.component.html
src/app/search/search.component.scss
src/app/search/search.component.ts
src/app/search/state/search.service.ts
src/app/shared/private-icon/private-icon.component.html
src/app/shared/private-icon/private-icon.module.ts
src/app/test/service-stubs.ts

search page tool tips

---

package.json
src/app/home-page/widget/entries/entries.component.ts
src/app/home-page/widget/filtered-list.ts
src/app/home-page/widget/organizations/organizations.component.ts
src/app/shared/state/entry-wizard.service.ts

Contributes to https://github.com/dockstore/dockstore/pull/3117

Update to tagged openapi endpoints

---

src/app/myworkflows/my-workflow/my-workflow.component.html
src/app/navbar/navbar.component.html
src/app/sitemap/sitemap.component.html
src/app/workflows/workflows.component.html
src/styles.scss

Outdated images removed
https://github.com/dockstore/dockstore/issues/3083

The not-beta label

---

package.json

Update webservice version to 1.8.0-beta.8

update webservice version to 1.8.0-beta.8

---

src/app/search/map-friendly-values.pipe.spec.ts
src/app/search/map-friendly-values.pipe.ts
src/app/search/search.component.html
src/app/search/search.component.scss
src/app/search/search.module.ts
src/ds-style-fix.scss

Portion of dockstore/dockstore#2964 I think we discussed in December no longer pointing out private tools or getting rid of them since it's not really used and the order of facets tbd once we work out other changes later (like the new facet ideas).

formatting changes

---

package.json

Update package.json to point to newest webservice 1.8.0-beta.9.

update test version of webservice

---

.circleci/config.yml

The existing sed was only replacing one instance of ../, should replace any number of ../
https://github.com/dockstore/dockstore/issues/2917

cdn regex should replace any number of ../

---

src/app/container/version-modal/version-modal.component.html
src/app/workflow/version-modal/version-modal.component.html

Dialog was _literally_ unusable 
...because you can't highlight any element inside it.

Revert drag-able dialog

---

src/app/loginComponents/onboarding/quickstart.component.html

https://github.com/dockstore/dockstore/issues/3177
Link at end of quick-start now works.

fix broken link

---

src/app/container/info-tab/info-tab.service.ts

For dockstore/dockstore#3180
Appears to be an error when trying to PUT /containers/{containerId} 
The starredUsers property from the UI is not understood by the webservice.
Solution: Removing ALL unused properties
Also added an alert to notify users when PUT has failed.

Fix PUT error

---

src/app/login/login.component.ts

Login -> homepage
Register -> onboarding
https://github.com/dockstore/dockstore/issues/3054
Edit:
Didn't see this was assigned already, but already did it.

When logging in, go to homepage. When registering, go to onboarding.

---

src/app/search/search.component.ts

Weird stuff with master having extra code that 2.5.0 doesn't.  Removing that code which is old anyways.

Fix merge conflicts from master

---

src/app/container/add-tag/add-tag.component.ts
src/app/login/login.service.ts
src/app/loginComponents/onboarding/onboarding.component.ts
src/app/myworkflows/my-bio-workflows.service.ts
src/app/organizations/collection/state/add-entry.query.ts
src/app/organizations/state/organizations.query.ts
src/app/register/register.service.ts
src/app/shared/entry/descriptor-language.service.ts
src/app/shared/state/checker-workflow.service.ts
src/app/shared/twitter.service.ts
src/app/workflow/dag/cwl-viewer/cwl-viewer.service.spec.ts
src/app/workflow/launch-third-party/launch-third-party.component.ts

Fix lint warnings
@coverbeck See if src/app/workflow/dag/cwl-viewer/cwl-viewer.service.spec.ts is correctly fixed.

Fix lint warnings

---

src/app/search/search.component.ts

The master branch did not match the 2.5 tag; fix
by making the match at the beginning of the hotfix branch.
```
~/git/dockstore/dockstore-ui2$ git diff feature/mergefix 2.5.0
~/git/dockstore/dockstore-ui2$
```

Make 2.5.1 hotfix match 2.5 tag

---

cypress/support/commands.ts
package.json
scripts/run-webservice-script.sh
travisci/web.yml

For debugging just the webservice update

Version update only

---

proxy.conf.json

Follow up for dockstore/compose_setup#120

Make Swagger-UI work in local dev mode

---

src/app/container/refresh-tool-organization/refresh-tool-organization.component.ts
src/app/workflow/workflow-file-editor/workflow-file-editor.component.ts

For dockstore/dockstore#3348
Fixed the original issue and also the one in the comments of it

Fix both endless loading bars

---

src/app/organizations/collections/state/create-collection.service.ts
src/app/shared/entry.ts
src/app/shared/entry/register-checker-workflow/register-checker-workflow.service.ts
src/app/shared/extended-tools.service.ts
src/app/shared/extended-workflows.service.ts
src/app/shared/file.service.ts
src/app/shared/launch.service.ts
src/app/sponsors/sponsors.component.html
src/app/workflow/permissions/permissions.component.ts
src/app/workflow/tool-tab/tool-tab.component.html
src/app/workflow/version-modal/version-modal.service.ts
src/app/workflow/workflow.component.html

Tried to go through the alerts one by one and addressed the ones that made sense to me/didn't seem like I'd inadvertently break something 
Alerts here: https://lgtm.com/projects/g/dockstore/dockstore-ui2/?mode=list

lgtm recommended changes

---

src/app/shared/refresh.service.ts

2 PRs went out at the same'ish time. The merge build wasn't up to date which is now causing a build issue on develop. This fixes it.

Fix merge issue

---

src/app/shared/user/user.service.ts

My WIP somehow made it into one of my previous PRs which was not intended. 
https://github.com/dockstore/dockstore-ui2/commit/84e6cf479758b539dd6e414176f360f2eac80885#diff-26a32f2391f5d51dc0d470a1231780c6
This reverts it back to the original.

Revert logout fix

---

src/app/workflow/workflow.component.html

https://github.com/dockstore/dockstore/issues/3415
Remove reference to SERVICE mode (now use DOCKSTORE_YML as mode and SERVICE as descriptor type).

remove reference to service mode

---

.circleci/config.yml
cypress/integration/manualTests/monitor.ts
package.json
src/app/search/search-tool-table/search-tool-table.component.html
src/app/search/search-workflow-table/search-workflow-table.component.html
src/app/workflow/launch-third-party/launch-third-party.component.html

Automated tests on dev.dockstore.net are going to fail for now because they depend on `data-cy` attributes which I added to the UI on this branch

Automate daily tests

---

cypress/integration/group1/hostedTools.ts
cypress/integration/group1/hostedWorkflows.ts
src/app/container/container.component.html
src/app/workflow/workflow.component.html

For dockstore/dockstore#3193
Should be good enough for the users to understand how to add a version when there are currently no versions.

Specify how to add version

---

src/app/organizations/collection/collection.component.html

For SEAB-1132
Requires 1.8.6 hotfix

Collection Entries 

---

cypress/integration/manualTests/basic-enduser.ts
cypress/integration/manualTests/monitor.ts

separated out from auth tests PR to get nightly tests working

removed duplicate test, commented out flaky DAG test

---

cypress/integration/group2/organizations.ts
scripts/run-webservice-script.sh

Tests were failing because of 1.9 things in the web.yml.

Use develop web service jar to get tests to pass

---

src/app/shared/validationMessages.model.ts
src/app/workflow/register-workflow-modal/register-workflow-modal.component.html
src/app/workflow/register-workflow-modal/register-workflow-modal.component.ts

validation messages

---

src/app/home-page/widget/entries/entries.component.ts
src/app/home-page/widget/filtered-list.ts

Addresses:
dockstore/dockstore#3418
https://ucsc-cgl.atlassian.net/browse/DOCK-1327

Fix debounce for Find entries

---

cypress/integration/group2/myworkflows.ts
src/app/shared/constants.ts
src/app/workflow/info-tab/info-tab.component.html
src/app/workflow/info-tab/info-tab.component.ts
src/app/workflow/register-workflow-modal/register-workflow-modal.component.html
src/app/workflow/register-workflow-modal/register-workflow-modal.component.ts

For https://ucsc-cgl.atlassian.net/browse/SEAB-1341
Constant that you can toggle to make GitHub Apps recommended or not.  Though reverting this PR would be cleaner in certain cases.
Test kept failing for some reason, changed it to be more specific.

Feature/seab 1341/toggle GitHub app recommendation

---

cypress/integration/group2/myworkflows.ts
src/app/myworkflows/sidebar-accordion/github-apps-logs/github-apps-logs.component.html
src/app/myworkflows/sidebar-accordion/github-apps-logs/github-apps-logs.component.ts

For partial SEAB-1367
Added frontend-pagination, backend is probably not going to be ready for 1.9.0 (push to 1.9.x?)
Put the alerts into cards
Fixed the strict null check issues in the file.

Feature/seab 1367/pretty alerts and pagination

---

src/app/workflow/workflow.component.html

show verified icon

---

src/app/loginComponents/onboarding/downloadcliclient/downloadcliclient.component.html
src/app/loginComponents/onboarding/downloadcliclient/downloadcliclient.component.scss
src/app/loginComponents/onboarding/downloadcliclient/downloadcliclient.component.spec.ts
src/app/loginComponents/onboarding/downloadcliclient/downloadcliclient.component.ts

dockstore/dockstore#3570
Some of the formatting is weird inthe code, but looks like

quickstart for Mac

---

src/app/organizations/organization/organization-starring/organization-starring.service.ts

For dockstore/dockstore#2395 part 3
Use the new restful starring endpoint (need to do this before previous one is removed).

Use new restful starring endpoint

---

src/app/organizations/organization/organization-stargazers/organization-stargazers.component.ts
src/app/organizations/organization/organization-starring/organization-starring.service.ts

dockstore/dockstore#3553 organization-stargazers component had the stargazers HTML but not the corresponding CSS, causing the sizing to be wrong.

applied stargazers CSS to organizations

---

src/app/home-page/recent-events/recent-events.component.scss
src/app/home-page/widget/news-updates/news-updates.component.html
src/styles.scss

* timestamps on news and updates UI
* move .subtitle class to styles.scss
See https://github.com/dockstore/dockstore/issues/3307 and https://github.com/dockstore/dockstore-ui2/pull/1026

timestamps on news and updates UI (#1026)

---

cypress/integration/group2/myworkflows.ts
src/app/myworkflows/sidebar-accordion/github-apps-logs/github-apps-logs.component.html
src/app/myworkflows/sidebar-accordion/github-apps-logs/github-apps-logs.component.scss
src/app/myworkflows/sidebar-accordion/github-apps-logs/github-apps-logs.component.ts
src/app/search/map-friendly-values.pipe.ts

For dockstore/dockstore#3606 and dockstore/dockstore#3610
Originally based on "Table with expandable rows" of https://material.angular.io/components/table/examplesAdds , now adds a pointer on hover based on this random guy https://stackoverflow.com/a/46931989
~And no, there's no vertical room to display the message by default or horizontal room to show https://mdbootstrap.com/snippets/jquery/cam/979615~
Added it to the same column as date and then shortened the date to have the expand icons
~The console error is a legit console error and the message displayed is intuitive for me and it's hard for me to "imagine if it was not intuitive"~
Added a category of keys in which we allow null/undefined in the friendly map

Pointer on hover

---

src/app/workflow/info-tab/info-tab.service.ts

Temporary fix for dockstore/dockstore#3662 .  Additional webservice fix is preferable

Don't send back users or starred users

---

src/app/home-page/home-logged-out/home.component.html
src/app/shared/entry/descriptor-language.service.ts
tsconfig.json

For dockstore/dockstore#3665
Interesting, webservice returns Galaxy before Nextflow

Mention Galaxy on Logged-out homepage

---

cypress/support/commands.ts
package.json
scripts/generate-openapi-script.sh
scripts/run-webservice-script.sh
src/app/containers/list/published-tools.datasource.spec.ts
src/app/shared/image-provider.service.spec.ts
src/app/shared/image-provider.service.ts
src/app/test/service-stubs.ts

RIP previous CircleCI Jar, here's a newer one
Had a breaking change in the last 30 days. Needed to make some modifications to tests

Update CircleCI Jar

---

src/app/source-file-tabs/source-file-tabs.component.html
src/app/source-file-tabs/source-file-tabs.component.spec.ts
src/app/source-file-tabs/source-file-tabs.component.ts

For dockstore/dockstore#3608
~Bug fixed but unclear if this component should even initialize if version is null.  Need confirmation before I simplify the component.~
- Endpoint was called on OnInit and also when a version is changed, modifying to only call endpoint on ngOnChanges
- Added a truthy check to make sure the component is not initialized unless version is truthy which allowed some simplificiations

Use ngOnChanges

---

README.md
package.json

Part of https://ucsc-cgl.atlassian.net/browse/SEAB-1614

test against 1.9.1

---

package.json
scripts/generate-openapi-script.sh
scripts/run-webservice-script.sh

part of https://ucsc-cgl.atlassian.net/browse/SEAB-1614

test against 1.10.0-alpha.0

---

.circleci/config.yml
package.json
scripts/generate-openapi-script.sh
scripts/run-webservice-script.sh
src/app/organizations/collection/state/add-entry.service.ts
src/app/organizations/state/organization-members.query.ts
src/app/organizations/state/organization-members.service.ts

dockstore/dockstore#3742
Relates to this web service PR https://github.com/dockstore/dockstore/pull/3762#pullrequestreview-475849753

update organization user roles

---

.circleci/config.yml
src/app/source-file-tabs/source-file-tabs.component.html
src/app/source-file-tabs/source-file-tabs.component.spec.ts
src/app/source-file-tabs/source-file-tabs.component.ts

For dockstore/dockstore#3608
was previously https://github.com/dockstore/dockstore-ui2/pull/1044 merged to develop instead of hotfix
* Use ngOnChanges
* Don't initialize component when version is null

Use ngOnChanges (#1044)

---

package.json
scripts/generate-openapi-script.sh
scripts/run-webservice-script.sh
src/app/container/paramfiles/paramfiles.service.spec.ts
src/app/container/tool-file-editor/tool-file-editor.component.ts
src/app/test/mocked-objects.ts
src/app/workflow/workflow-file-editor/workflow-file-editor.component.ts

Looks like I accidentally left a line in 
dockstore/dockstore#3644 
dockstore/dockstore#3712

update to build off develop, remove sourcefile line

---

.gitallowed
package.json
scripts/install-git-secrets.sh

Addresses https://ucsc-cgl.atlassian.net/browse/SEAB-1517

add git secrets checks

---

src/app/funding/funding.component.ts

https://ucsc-cgl.atlassian.net/browse/SEAB-1773

Change CFI funding text

---

package.json
scripts/generate-openapi-script.sh
scripts/run-webservice-script.sh

Use latest web service artifacts

---

cypress/integration/manualTests/auth-tests.ts

Mock didn't take new parameter into account.
Just entered (and verified) what Gary figured out

Fix failing auth tests on dev

---

src/app/shared/entry/info-tab-checker-workflow-path/info-tab-checker-workflow-path.component.html
src/app/workflow/info-tab/info-tab.component.html
src/app/workflow/info-tab/info-tab.component.ts
src/app/workflow/info-tab/info-tab.service.ts

- frontend changes for [3739](https://github.com/dockstore/dockstore/issues/3739)
- discussion link appears in workflow info-tab
- the link can be edited by owner

Can add and edit forumurl to workflow

---

cypress/integration/group2/organizations.ts
package.json
scripts/generate-openapi-script.sh
scripts/run-webservice-script.sh
src/app/container/container.component.html
src/app/entry/current-collections/current-collections.component.ts
src/app/organizations/collection/add-entry/add-entry.component.html
src/app/organizations/collection/add-entry/add-entry.component.ts
src/app/organizations/collection/collection.component.html
src/app/organizations/collection/state/add-entry.service.ts
src/app/workflow/workflow.component.html

For https://ucsc-cgl.atlassian.net/browse/SEAB-1639
- used the existing dialog and just added an optional version field
- modified to use the outline form field
Surprisingly didn't need any additional webservice changes.

Feature/seab 1639/collection entry version

---

cypress/integration/manualTests/search.ts
package.json

- for [SEAB-2046](https://ucsc-cgl.atlassian.net/browse/SEAB-2046)
- update ES query from _type to _index
- changed paginator selector to be less flaky

Fixed failing manual search tests

---

package.json
scripts/generate-openapi-script.sh
scripts/run-webservice-script.sh

Test with final webservice release

Final test

---

src/app/container/tool-file-editor/tool-file-editor.component.ts
src/app/shared/file-editing.ts
src/app/workflow/workflow-file-editor/workflow-file-editor.component.ts

added two methods: getIdOfNewestVersion, and getNewestVersion. Not sure if the former is necessary, also added detailed success message

Added success message and methods

---

cypress/integration/manualTests/basic-enduser.ts
src/app/search/search-results/search-results.component.html

- for [SEAB-2142](https://ucsc-cgl.atlassian.net/browse/SEAB-2142)

update smoke tests from tag cloud to popular keywords

---

.circleci/config.yml

Turns out increasing resource is probably not needed. Still need to limit memory usage though (copied build command from other jobs)

Limit memory usage

---

cypress/integration/group1/checkerWorkflowFromTools.ts
src/app/search/search-tool-table/search-tool-table.component.html
src/app/search/search-workflow-table/search-workflow-table.component.html
src/styles.scss

[dockstore/dockstore/issues/3996](https://github.com/dockstore/dockstore/issues/3996)
Used media queries, added a class called "align-languages" used solely for responsive resizing

language labels display styling

---

cypress/integration/manualTests/basic-enduser-prod-only.ts
cypress/integration/manualTests/basic-enduser.ts
package.json

https://ucsc-cgl.atlassian.net/browse/SEAB-1632

Seab 1632/tool tester logs smoke test

---

cypress/integration/manualTests/monitor.ts
src/app/footer/footer.component.html

created more data-cy IDs used for footer links

---

src/app/loginComponents/onboarding/downloadcliclient/downloadcliclient.component.ts
src/app/shared/launch.service.ts

add nextflow install instructions

---

cypress/integration/manualTests/basic-enduser.ts
cypress/integration/manualTests/search.ts
src/app/search/search-results/search-results.component.html
src/app/search/search.component.ts
src/app/search/state/search.service.ts

Fix for tests and also the tab change not triggering facet reset
Edit to add: follows #1127

Fix tests + tab change filter reset

---

cypress/integration/manualTests/basic-enduser.ts

`/integration/manualTests/basic-enduser.ts`

Github to GitHub

---

src/app/footer/footer.component.html

typo in img src

---

THIRD-PARTY-LICENSES.csv
package-lock.json
package.json

https://ucsc-cgl.atlassian.net/browse/SEAB-2523

Update dompurify to latest version (2.2.7)

---

cypress/integration/group1/checkerWorkflowFromWorkflow.ts
cypress/support/commands.ts
scripts/generate-openapi-script.sh
scripts/run-webservice-script.sh
src/app/shared/constants.ts
src/app/shared/entry-actions/entry-actions.service.ts

dockstore/dockstore#4080
pairs with this PR https://github.com/dockstore/dockstore/pull/4135

build against webservice that lazy loads versions

---

src/app/search/search.component.ts

https://ucsc-cgl.atlassian.net/browse/SEAB-2515
Show the error to the user if their search request exceeds new limit.

show error if when url request is too large on search page

---

src/app/loginComponents/requests/requests.component.ts
src/app/loginComponents/state/requests.service.ts

Don't refresh curator's orgs if not curator

---

cypress/integration/manualTests/basic-enduser.ts

Added two lines to ensure the result table is properly rendered before moving on

 ensure the result table is properly rendered in basic-enduser.ts

---

src/app/about/about.component.css
src/app/about/about.component.html
src/app/footer/footer.component.css
src/app/footer/footer.component.html
src/app/home-page/home-logged-out/home.component.html
src/app/navbar/navbar.component.html
src/app/organizations/collection/collection.component.html
src/app/organizations/organization/organization.component.html
src/app/organizations/organizations/organizations.component.html
src/app/organizations/organizations/organizations.component.scss
src/bootstrap4.scss
src/styles.scss

Please refer to the points that are crossed off in this document: https://docs.google.com/document/d/1GLshBv7Ue09ceCFDSLmFvrgbEofGkY6R0jXlKxVjqHc/edit?ts=607ded9d
Screenshots(only some minor changes):
1. Added a side scrollbar for cards that have too much content(only visible when scrolling):
other things are pretty straight forward, if screenshots are needed then I will insert them here

minor adjustments to multiple pages

---

src/app/container/refresh-tool-organization/refresh-tool-organization.component.ts
src/app/workflow/refresh-workflow-organization/refresh-workflow-organization.component.ts

For dockstore/dockstore#3811
Not entirely sure why the error isn't being thrown to the outer observable (also couldn't be thrown). Catching it in the inner observable instead.

Catch error in inner observable

---

src/app/search/query-builder.service.ts

Now that we're back on ES 7.10, we can revert commit 48a245cc
dockstore/dockstore#4143

Revert "Remove 7.10 Elasticsearch feature"

---

src/app/about/about.component.html

Working on https://github.com/dockstore/dockstore/issues/4045 and SEAB-2907
Needs follow-up work via SEAB-2915

Add citation info for new paper, sync FAIR text

---

src/app/entry/extendedDescriptorLanguage.ts
src/app/shared/entry/descriptor-language.service.spec.ts
src/app/workflow/register-workflow-modal/register-workflow-modal.component.html
src/app/workflow/workflow.component.html

remove preview label for galaxy

---

src/app/organizations/organizations/organizations.component.html
src/app/organizations/organizations/organizations.component.ts

For SEAB-2494
Frontend pagination only. Kind of weird numbers I've chosen (9, 18, 36).
https://user-images.githubusercontent.com/24548904/118706504-6bde6f00-b7e7-11eb-95fc-88294fb864b3.mp4
Also feels like I'm missing something
Unrelated: at the end of the video, i show myself clicking in the text field. Does it look weird like that for anyone?

Add frontend pagination

---

src/app/loginComponents/auth/auth.component.ts

Extra redirect removal.
@garyluu  pointed this out during a review of https://ucsc-cgl.atlassian.net/browse/SEAB-2782 (PR: https://github.com/dockstore/dockstore-ui2/pull/1200)

Removed doubled redirect

---

src/app/workflow/launch-third-party/multi-cloud-launch/multi-cloud-launch.component.ts

https://ucsc-cgl.atlassian.net/browse/SEAB-2971
Attempts to create and save a user's custom launch url and ignore if it fails so the user can continue with launch.
Doesn't save any custom launch urls if the user isn't logged in.

Save user's custom launch to db

---

src/app/about/about.component.html
src/app/home-page/widget/entries/entries.component.html
src/app/home-page/widget/organizations/organizations.component.html

Follow-up on SEAB-2737
Also probably need to mess with Dockstore.DOCUMENTATION_URL on deploy

Point at stable

---

src/app/about/about.component.html
src/app/home-page/home-logged-out/home.component.html

Followup for https://ucsc-cgl.atlassian.net/browse/SEAB-2907
(log in when used as verb, login when used as noun)

Tiny, tiny word tweaking.

---

src/app/shared/dockstore.model.ts

May also need to consider orcid, let's test that for the next week or two depending on procurement

delay dnastack multi activation

---

package.json
scripts/generate-openapi-script.sh
scripts/run-webservice-script.sh

Will merge this one, for the release checklist

Test with hopefully the final artifacts

---

src/app/shared/grammars/custom-grammars.js

For dockstore/dockstore#2921
Could not manage to feasibly update anything. Everything seems fine as is. See comments of code and issue.

Add comments

---

.github/dependabot.yml

Related: [SEAB-3008](https://ucsc-cgl.atlassian.net/browse/SEAB-3008)

Add dependabot config file to enable dependabot in dockstore-ui2

---

src/app/loginComponents/accounts/external/accounts.component.html
src/app/loginComponents/accounts/external/accounts.component.ts

Feedback from ORCID meeting: add an additional note on what is ORCID. Kind of hacky.

Add extra note about what is ORCID

---

src/styles.scss

Changed the ORCID logo from 14x14 to 16x16

Changed ORCID Logo Size

---

src/app/workflow/dag/state/dag.service.ts

For dockstore/dockstore#4333
See https://popper.js.org/docs/v2/migration-guide/#8-update-method-names

scheduleUpdate() => update()

---

src/app/container/register-tool/register-tool.component.html
src/app/workflow/register-workflow-modal/register-workflow-modal.component.html
src/app/workflow/register-workflow-modal/register-workflow-modal.component.ts

For dockstore/dockstore#1873
Register tool dialog was never converted to Material because of the first field

Generate final path, change input appearance

---

src/app/search/search.component.ts
src/app/test/service-stubs.ts

For https://github.com/dockstore/dockstore/issues/4026: reset the page number every time there's a new search

Reset page number for new search

---

cypress/integration/immutableDatabaseTests/services.ts
src/app/source-file-tabs/source-file-tabs.component.html
src/app/source-file-tabs/source-file-tabs.component.ts
src/app/source-file-tabs/source-file-tabs.service.ts

- correctly show warning if there's no files
- put main descriptor before all the other files of the same type

Feature/seab 3119/refactor file tab

---

src/app/descriptor-languages/CWL.ts
src/app/descriptor-languages/Galaxy.ts
src/app/descriptor-languages/Nextflow.ts
src/app/descriptor-languages/Service.ts
src/app/descriptor-languages/WDL.ts
src/app/entry/extendedDescriptorLanguage.ts
src/app/source-file-tabs/source-file-tabs.component.ts
src/app/source-file-tabs/source-file-tabs.service.ts

One of many many PRs for SEAB-3140
Splitting out the file tabs "schematic" to be in the extendedDescriptorLanguageBean. Moved the beans of each language to be in their own file in a new descriptor-languages directory

Feature/seab 3140/language plugin

---

src/app/container/container.component.html
src/app/loginComponents/accounts/external/accounts.component.html
src/app/loginComponents/onboarding/onboarding.component.html
src/app/workflow/dag/cwl-viewer/cwl-viewer.html
src/app/workflow/permissions/permissions.component.html
src/app/workflow/workflow.component.html

For https://ucsc-cgl.atlassian.net/browse/SEAB-2819

Adding rel='noopener' to outgoing links in UI2

---

package.json
src/app/descriptor-languages/CWL.ts
src/app/descriptor-languages/Galaxy.ts
src/app/descriptor-languages/Nextflow.ts
src/app/descriptor-languages/Service.ts
src/app/descriptor-languages/WDL.ts
src/app/entry/extendedDescriptorLanguage.ts
src/app/shared/entry/register-checker-workflow/register-checker-workflow.component.ts
src/app/shared/entry/register-checker-workflow/register-checker-workflow.service.ts
src/app/workflow/launch-third-party/launch-third-party.component.ts
src/app/workflow/register-workflow-modal/register-workflow-modal.service.ts

Part 3 of unknown. This is required for Part 2 https://github.com/dockstore/dockstore/pull/4387
Need to change package.json after Part 2 merged
One oddity is that the DescriptorLanguage in the openapi has varying lowercases, but the generated swagger client here is uppercase only but still works.

Feature/seab 3140/language plugin endpoint changes

---

src/app/footer/footer.component.html

https://github.com/dockstore/dockstore/issues/4375
Forum is redundant with the top, no support aside from discourse that we wish to encourage yet

Disable till result of discussion

---

package.json
scripts/generate-openapi-script.sh
scripts/run-webservice-script.sh

test with 1.11.6. artifacts

---

cypress/integration/group2/organizations.ts
cypress/integration/group2/starEntry.ts
src/app/loginComponents/accounts/external/accounts.component.ts
src/app/organizations/organizations/organizations.component.html
src/app/organizations/organizations/organizations.component.ts
src/app/organizations/register-organization.module.ts
src/app/organizations/registerOrganization/register-organization.component.html
src/app/organizations/registerOrganization/register-organization.component.ts
src/app/organizations/registerOrganization/requireAccountsModal/require-accounts-modal.component.html
src/app/organizations/registerOrganization/requireAccountsModal/require-accounts-modal.component.ts
src/app/organizations/state/register-organization.service.ts

https://ucsc-cgl.atlassian.net/browse/SEAB-3275

require email and two linked accounts to request an organization

---

package.json
src/app/loginComponents/accounts/external/accounts.component.html

* `npm run bulld` died locally, did our id change? (looking at blame, probably just expired)
* fix orcid id underline https://ucsc-cgl.atlassian.net/browse/SEAB-3244

circle ci id change and most significant commit ever

---

cypress/integration/group2/usernameChangeRequired.ts
package.json
src/app/app.component.html
src/app/app.component.ts
src/app/app.module.ts
src/app/changeUsernameBanner/changeUsernameBanner.component.html
src/app/changeUsernameBanner/changeUsernameBanner.component.ts
src/app/loginComponents/accounts/internal/change-username/change-username.component.html
src/app/loginComponents/accounts/internal/change-username/change-username.component.ts
src/app/loginComponents/onboarding/onboarding.component.html
src/app/loginComponents/onboarding/onboarding.component.ts
src/app/workflow/register-workflow-modal/register-workflow-modal.component.html
src/app/workflow/register-workflow-modal/register-workflow-modal.component.ts

Pairs with https://github.com/dockstore/dockstore/pull/4562. This displays a banner that follows users around the site telling them they need to change their username. Also adds a warning when they rename themselves and disables the github app installation button.
**Issue**
https://ucsc-cgl.atlassian.net/browse/SEAB-3210

change username

---

package.json
src/app/configuration.service.ts
src/app/footer/footer.component.ts
src/app/footer/footer.service.spec.ts
src/app/footer/footer.service.ts
src/app/shared/dockstore.model.ts

Add the lambda/plugin versions to the copy build info button. It's going to say null for a while no dev until it's set
**Issue**
For SEAB-3517

Add lambda/plugin version to build info

---

src/app/workflow/info-tab/info-tab.component.html
src/app/workflow/info-tab/info-tab.component.ts

Show a simple warning in the workflow version info tab
**Issue**
For dockstore/dockstore#4560

Calculate has imports and show warning

---

cypress/integration/group2/mytools.ts
cypress/integration/group2/myworkflows.ts
package.json
src/app/container/container.component.html
src/app/container/info-tab/info-tab.component.css
src/app/container/info-tab/info-tab.component.html
src/app/container/info-tab/info-tab.component.ts
src/app/container/info-tab/info-tab.service.ts
src/app/search/query-builder.service.ts
src/app/search/search-tool-table/search-tool-table.component.html
src/app/search/search-workflow-table/search-workflow-table.component.html
src/app/shared/container.service.ts
src/app/shared/entry-actions/tool-actions.component.html
src/app/shared/entry-actions/workflow-actions.component.html
src/app/shared/state/workflow.service.ts
src/app/workflow/info-tab/info-tab.component.css
src/app/workflow/info-tab/info-tab.component.html
src/app/workflow/info-tab/info-tab.component.ts
src/app/workflow/info-tab/info-tab.service.ts
src/app/workflow/workflow.component.html

Separate topic into topicManual and topicAutomatic. Also added topic selection.
The ul, li structure of the workflow counterpart is kind of a mess due to an existing issue but fixing it now would probably be inefficient when an existing bootstrap issue would probably end up changing it anyways.
**Issue**
SEAB-3698

Feature/seab 3698/topic sentence phase2

---

package.json
scripts/run-webservice-script.sh
src/app/container/register-tool/register-tool.component.html
src/app/mytools/mytools.service.ts
src/app/workflow/workflow.component.html
src/app/workflow/workflow.component.ts

Uses tool icon now
Fixes the navigation bug when there are unpublished tools
Not a ticket, but also fixes an api call
**Issue**
https://ucsc-cgl.atlassian.net/browse/SEAB-3827
https://ucsc-cgl.atlassian.net/browse/SEAB-3780

some github app tool fixes.

---

cypress/integration/group2/githubAppTools.ts
cypress/support/commands.ts
src/app/container/container.component.ts
src/app/workflow/info-tab/info-tab.component.html
src/app/workflow/version-modal/version-modal.component.html
src/app/workflow/versions/versions.component.html
src/app/workflow/workflow.component.html
test/github_app_tool_db_dump.sql

Add some tests
https://ucsc-cgl.atlassian.net/browse/SEAB-3733
icon:
https://ucsc-cgl.atlassian.net/browse/SEAB-3827
fix redirect:
https://ucsc-cgl.atlassian.net/browse/SEAB-3825
trs link:
https://ucsc-cgl.atlassian.net/browse/SEAB-3828

add tests, fix view public and trs link

---

src/app/about/about.component.html
src/app/docs/docs.component.ts
src/app/home-page/widget/entries/entries.component.html
src/app/home-page/widget/entries/entries.component.ts
src/app/home-page/widget/organizations/organizations.component.html
src/app/home-page/widget/organizations/organizations.component.ts
src/app/loginComponents/auth/auth.component.ts
src/app/shared/dockstore.model.ts

Use the global variable more for pointing at the docs, allowing us to point certain deployments elsewhere
**Issue**
https://ucsc-cgl.atlassian.net/browse/DOCK-2016

more DOCUMENTATION_URL

---

cypress/integration/group2/githubAppTools.ts
src/app/mytools/my-tool/my-tool.component.html
src/app/mytools/my-tool/my-tool.component.ts
src/app/mytools/mytools.service.ts
src/app/myworkflows/myworkflows.service.ts
src/app/shared/state/workflow.service.ts
src/app/workflow/version-modal/version-modal.component.html
src/app/workflow/version-modal/version-modal.component.ts
src/app/workflow/versions/versions.component.html

https://ucsc-cgl.atlassian.net/browse/SEAB-3826
Don't need to refresh page after publishing/unpublishing tool to see list updated
https://ucsc-cgl.atlassian.net/browse/SEAB-3844
Change text in edit version

Fix publishing and edit bugs

---

.circleci/config.yml
src/app/workflow/launch/launch.component.html
src/app/workflow/launch/launch.component.ts
src/app/workflow/launch/workflow-launch.service.ts

The GitHub App Tool actually uses the workflow mode in the Dockstore CLI.
Also changed the m-2 repetition which should hopefully be fine
**Issue**
SEAB-3730

Change make-template command

---

package.json

Test with the tagged hotfix webservice release
**Issue**
https://github.com/dockstore/dockstore-deploy/wiki/1.11.11-staging-checklist

Test with hotfix release

---

cypress/integration/smokeTests/sharedTests/auth-tests.ts

This PR re-introduces `cy.waits()` that'd I'd previously removed in: https://github.com/dockstore/dockstore-ui2/pull/1448, because that PR didn't really fix anything... Any suggestions appreciated.
The UI uses javascript to update asynchronously, Cypress is grabbing DOM elements that, after the UI updates, are considered detached, causing tests to fail. After spending a while trying to identify when the UI had updated sufficiently, I was still hitting flakey tests, and succumbed to re-introducing `cy.wait()` at a higher timeout than before.
Hopefully this PR will reduce the flakiness of the auth tests, but it isn't guaranteed. If the auth tests fail again, I'll create a followup ticket to refactor the `my-tools` and `my-workflows` components to see if the flakiness is …

Flakey Auth Tests Round Three

---

src/app/app.module.ts
src/app/entry/current-collections.module.ts
src/app/entry/current-collections/current-collections.component.html
src/app/gravatar/gravatar.pipe.spec.ts
src/app/gravatar/gravatar.pipe.ts
src/app/gravatar/gravatar.service.spec.ts
src/app/gravatar/gravatar.service.ts
src/app/organizations/collection/collection.component.html
src/app/organizations/collection/collection.component.ts
src/app/organizations/collections.module.ts
src/app/organizations/organization/organization.component.html
src/app/organizations/organization/organization.component.ts
src/app/organizations/organizations.module.ts
src/app/organizations/organizations/organizations.component.html
src/app/organizations/state/organization.query.spec.ts
src/app/organizations/state/organization.query.ts
src/app/organizations/state/organization.service.ts
src/app/shared/pipe/pipe.module.ts
src/app/shared/user/user.service.ts
src/app/starredentries/starredentries.component.html

Problem was due to strict-origin-when-cross-origin policy on the
image. Using gravatar fixes it (and is why it worked on the single Org page).
Consolidated all the gravatar calls into one service.
**Issue**
#4700
- [] Run `npm audit` and ensure you are not introducing new vulnerabilities

Org logo not displaying on Orgs page

---

src/app/home-page/home-logged-out/home.component.html
src/app/workflow/launch-third-party/launch-third-party.component.html
src/app/workflow/launch-third-party/launch-third-party.component.spec.ts

Some stuff that made it into the most recent hotfix (2.8.5)  but not into the release 
(presumably because we hubflow hotfix finished the previous hotfix after we started the release branch)
**Issue**
https://ucsc-cgl.atlassian.net/browse/SEAB-3950

Hotfix sync

---

package.json

test a newer version of the webservice
**Issue**
n/a for 1.12 release

UI branch testing

---

package.json

test with final1.12.0 release
**Issue**
https://github.com/dockstore/dockstore-deploy/wiki/1.12-staging-checklist#pre-deploy-1

test with final release

---

cypress.json

Use unique userAgent in cypress config to enable filtering usage analytics in Google.
**Issue**
https://ucsc-cgl.atlassian.net/browse/SEAB-4202

Add userAgent to cypress.json (SEAB-4202)

---

.github/workflows/update_license.yml

expand scope of license update to snyk
**Issue**
see https://github.com/dockstore/dockstore/pull/4935

expand scope of license update to snyk

---

package.json
src/app/search/query-builder.service.ts

UI counterpart to https://github.com/dockstore/dockstore/pull/5023/files
Will change circle ci artifact branch after companion is merged
**Issue**
https://github.com/dockstore/dockstore/issues/5016

add sorting so UI requests 200 max in sorted order

---

src/app/workflow/launch-third-party/launch-third-party.component.html

remove superfluous warning 
**Issue**
https://github.com/dockstore/dockstore/issues/5028

clean up warning

---

src/app/shared/entry/launch-checker-workflow/launch-checker-workflow.component.html
src/app/shared/entry/launch-checker-workflow/launch-checker-workflow.component.ts
src/app/workflow/launch/launch.component.html

Adds a pile of copy buttons
**Issue**
https://github.com/dockstore/dockstore/issues/4309

add buttons

---

src/app/home-page/home-page.module.ts

Not very exciting, seems to have broken registering quay.io tools
Might be bad merge conflict, not sure why this gets past compiler before
**Issue**
https://ucsc-cgl.atlassian.net/browse/SEAB-4706

looks like an import error

---

package.json
src/app/home-page/home-logged-in/home-logged-in.component.ts
src/app/home-page/recent-events/recent-events.component.html

Checks for nulls for a bunch of events 
**Issue**
n/a detected during staging spot checking
Makes the recent events widget go into indeterminate loading and somewhat slows down interacting with the whole page

throw in a bunch of null checks

---

.github/PULL_REQUEST_TEMPLATE.md

Add checkbox for documentation
**Issue**
https://ucsc-cgl.atlassian.net/browse/SEAB-3061

Update PR template for docs

---

src/app/mytools/my-tool/my-tool.component.html

Removed random '>' characted in My Tools when there are no tools.
Before fix: 
After fix: 
**Issue**
https://ucsc-cgl.atlassian.net/browse/DOCK-2254

DOCK-2254 bug fix

---

.github/PULL_REQUEST_TEMPLATE.md

Add PR review instructions.
**Issue**
[SEAB-4067](https://ucsc-cgl.atlassian.net/browse/SEAB-4067)

Add review instructions

---

src/app/search/query-builder.service.ts

Cherry-pick of #1639 -- see that PR for details.
Cherry-pick of #1639 -- see that PR for details.
**Issue**
dockstore/dockstore#5220

Set size of hits to 0 for tag cloud query (#1639)

---

.github/PULL_REQUEST_TEMPLATE.md
cypress/integration/group2/organizations.ts

Checklist item, see changes
n/a
**Issue**
https://ucsc-cgl.atlassian.net/browse/SEAB-5022

add checklist item for tests

---

cypress/integration/group2/organizations.ts
src/app/home-page/home-logged-out/home.component.html
src/app/loginComponents/onboarding/downloadcliclient/downloadcliclient.component.ts

Add warning against the use of Docker Desktop with Dockstore CLI
See that the warning appears in the quick-start
**Issue**
https://github.com/dockstore/dockstore/issues/5135

update and add warning for Linux

---

.github/PULL_REQUEST_TEMPLATE.md

Checklist item to check target branch.
Click the button to create a PR. You should see a checklist item that says "Ensure that the PR targets the correct branch. Check the milestone or fix version of the ticket."
**Issue**
https://ucsc-cgl.atlassian.net/browse/SEAB-4603

Update PR template for target branch

---

.circleci/config.yml

Deal with https://github.com/CircleCI-Public/browser-tools-orb/issues/62
Build should just work
**Issue**
n/a
**Security**
n/a

fix build issue with chromedriver

---

src/app/shared/code-editor/code-editor.component.ts

As the ticket mentions, groovy files don't have syntax highlighting like other file types do in the UI.
I tried looking around at the highlight rules in `custom-grammars.js` with no luck, then checked out `code-editor.components` and realized that we're not switching the editor mode when viewing a `.groovy` file -> so it was being displayed as a simple text file.  Added the check and all was _groovy_ ;)
**Before:**
**After:**
**Steps to reproduce:**
1. Go to https://qa.dockstore.org/workflows/github.com/nf-core/hic:TEMPLATE?tab=files
2. Click on "Select File"
3. Click on "lib"
4. Choose any .groovy file
**Issue**
[DOCK-2304
](https://ucsc-cgl.atlassian.net/browse/DOCK-2304?atlOrigin=eyJpIjoiOGYwMjJmMjg3NzI1NDg4NDllYjdmYzIzZDdiMGMyOTIiLCJwIjoiaiJ9) …

Groovy Files Missing Syntax Highlighting

---

cypress/e2e/group2/myworkflows.ts
cypress/e2e/group3/mytools.ts
cypress/e2e/group3/starEntry.ts
cypress/e2e/immutableDatabaseTests/admin.ts
cypress/e2e/immutableDatabaseTests/app-spec.ts
cypress/e2e/immutableDatabaseTests/curator.ts
cypress/e2e/immutableDatabaseTests/dropdown.ts
src/app/navbar/navbar.component.html
src/app/navbar/navbar.component.scss

Updated dropdown on navbar to look like the zeplin mockups.
UI after changes:
Zeplin mockups
https://app.zeplin.io/project/5fc690a2717ee9144814f190/screen/6022acb6632937281e6935ec. 
Verify that the new changes represent the mockups accurately and the integration tests still pass.
**Issue**
https://github.com/dockstore/dockstore/issues/5261
**Security**

DOCK-2290: updated navbar dropdown

---

README.md
src/app/home-page/home-logged-out/home.component.html
src/app/loginComponents/onboarding/downloadcliclient/downloadcliclient.component.ts

Update quickstart to Java 17. 
Will rename/refocus ticket on Mac afterwards
Take a look at linux instructions, they should just work. Can use a docker container to test up to actually running a workflow. 
**Issue**
https://ucsc-cgl.atlassian.net/browse/SEAB-5074
**Security**
None

update references to java (linux)

---

package.json
src/app/search/map-friendly-values.pipe.ts
src/app/search/state/search.service.ts

Surface the Open Data facet. 
The facets column is getting really long, I wonder if it should start out collapsed by default? But that's for another issue/discussion.
Verify that the open data facets are present as in the screenshots, and that clicking a search result when the `Has public test data` checkbox is selected, takes you to a workflow with an open data test param file.
**Issue**
dockstore/dockstore#5136
**Security**

Add the Open Data facet

---

cypress/e2e/group3/githubAppTools.ts
src/app/workflow/workflow.component.html

This PR adds a more descriptive message for a GitHub App entry without versions. A GH App entry can get into a state where it has no versions if all the branches/tags that contain a .dockstore.yml that references the workflow are deleted (see more details in the ticket).
On QA:
- Create a GitHub App workflow by creating a .dockstore.yml in a non-main/master branch. For the purposes of these instructions, I'm going to call this branch the ghost branch. The workflow in the .dockstore.yml should only exist in your ghost branch (ex: if you had a workflow called foo in the .dockstore.yml in the main/master branch, your workflow in the ghost branch should be named something else, like foo-wdl) 
- Wait for the new workflow from your ghost branch to show up …

Add message for GH App entry with no versions

---

README.md

Reference the latest and greatest software versions used by the UI.
None needed beyond the PR review itself.
**Issue**
dockstore/dockstore#5165
**Security**

Small tweaks to README.md.

---

src/app/home-page/new-dashboard/new-dashboard.component.html
src/app/home-page/widget/entry-box/entry-box.component.html
src/app/home-page/widget/entry-box/entry-box.component.scss
src/app/home-page/widget/entry-box/entry-box.component.ts
src/app/home-page/widget/organization-box/organization-box.component.html
src/app/home-page/widget/organization-box/organization-box.component.scss
src/app/home-page/widget/organization-box/organization-box.component.ts
src/app/home-page/widget/starred-box/starred-box.component.scss
src/app/home-page/widget/starred-box/starred-box.component.ts
src/app/shared/styles/dashboard-boxes.scss

Changes to the new dashboard and new components on the dashboard to allow for better page resizing.
**Before:**
https://user-images.githubusercontent.com/97123241/216400435-de508b97-76fa-48c6-b942-5a198d50af11.mp4
**After:**
https://user-images.githubusercontent.com/97123241/216400332-1d157fa4-ba5d-4c1d-af3d-67798cb78f67.mp4
Resizing changes to the `starred-box.component` were completed in my last pr, this pr adds those same structural changes to the `entry-box.component` and `organization-box.component`.  Same as before, a `div` which encapsulates all of the `mat-card` contents was added to help with the alignment of content inside when resizing and resolve the overflow issues.
As a result `entry-box.component.html` and …

New Dashboard Resizing

---

src/app/workflow/workflow.component.html

Noticed that the workflow sidebar get squished when resizing, but the tools sidebar does not... 
**Tools (left) & Workflows (right):**
The breakpoints only differed in these two lines:
https://github.com/dockstore/dockstore-ui2/blob/36197d44f406b030c938c984451a1930cae2690c/src/app/container/container.component.html#L194
https://github.com/dockstore/dockstore-ui2/blob/36197d44f406b030c938c984451a1930cae2690c/src/app/container/container.component.html#L301
Updated the `workflow.component` to match and the squishing is avoided:
**Before (left) & After (right):**
**Issue**
**Security**
Please make sure that you've checked the following before submitting …

workflow sidebar resize

---

src/app/loginComponents/onboarding/downloadcliclient/downloadcliclient.component.ts
src/app/loginComponents/onboarding/onboarding.component.html

Elaborate on who needs the CLI, thinking this is a compromise while not going as far as explicitly labeling the CLI as optional 
Should just go through onboarding tutorial and look for formatting/display issues
Note, if you've already registered you can get back to the onboarding tutorial via https://qa.dockstore.org/onboarding
**Issue**
https://github.com/dockstore/dockstore/issues/4797
https://github.com/dockstore/dockstore/issues/4858
**Security**
None

Elaborate on CLI in onboarding tutorial

---

src/app/home-page/widget/news-box/news-box.component.html
src/styles.scss

Follow up to this [PR](https://github.com/dockstore/extra-content/pull/47),  adds styles for `News & Updates` using plain css.
**Currently in QA:**
**Final changes with plain html and css styles:**
News & Updates should look consistent with above ^ after this [PR](https://github.com/dockstore/extra-content/pull/47) and current are merged.
**Issue**
SEAB-5339
**Security**

News & Updates Global Styles - SEAB-5339

---

cypress/e2e/group2/usernameChangeRequired.ts
cypress/e2e/group3/githubAppTools.ts
src/app/container/container.component.ts
src/app/shared/entry.ts
src/app/source-file-tabs/source-file-tabs.component.html
src/app/source-file-tabs/source-file-tabs.component.spec.ts
src/app/source-file-tabs/source-file-tabs.component.ts
src/app/source-file-tabs/source-file-tabs.service.ts
src/app/workflow/workflow.component.html
src/app/workflow/workflow.component.ts

The crux of fix for the issue described in the bug is in source-file-tabs.service.ts.
In working on it, I noticed compilation errors in the IDE, which led to a chain of changes.
The starting problem was in workflow.component.html, where `selectedVersion` was defined in entry.ts as `WorkflowVersion | Tag`, was being passed to a component that was expecting a `WorkflowVersion`.
I moved selectedVersion out of entry.ts and into the workflow and container subclasses.
1. Go any published app tool -- find one via Search: (Search | Tools | Select `Source Control - GitHub` facet).
2. Go to the Files tab, and then the Descriptor Files subtab.
3. Click the Download icon at the top right of the file.
4. The file should download
**Issue** …

Download file for app tool fix

---

src/app/workflow/info-tab/info-tab.component.html

Fixes link to source code which had extra slash (I don't actually know the original intent of the `isPublic` bit, let me know if you recognize it. Its quite old)
Check the link to the source code in my workflows, in public page
**Issue**
https://github.com/dockstore/dockstore/issues/5444
https://github.com/dockstore/dockstore/issues/5414
**Security**

fix link to source code

---

src/app/user-page/user-page.component.ts

This PR removes the `checkUserExists` function in the user page to allow unauthorized users to view user pages. 
Before fix: 
After fix:
Log out and go to https://qa.dockstore.org/users/hyunnaye and confirm that the credentials error is not shown.
**Issue**
https://github.com/dockstore/dockstore/issues/5480
**Security**

DOCK-2383: removed checkUserExists function to allow unauthorized users to view user pages

---

src/app/workflow/launch-third-party/launch-third-party.component.html

Cherry pick of https://github.com/dockstore/dockstore-ui2/pull/1773 to release/1.14.
None, will be tested on develop branch and during release user testing.
**Issue**
https://ucsc-cgl.atlassian.net/browse/SEAB-5511
**Security**

SEAB-5511: Make all "launch with" button tooltips appear to the left 

---

src/app/navbar/navbar.component.ts

Only ask for curator orgs when curator or admin
There should be no 403 or snakebar warning message as indicated in the linked ticket when logged in as a regular user. 
**Issue**
https://github.com/dockstore/dockstore/issues/5520
**Security**

permissions fix

---

.circleci/config.yml
package.json
src/app/configuration.service.ts
src/app/shared/dockstore.model.ts
src/app/test/mocked-objects.ts
src/app/workflow/launch-third-party/launch-third-party.component.html
src/app/workflow/launch-third-party/launch-third-party.component.ts

This PR:
* modifies the Colab notebook "launch with" process by adding a button, improving the URL synthesis, and using the root URL that is supplied by the webservice. 
* adds similar MyBinder notebook "launch with" functionality.
This PR includes ~~Denis'~~ Kathy's jdk->jre circleci fix.
Looks like we test the workflow "launch with" functionality very lightly, and primarily in the smoke tests.  Currently, there's not a smoke test for notebooks.  We should make one.  I suggest we write a ticket to do so, and implement the notebook "launch with" tests then-and-there.
Go to a public notebook page, use the "launch with" buttons to launch on Colab and MyBinder, and confirm it worked.  Note that as of the last few weeks, mybinder.org appears to be …

SEAB-5121: Improve Colab and add MyBinder notebook launch

---

cypress/e2e/group1/dashboard.ts
package.json
src/app/home-page/widget/entry-box/entry-box.component.html
src/app/home-page/widget/entry-box/entry-box.component.ts
src/materialColorScheme.scss
src/styles.scss

This PR allows notebooks to be displayed on the user dashboard.
Before fix (has 1 notebook published):
After fix:
Upload a notebook on qa and confirm it shows up on dashboard (with `notebooks` feature flag). 
The new integration test should pass.
**Issue**
https://ucsc-cgl.atlassian.net/browse/SEAB-5437
**Security**

SEAB-5437: show notebooks in dashboard

---

src/app/about/about.component.html

Wrapping up the setup development environment task by fixing a typo in the UI (didn't find a typo so fixed a missing period instead).
Check that the change is acceptable.
**Issue**
[SEAB-5479](https://ucsc-cgl.atlassian.net/browse/SEAB-5479)
**Security**
[SEAB-5479]: https://ucsc-cgl.atlassian.net/browse/SEAB-5479?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SEAB-5479: add missing period

---

.circleci/config.yml
sonar-project.properties

Setup CI-based analysis and coverage for ui2 project in SonarCloud (currently coverage is only tracked in Codecov).
Check that coverage info is available in the SonarCloud project. Before analysis and coverage can be sent, need to go to project adminstration to turn off automatic analysis since CI-based analysis cannot be run concurrently. Note: Also need to add the SONAR_TOKEN environment variable.
**Issue**
[SEAB-3959](https://ucsc-cgl.atlassian.net/browse/SEAB-3959)
**Security**
[SEAB-3959]: https://ucsc-cgl.atlassian.net/browse/SEAB-3959?atlOrigin=eyJpIj …

SEAB-3959: Set up coverage in SonarCloud for dockstore-ui2 project

---

package.json

Was causing search to fail because generated client wasn't adding application/json content-type; a `@Consumes(application/json) had been added in the hotfix.
Go to search page; you should see no errors.
**Issue**
dockstore/dockstore#5606
**Security**

Update to latest artifacts

---

src/app/configuration.service.ts
src/app/footer/footer.component.ts
src/app/footer/footer.service.spec.ts
src/app/footer/footer.service.ts
src/app/shared/dockstore.model.ts

Child of https://github.com/dockstore/dockstore-deploy/pull/684
Check qa footer after deployment
**Issue**
https://ucsc-cgl.atlassian.net/browse/SEAB-5666
**Security**

cleanup compose setup version

---

cypress/e2e/group2/myworkflows.ts
cypress/e2e/group3/githubAppTools.ts
package.json
src/app/myworkflows/sidebar-accordion/github-apps-logs/github-apps-logs.component.html
src/app/myworkflows/sidebar-accordion/github-apps-logs/github-apps-logs.component.ts
src/app/myworkflows/sidebar-accordion/github-apps-logs/github-apps-logs.module.ts
src/app/myworkflows/sidebar-accordion/sidebar-accordion.component.ts
src/app/shared/constants.ts
src/app/user-page/user-page.component.ts

Added columns for `entryName` and `deliveryId` in GitHub App Logs.
In "My Dockstore", click "Apps Logs" and check that the entry name and delivery id appear in the table.
**Issue**
[DOCK-2407](https://ucsc-cgl.atlassian.net/browse/DOCK-2407)
**Security**
[DOCK-2407]: https://ucsc-cgl.atlassian.net/browse/DOCK-2407?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DOCK-2407: Display entryName and deliveryId in GitHub App Logs

---

src/app/footer/footer.component.html
src/app/home-page/home-logged-out/home.component.html

A couple of links to the faq entry on citing dockstore.
Pairs with https://github.com/dockstore/dockstore-documentation/pull/252
Follow the various links in the UI and in the FAQ
**Issue**
https://github.com/dockstore/dockstore/issues/5598
**Security**

add a couple links to the footer and homepage

---

cypress/e2e/immutableDatabaseTests/dropdown.ts
src/app/loginComponents/accounts/account-sidebar/account-sidebar.component.html
src/app/loginComponents/accounts/account-sidebar/account-sidebar.component.scss
src/app/loginComponents/accounts/account-sidebar/account-sidebar.module.ts
src/app/navbar/navbar.component.html
src/app/navbar/navbar.component.scss
src/app/organizations/events.module.ts
src/app/organizations/events/events.component.html

This PR adds a way to navigate to the current user profile from the navbar drop-down menu and account page. Links to user profiles were also added to usernames for organization events.
1. Go to the drop-down at the top of the page and click "Profile", it should take you to your user profile page
2. Go to your account page and click on the "View Dockstore Profile" button, it should take you to the user profile page
3. Go to "Organizations" > View > Updates tab > Click on a username for an event and it should take you to the corresponding user profile
**Issue**
[DOCK-2439](https://ucsc-cgl.atlassian.net/browse/DOCK-2439)
**Security**
Please make sure …

DOCK-2439: Add links to user profile

---

src/app/workflow/executions/executions-tab.component.html

This PR displays the cost metric with 2 decimal places.
Before:
Note how 3 USD has no decimal places
After:
Note how 6.00 USD has 2 decimal places
Verify that the cost metrics in this workflow [insert workflow]  contain 2 decimal places.
**Issue**
dockstore/dockstore#5600
[DOCK-2433](https://ucsc-cgl.atlassian.net/browse/DOCK-2433)
**Security**
[DOCK-2433]: https://ucsc-cgl.atlassian.net/browse/DOCK-2433?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Display cost metric with 2 decimal places

---

src/app/home-page/home-logged-out/home.component.html

On the Dockstore home page, we link to the HelloWorld workflow.  In the link, we tried to include the query parameter `tab` with value `info`, but alas, right now, the `?` and `=` are encoded, so they end up being interpeted as part of the branch name.  So, right now, when the link is clicked on, Dockstore tries to find a non-existent version.  To temporarily triage the bug, we set the default version on the workflow to the desired version, which Dockstore then displays, so the link appears to work.  So, I think we can merge this fix to develop.
The problem happens because we include the parameters in `routerLink`, which causes them to be included in the main part of the link and encoded.
This PR changes the code to use the `queryParams` property to correctly specify the …

SEAB-5975: Fix broken "HelloWorld" workflow links

---

cypress/e2e/immutableDatabaseTests/searchTable.ts
cypress/fixtures/noHitsSearchTableResponse.json
src/app/search/query-builder.service.ts
src/app/search/search.component.html
src/app/search/search.component.ts
src/app/search/state/search.service.ts

UI will look like this:
Also replaced several `any` with types, which helped me understand the code as I was navigating it.
If this seems like a bit of a dupe of a previous review, it is -- I closed #1853 due to weird CircleCI results discussed in [Slack](https://ucsc-gi.slack.com/archives/C05EZH3RVNY/p1698784510700059).
Follow "short version" instructions in dockstore/dockstore#5648. You should see the screenshot from the description, above.
Also try searching for a non-existent term from the home page, and make sure there are not duplicate boxes and that a suggestion is displayed -- discovered by Steve in other PR review.
**Issue**
dockstore/dockstore#5648
**Security**
If there are any concerns that require extra attention from the security team, …

Tell user to reset if there are no search results via facets

---

.github/workflows/accessibility_test.yml

Reverts dockstore/dockstore-ui2#1900

Revert "Bump actions/upload-artifact from 3 to 4"

---

cypress/e2e/group1/dashboard.ts
cypress/support/commands.ts
src/app/app.routing.ts
src/app/container/register-tool/register-tool.component.ts
src/app/github-landing-page/github-landing-page.component.html
src/app/github-landing-page/github-landing-page.component.scss
src/app/github-landing-page/github-landing-page.component.ts
src/app/home-page/home-page.module.ts
src/app/shared/modules/register-github-app.module.ts
src/app/shared/register-github-app/register-github-app.component.html
src/app/shared/register-github-app/register-github-app.component.spec.ts
src/app/shared/register-github-app/register-github-app.component.ts
src/app/shared/session/session.query.ts
src/app/workflow/register-workflow-modal/register-github-app-modal/register-github-app-modal.component.ts
src/app/workflow/register-workflow-modal/register-workflow-modal.component.ts

This PR adds a static GitHub landing page for the user to land on after registering their workflows.
First, the Manage Dockstore installations on GitHub button goes to the github app configuration page in a new tab, later redirecting to the landing page. The original tab remains the same with the dialog open.
Try registering a new workflow and verify that the github apps installation page goes to a new tab then redirected to the landing page after saving configurations. Also verify that the original tab remains the same with the dialog open.
**Issue**
https://ucsc-cgl.atlassian.net/browse/SEAB-5950
https://ucsc-cgl.atlassian.net/browse/SEAB-5998
**Security**
If there are any concerns that require extra attention from the security team, highlight …

SEAB-5998: Create static github apps landing page

---

src/app/entry/delete/dialog/delete-entry-dialog.component.html
src/app/entry/delete/dialog/delete-entry-dialog.component.ts
src/app/search/advancedsearch/advancedsearch.component.html
src/app/workflow/snapshot-exporter-modal/snaphot-exporter-modal.component.html
src/app/workflow/snapshot-exporter-modal/snaphot-exporter-modal.component.spec.ts
src/app/workflow/snapshot-exporter-modal/snaphot-exporter-modal.component.ts
src/app/workflow/version-modal/version-modal.component.html

This PR adjusts the text of various UI components to mention and/or make sense for notebooks.  Specifically, it addresses the following issues:
* Notebook version “Info” dialog displays “Test Parameter File(s)”, should be “Test Files”.
* Advanced Search dialog box should include “notebooks” alongside “tools and workflows”.
* “Snapshot version” dialog refers to the notebook as a “workflow”.
* “Request DOI” dialog refers to the notebook as a “workflow”.
* “Export to ORCID” dialog refers to the notebook as a “workflow”.
* “Delete notebook” dialog refers to a “checked or checker workflow”, which doesn’t make sense and should be removed for notebooks.
For more details, see this doc: https://docs.google.com/document/d/1s3OU1kDcVwjPIOdgsmmaJTKGD2ZrojgZS5VYUt8njf8
**Review …

SEAB-6187: Adjust messaging for notebooks

---

src/app/search/map-friendly-values.pipe.ts

When displaying GitHub App logs in the dashboard, entries with the type `PUBLISH` have the field written in all caps, while the other types (`Push`, `Delete`, `Install`) are written in title case.
_(Screenshot from Cypress test: App logs with different types, before changes.)_
After updating the `MapFriendlyValuesPipe` for the 'type' key, GitHub App entries of type `PUBLISH` should be displayed in title case, similarly to the remaining three types.
_(Screenshot from Cypress test: App logs with different types, after changes.)_
**Issue**
[DOCK-2488](https://ucsc-cgl.atlassian.net/browse/DOCK-2488?atlOrigin=eyJpIjoiZDNiYWI1NWYzYzJhNDk2ZTljZGU1YzMyNGY0NjQwYmIiLCJwIjoiaiJ9)
**Security**
If there are any concerns that require extra attention from the …

DOCK-2488: Update Apps Logs type to title case

---

src/app/workflow/workflow.component.ts

Before, when viewing the metrics tab, if the user refreshes the page, the tab would reset back to the Info tab. 
Thus this PR fixes that issue such that when a user reloads the page, the page will be reloaded back onto the Metrics tab.
1. Go to  https://staging.dockstore.org/workflows/github.com/gatk-workflows/seq-format-conversion/BAM-to-Unmapped-BAM:3.0.0?tab=metrics 
2. Refresh the page and verify that the page loads back onto the Metrics tab.
**Issue**
https://ucsc-cgl.atlassian.net/browse/SEAB-6202
**Security**

SEAB-6292: Fix refresh issue when reloading the Metrics tab

---

cypress/e2e/group3/metrics.ts
cypress/fixtures/sampleMetrics.json
package.json
src/app/shared/entry/execution-status.pipe.spec.ts
src/app/shared/entry/execution-status.pipe.ts
src/app/shared/pipe/pipe.module.ts
src/app/workflow/executions/executions-tab.component.html
src/app/workflow/executions/executions-tab.component.ts

Corresponding PRs:
- https://github.com/dockstore/dockstore/pull/5800
- https://github.com/dockstore/dockstore-support/pull/482
This PR adds a drop down that allows users to view execution metrics by the status of the executions it was aggregated from.
When there is only one real status (ex: ALL and SUCCESSFUL), the single status is displayed by default and ALL is hidden. Since I did that for the execution status drop down, I also did it for the platform drop down which tackles this [SEAB-6205](https://ucsc-cgl.atlassian.net/browse/SEAB-6205).
**Videos**
NEWEST VIDEO:
- Shows that successful is the default status
- Shows the Not Available row if there's no metrics for a status (modeled after the Info tab's Author table when there are no authors) …

Add drop down to display execution metrics by status

---

.circleci/config.yml

Fix ChromeDriver install so develop builds will pass. Copied from #1936
CircleCI builds should pass
**Issue**
SEAB-6272
**Security**

ChromeDriver Fix

---

src/app/shared/launch.service.ts
src/app/workflow/launch/launch.component.html
src/app/workflow/launch/launch.component.ts

* Single quotes needed for wget on zsh
* Hard-coded parameter file name to match WDL
With provided parameter file
Without provided parameter file
Same as previous PR https://github.com/dockstore/dockstore-ui2/pull/1940
**Issue**
More https://ucsc-cgl.atlassian.net/browse/SEAB-6273
**Security**

make zsh compatible and hardcode parameter file name

---

cypress/e2e/group2/myworkflows.ts
package.json
src/app/workflow/workflow.component.html
src/app/workflow/workflow.component.ts

This PR adds a "yellow box" warning to the private Entry page that is displayed when the GitHub App appears to be uninstalled:
The button has the same text as the button that's displayed in the registration interface.
Register an entry on qa via our GitHub App, and view the private page.  Confirm that the warning is not displayed.  Uninstall our GitHub App on the repository containing the entry.  Wait five minutes.  Reload the private page, and confirm that the warning is displayed.  Click on the button and reinstall the App on the repo.  Wait five minutes.  Confirm that the warning is displayed.
**Issue**
https://ucsc-cgl.atlassian.net/browse/DOCK-2312
https://github.com/dockstore/dockstore/issues/5331
**Security**
No security concerns.
Please make …

DOCK-2312: Add warning to Entry page that GitHub App might be uninstalled

---

cypress/e2e/immutableDatabaseTests/jsonld.ts
src/app/home-page/home-logged-out/home.component.html
src/app/home-page/home-page.service.ts
src/app/login/login.component.html
src/index.html

Remove references since collaboratory has shut down and we've been independent for a long time. 
GA4GH reference is further down the page. 
passing builds, could login or take a look at home page
**Issue**
https://ucsc-cgl.atlassian.net/browse/SEAB-6397
**Security**
None

remove old references

---

src/app/workflow/info-tab/info-tab.component.css
src/app/workflow/info-tab/info-tab.component.html

This PR changes the labels from just "DOI" to "Concept DOI" and "Version DOI"
Before fix:
After fix (Note the DOI labels have changed):
Tooltip:
Go to https://qa.dockstore.org/workflows/github.com/kathy-t/ghapps-single-workflow:master?tab=info and verify that the labels have changed
**Issue**
https://ucsc-cgl.atlassian.net/browse/DOCK-2527
**Security**

DOCK-2527: Improve DOI labels

---

src/app/workflow/info-tab/info-tab.component.css
src/app/workflow/info-tab/info-tab.component.html

Not sure why this commit didn't get pushed.. This PR adds the changes from Charles' comment in this [PR ](https://github.com/dockstore/dockstore-ui2/pull/1976)
Same as https://github.com/dockstore/dockstore-ui2/pull/1976
**Issue**
https://ucsc-cgl.atlassian.net/browse/DOCK-2527
**Security**

DOCK-2527: remove duplicate code

---

src/app/mytools/my-tool/my-tool.component.html
src/app/mytools/my-tool/my-tool.component.ts
src/app/myworkflows/my-workflow/my-workflow.component.html
src/app/myworkflows/sidebar-accordion/github-apps-logs/github-apps-logs.component.html
src/app/myworkflows/sidebar-accordion/github-apps-logs/github-apps-logs.component.ts

This PR adds the "Configure your authorized organizations" message to the My Tools page so it matches the My Workflows page.
Verify that the My Tools page has the same "Configure your authorized organizations" as the My Workflows page in the left side bar.
Click on the "Configure" link and verify that it takes you to configure the app for the correct environment. For example, if you're in QA, then it should display the GitHub OAuth app for QA.
**Issue**
dockstore/dockstore#4852
https://ucsc-cgl.atlassian.net/browse/DOCK-2136
**Security**

Add "Configure your authorized organizations" message to My Tools page

---

.circleci/config.yml
cypress/e2e/group2/myworkflows.ts
cypress/e2e/group3/mytools.ts
src/app/loginComponents/onboarding/downloadcliclient/downloadcliclient.component.ts
src/app/loginComponents/onboarding/onboarding.component.html

A cherry pick of #1964, plus another commit. Apparently I missed pushing my last commit to #1964, so even though the screenshot reflected what was on my local branch, it was ahead of what was on GitHub. I was able to get that last commit via reflog.
Go to Dashboard | Quickstart | MacOS, and verify the instructions mention Java 17, not 11. Note that the instructions have been reworked a bit, with the latest commit, and are less prescriptive on exactly how to install Java on a Mac, since there are many ways.
**Issue**
DOCK-2538
dockstore/dockstore#5920
**Security**
Please make sure that you've checked the following before submitting your pull request. …

Fix Java install instructions for Mac

---

src/app/organizations/collection/collection.component.html
src/app/organizations/collection/collection.component.ts

This PR adds topic sentences to each entry in the collection page
Before:
After:
AI Bubble
Go to https://qa.dockstore.org/organizations/BroadInstitute and verify that there are topic sentences for each entry.
**Issue**
https://ucsc-cgl.atlassian.net/browse/DOCK-2557
**Security**

DOCK-2557: Adds topic sentences in collection page

---

cypress/e2e/smokeTests/sharedTests/auth-tests.ts

This PR attempts to adjust the smoke tests so that they do not create lots of "orphaned" Zenodo DOIs, by tweaking the tests so that a test workflow is not restubbed in the prod tests, preventing new tag-backed versions from being created and each triggering the generation of a new DOI.  The assumption here is that we don't want to create lots of orphaned production Zenodo DOIs.  If we decide that some degree of orphaning is acceptable, we might partially or completely reverse this change.
This PR reflects a pragmatic but imperfect-balancing of the various tradeoffs, and is probably good enough for now.
Originally, I had planned to tweak the smoke tests so that in prod, the "refresh from stub" path used a tagless fork of the currently-used repo.  However, that approach …

SEAB-6508: Adjust smoke tests for new auto-DOI generation feature

---

README.md
src/app/about/about.component.ts
src/app/footer/footer.component.ts
src/app/shared/code-editor/code-editor.component.ts

Snakemake files appear to be highlighted as python on GitHub, doing the same
Supports https://github.com/dockstore/snakemake-language-interface/pull/2
After prototype is merged, could load a Snakemake workflow and view its files
**Issue**
https://ucsc-cgl.atlassian.net/browse/SEAB-3981
https://ucsc-cgl.atlassian.net/browse/SEAB-6726
**Security**

Add syntax highlighting for Snakemake

---

src/app/notebook/prism.ts

This PR adds syntax highlighting to the notebook "Preview" for R Jupyter notebooks. 
View the preview of an R notebook, and confirm that the R code is rendered in multiple different colors.
**Issue**
https://ucsc-cgl.atlassian.net/browse/SEAB-6958
**Security**

SEAB-6958: Add syntax highlighting for R notebooks

---

src/assets/text/sample-workflow-dockstore.yml

This PR adds `SMK` to the list of possible values in the example workflow `.dockstore.yml` on the registration landing page.
Confirm that `SMK` now appears, as expected.
**Issue**
https://ucsc-cgl.atlassian.net/browse/SEAB-7016
**Security**

SEAB-7016: Add SMK to example .dockstore.yml

---

src/app/shared/launch.service.ts
src/app/shared/state/workflow.query.ts
src/app/workflow/launch/launch.component.html
src/app/workflow/launch/launch.component.ts
src/app/workflow/launch/workflow-launch.service.ts

This PR adds some rudimentary instructions to the "Launch" tab for snakemake workflows, and makes some cosmetic changes to the order of some properties/methods in the interest of improving clarity.
Per a discussion with Denis, the instructions recommend a "github clone" file download and `snakemake` invocation.
The good thing about a "github clone" download is that it:
* downloads all of the necessary files (including those which our new plugin might have [inadvertently] not pulled into Dockstore).
* works for unpublished workflows.
The bad thing about the "github clone" approach is that it:
* doesn't support non-GitHub-based workflows (hosted, GitLab, etc).
* might download a bunch of extra/unnecessary junk.
If the workflow isn't GitHub-based, no instructions appear.
I'm …

SEAB-7081: Add launch information for snakemake

---

src/app/source-file-tabs/source-file-tabs.component.html

This PR center aligns the home icon on the Files tab.
Before:
After:
On staging:
- Navigate to https://staging.dockstore.org/workflows/github.com/broadinstitute/warp/Optimus:Optimus_v5.4.3?tab=files&file=%2Ftasks%2Fskylab%2FCheckInputs.wdl
- Verify that the home button is centred aligned
**Issue**
https://ucsc-cgl.atlassian.net/browse/SEAB-7148
**Security**

Align home icon in Files tab

---

README.md

Noticed that these instructions on how to build against a specific branch are slightly out of date so I updated them.
Could try out the instructions
**Issue**
n/a
**Security**

Update docs on how to build against a specific branch
