- README.md
- package.json
Issue ga4gh/dockstore#715 has been updated.
So I tested this with different dockers, the global cil version is now same as the local cil.
Note that "angular/cli" in the package.json should always matches the version of the sudo npm install command:
sudo npm install -g @angular/cli@**1.0.3**
ie: make sure its 1.0.3 for both package.json and the install command.
> Updated README and package.json for setting up angular-cli

- src/app/container/container.component.html
- src/app/container/versions/versions.component.html
Making the column length flexible depending on its contents.
Giving the container info a bit more space to work with.
> More space for container info

- package.json
- src/app/container/container.component.ts
- src/app/container/register-tool/register-tool.service.ts
- src/app/container/view/view.component.html
- src/app/container/view/view.component.ts
- src/app/container/view/view.service.ts
- src/app/containers/list/list.component.ts
- src/app/mytools/mytools.component.html
- src/app/mytools/mytools.component.ts
- src/app/shared/container.service.ts
- src/app/shared/modules/container.module.ts
- src/app/shared/tool.ts
- src/app/workflow/dag/dag.component.html
- src/app/workflow/dag/dag.component.ts
- src/app/workflow/dag/dag.service.ts
- src/styles.scss
Contains a bunch of bug fixes and minor feature updates for tag edtior, DAG, and add tool
- Upon registering tool, add the registered response tool to the list of displayed tools without an additional API call
- Select the tool that just got registered.
- Style fix for DAG
- Bug fix for tag edtior
- Adding DAG refresh on ngAfterViewChecked
- Changes to the routing to grab published tool only when the event.url contains "containers"
> Add and select tool to view

- src/app/search/query-builder.service.ts
Select almost any filter, notice how the verified filters are incorrect.   This fixes that by actually returning the query body string.  The previous query used to be null.
> Actually return the query

- src/app/container/info-tab/info-tab.component.html
Fix info-tab names.  Currently relies on the tool observable.
> Use friendly provider names

- src/app/loginComponents/onboarding/downloadcliclient/downloadcliclient.component.ts
- src/app/loginComponents/onboarding/quickstart.component.html
Fix for the dockstore version and api version not showing up on slow networks.  Simply initializing within the subscription instead of outside it.   Formatting is responsible for 6/7 lines added/deleted.
Also might as well fix the ga4gh/dockstore#1010
> Fix for subscription

- src/app/search/search.component.html
- src/app/search/search.component.spec.ts
- src/app/search/search.component.ts
- src/app/search/search.module.ts
- src/app/search/search.service.ts
- src/app/shared/dockstore.model.ts
Uses URL shortener for permalinks.
Note dockstore.model.ts has new field GOOGLE_SHORTENER_KEY, we will need to generate an API key with a new dockstore email address
[Issue #924](https://github.com/ga4gh/dockstore/issues/924)
> Use google url shortener on permalinks if possible

- src/app/shared/validationMessages.model.ts
* relaxes validation for tool version as mentioned in ga4gh/dockstore#776 (allows for consecutive inner - and _ )
> relaxed tool version validation

- src/app/shared/auth.model.ts
This one line/error took entirely too long to discover. 
The issue was that logging in would create a token of completely different scope from the linking account button, causing newly logged in users to be unable to refresh workflows out of the box.
> Fix login to create tokens of the same scope as account linking

- scripts/run-travis-script.sh
Sometimes `ng test` results in `Karma - Disconnected, because no message in 10000 ms`  .  Run chrome headless appears to help mitigate the issue a bit.  Another option is to increase timeout.
> Run chrome headless

- src/app/container/versions/versions.component.html
- src/app/workflow/versions/versions.component.html
Add info icon to right of Version / Git Reference column header
> Add link to default version help (#1028)

- src/app/container/launch/launch.component.ts
- src/app/container/launch/tool-launch.service.spec.ts
- src/app/container/launch/tool-launch.service.ts
- src/app/shared/launch.service.ts
- src/app/workflow/launch/launch.component.ts
- src/app/workflow/launch/workflow-launch.service.spec.ts
- src/app/workflow/launch/workflow-launch.service.ts
For issue ga4gh/dockstore#844
Substitute the workflow cwl-runner launch string's descriptor with the relative paths endpoint instead.  Tool is also changed.
> Used main descriptor as relative path

- src/app/container/versions/versions.component.ts
- src/app/test/service-stubs.ts
- src/app/workflow/versions/versions.component.spec.ts
- src/app/workflow/versions/versions.component.ts
For ga4gh/dockstore#1100
Hooks refresh into the default version change.  Instead of updating the tool/workflow based on the tool/workflow update response, update the tool/workflow based on the refresh response.
> Refresh upon default version change

- src/app/shared/dockstore.model.ts
For issue ga4gh/dockstore#1126 Remove `user` from GitHub scope.  On a fresh database, GitHub account info gets automatically synced upon first visit.  New workflows/tools are automatically added via refresh all.
> Remove user from github scope

- src/app/search/search.service.ts
For ga4gh/dockstore#1134  
Clicking on verified facet alters the filters by adding a number as the categoryValue (0 for public, 1 for private).
However, using the search path with parameters alters the filters by adding a string as the categoryValue ("0" for public, "1" for private).   This difference causes problems.  Now changing it all to strings (apparently elasticsearch doesn't care).  Also, not sure how a function with typed input parameters do not throw an error when it gets a different type.
> Use strings only

- src/app/workflows/list/list.component.html
Now workflows with workflow names are shown in list to be the same as tools.
Ex. OxoG-Dockstore-Tools/pcawg-oxog-full-workflow
https://github.com/ga4gh/dockstore/issues/1143
> changed workflow names from showing in brackets to the same as tools

- src/app/shared/dockstore.model.ts
- src/app/workflow/dag/cwl-viewer/cwl-viewer.component.ts
- src/app/workflow/dag/cwl-viewer/cwl-viewer.html
- src/app/workflow/dag/cwl-viewer/cwl-viewer.scss
- src/app/workflow/dag/cwl-viewer/cwl-viewer.service.spec.ts
- src/app/workflow/dag/cwl-viewer/cwl-viewer.service.ts
- src/app/workflow/dag/dag.component.html
- src/app/workflow/dag/dag.component.spec.ts
- src/app/workflow/dag/dag.component.ts
- src/app/workflow/dag/dag.module.ts
- src/app/workflow/workflow.component.html
For CWL workflows, display an SVG created by view.commonwl.org. This
is in addition to the current DAG visualization, and the change
includes radiobuttons that let the user select which visualization
to see.
This feature is off by default, as view.commonwl.org does not
support CORS. Two issues were filed and fixed in that repo, but they
have not yet been deployed. This was tested by running an instance of
the viewer locally.
To turn on the feature, initialize enableCwlViewer to true in
src/app/workflow/dag/dag.component.ts. Ideally a more fancy feature
flag feature should have been implemented that doesn't require
changing the source code to toggle the feature, but it didn't seem worth
the effort unless this is a need we anticipate coming up more often.
Todo:
The zooming in/out is pretty …
> Display view.commonwl.org visualization #1058

- .angular-cli.json
It was only failing in Angular prod mode.
Using source maps, I saw it was failing in cytoscape.min.js, so then
I tried the non-minified version to see exactly what the problem was,
and the problem went away.
The problem seems to be unrelated to the CWL Viewer DAG work, as I could
still reproduce the problem in prod mode if I rolled back the CWL
Viewer commits locally.
With this change, the generated bundles only seem to contain minified
code; it looks like the difference is that Angular preforms the
minification at build time.
ga4gh/dockstore#1199
> Fix broken DAG #1199

- src/app/listentry/listentry.component.html
- src/app/myworkflows/myworkflows.component.html
- src/app/starredentries/starredentries.component.html
- src/app/workflows/list/list.component.html
Changes workflow names in paths to be listed as path/workflowname instead of path (workflowname). This makes it consistent with tools.
Deals with
https://github.com/ga4gh/dockstore/issues/1143
> changed how we do workflow names

- package-lock.json
With our current @angular/cli version 1.4.10, newly generated projects actually use copy-webpack-plugin 4.5.0 instead of our current 4.3.1.  By upgrading it to 4.5.0, it upgrades "cacache" which upgrades "ssri".
> Upgrade ssri

- src/app/container/info-tab/info-tab.component.html
- src/app/container/info-tab/info-tab.component.ts
For issue ga4gh/dockstore#1187
Require one of the two descriptor paths in the info tab of mytools.
Also fixed tooltips and imports
> Require at least one of the two descriptors, change placeholder

- src/app/shared/dockstore.model.ts
- src/app/workflow/dag/dag.component.ts
Add a "feature flags" property in dockstore.model.ts, so that
features can be turned on/off without doing new Git commits.
EnableCwlViewer is the only flag in there so far.
Also added a comment to dockstore.model.ts warning to keep it in sync
with the template in the dockstore/compose_setup repo, as I was
previously unaware of the need.
Not sure if this approach is overkill, but it does seem like it would be nice to be able to turn on a feature with doing a new commit, and it looks like another feature, Launch with FireCloud, may only get turned on in staging, but not prod, at first.
> Add Feature Flags #268

- src/app/workflow/register-workflow-modal/register-workflow-modal.service.ts
There was a descriptorLanguage$ observable that was mapped from the bean to contain the array of strings.  This PR fixes what was left out (by not trying to map a 2nd time).
For ga4gh/dockstore#1253
> Fix for descriptorLanguage being pre-mapped already

- src/app/workflow/info-tab/info-tab.component.html
Simple fix for ga4gh/dockstore#1250 and also a bigger issue...  Going from FULL workflow to a STUB workflow showed the CLI commands of the previous FULL workflow.
> Fix stubbed workflows showing description and CLI commands

- src/app/search/search.component.ts
- src/app/shared/dockstore.model.ts
Removed code to use the google URL shortener. Now the function to shorten the URL will just return the regular URL. We will need to find something else to replace google in the future.
https://github.com/ga4gh/dockstore/issues/1263
Note: I still have to test this locally. Having trouble setting up elastic search. I'll notify people once this is ready for review.
> Comment out goo.gl url shortener code

- src/app/container/launch/tool-launch.service.spec.ts
- src/app/container/launch/tool-launch.service.ts
Fix for DescriptorLanguageBean returning all caps...which leads to Dockstore command being broken.
Didn't use an enum because DescriptorLanguageBean doesn't have enum.
ga4gh/dockstore#1304
> Fix for capital language descriptor bean

- src/app/containers/list/list.component.html
For issue ga4gh/dockstore#1278
Fix for the additional column added to list tools/workflows
> Fix for additional column added

- src/app/workflow/info-tab/info-tab.component.html
- src/app/workflow/info-tab/info-tab.component.ts
- src/app/workflow/info-tab/info-tab.service.ts
Simple change to not refresh when changing descriptorType of a stubbed workflow because that will automatically make it a full workflow and we can only change descriptorType of stubbed workflows.
> Don't refresh on stubbed descriptorType change

- src/app/workflow/info-tab/info-tab.service.ts
For ga4gh/dockstore#1326
Changing a stubbed workflow's descriptor type will automatically change the workflow path to a default one.  This kind of works because the workflow path validation prevents the user from changing the workflow path first.  CLI will also need to have a similar change.
> Change workflow path

- src/index.html
Adds a simple loading screen on initial page load. Much nicer than the current Loading... text.
Note that the CSS stuff has to be in the index.html as during the loading the screen the other CSS files don't seem to have been initialised.
On app load the contents of the app-root are cleared, so these classes shouldn't impact the actual site.
https://github.com/ga4gh/dockstore/issues/893
> added loading screen

- src/app/workflow/workflow.component.html
- src/app/workflow/workflow.component.ts
Fixing all the obvious issues reported by IDE in this workflow component html.
There's a bunch of similar issues across the board introduced during the Angularjs to Angular 2+ migration.  Couldn't find a tslint or codelyzer rules to enforce it so that it can be checked/fixed for everything in one PR but my IDE does in fact report it.  I'll keep an eye out in the future and fix it when in proximity.
- Removed the missingContent variable that's not defined anywhere
- Changed type from Workflow to ExtendedWorkflow due to the properties provider and provider url being available only in ExtendedWorkflow.
For ga4gh/dockstore#1394
> Fix noticeable warnings in workflow component html

- angular.json
- src/app/shared/code-editor/code-editor.component.ts
- src/app/shared/grammars/custom-grammars.js
Adds syntax highlighting for .config files and .nf files
.config uses groovy, .nf uses custom nextflow language that is then based upon the groovy language.
Partial implementation for ga4gh/dockstore#1396
Currently only uses https://github.com/nextflow-io/vscode-language-nextflow/blob/master/syntaxes/nextflow.tmLanguage.json and inherits groovy in order to highlight.  Ideally it should use https://github.com/nextflow-io/vscode-language-nextflow/blob/master/syntaxes/groovy.tmLanguage.json also.
> Add syntax highlighting for .config and .nf files

- src/app/container/paramfiles/paramfiles.component.html
- src/app/container/paramfiles/paramfiles.component.ts
- src/app/shared/file.service.ts
- src/app/workflow/paramfiles/paramfiles.component.html
- src/app/workflow/paramfiles/paramfiles.component.ts
This is to be reverted later when GA4GH endpoint is used to get the download file path.
Meant to revert https://github.com/dockstore/dockstore-ui2/pull/298
> Revert test parameter file download link change 

- src/app/shared/dockstore.model.ts
- src/app/workflow/dag/cwl-viewer/cwl-viewer.component.ts
- src/app/workflow/dag/cwl-viewer/cwl-viewer.html
- src/app/workflow/dag/cwl-viewer/cwl-viewer.service.spec.ts
- src/app/workflow/dag/cwl-viewer/cwl-viewer.service.ts
Fixes ga4gh/dockstore#1518.
* Look for a 200 response when polling the queue that might have a
cwltoolStatus of ERROR.
* Reduce polling frequency to every 500ms instead of 250ms.
* Stop polling when leaving the page.
* Display the error message that comes back from CWL Viewer instead
of a generic message.
> Improve CWL Viewer Error Handling

- src/app/shared/date.service.spec.ts
- src/app/shared/date.service.ts
- src/app/test/service-stubs.ts
The link used to redirect, now it just goes to the right place.
https://github.com/ga4gh/dockstore/issues/1493
> fix verified link

- cypress/integration/myworkflows.js
- src/app/myworkflows/my-workflow/my-workflow.component.html
- src/app/shared/validationMessages.model.ts
- src/app/workflow/register-workflow-modal/register-workflow-modal.component.html
- src/app/workflow/register-workflow-modal/register-workflow-modal.component.ts
- src/app/workflow/register-workflow-modal/register-workflow-modal.service.ts
For issue ga4gh/dockstore#1391
Reduced the getDescriptorType() calls by a bajillion
Have a different descriptor path validation patterns for the 3 descriptor types
TODO: 
- Set the initial validation pattern in a better way
- Have 3 different form errors for pattern
> Change validation pattern when descriptor type changes

- cypress/integration/checkerWorkflowFromWorkflows.js
- src/app/container/container.component.ts
- src/app/shared/entry.ts
- src/app/workflow/workflow.component.ts
For ga4gh/dockstore#1553
Changing the previous selection algorithm to be easier to read.
1. If the URL specifies a specific Tag or WorkflowVersion, choose to display that one.  Otherwise,
2. If the default version is specified, choose to display the default version.  Otherwise,
3. Choose the first version in the array (the last updated version?)
Also change the test because the checker is a stub since it can't be refreshed (no such Git repo).  Therefore, it cannot have a master branch to go to (not sure why it went there in the first place).
> Change version selection

- src/app/loginComponents/accounts/external/accounts.service.ts
- src/app/loginComponents/accounts/external/links.model.ts
- src/app/shared/dockstore.model.ts
* currently unable to determine membership or owned projects with a
token narrower than `api` which seems like a gitlab issue
https://github.com/timols/java-gitlab-api/blob/master/src/main/java/org/gitlab/api/GitlabAPI.java#L863
* tested with gitlab api 11.1.0-rc4-ee rev aedb3c9 (find at
https://gitlab.com/api/v4/version )
* note to self: follow with compose_setup PR when closing
> Prepare for scoped tokens on gitlab

- src/app/workflow/workflow.component.css
- src/app/workflow/workflow.component.html
- src/app/workflow/workflow.component.ts
ga4gh/dockstore#330
Disable instead of hide the button so user knows what is going on, with
a tooltip explaining why.
Only did it for FireCloud, as for DNAstack the user selects the version, so it doesn't seem like we should disable the button based on the content of the current version.
Screenshot showing warning for DNAstack and disabled button with tooltip for FireCloud:
FYI, this will be a pain to merge into develop, as the develop branch has this code in a new component.
> Disable Launch w/FireCloud if WDL has file imports

- src/app/shared/error.service.spec.ts
- src/app/shared/error.service.ts
Needed this to properly expose web service messages for WebApplicationException
otherwise we see "[HTTP 400] Bad Request: [object Object]" as opposed to "[HTTP 400] Bad Request: a message from the webservice"
> Expose web service messages for WebApplicationException

- src/app/workflow/workflow.component.ts
ga4gh/dockstore#1548
Fix case when disabling of launch with FireCloud/DNAstack buttons did
not happen when it should have, when you select the checker workflow
by clicking View Checker when on the parent.
Events seem to fire in a different order when selecting a checker
workflow that way. Add a call to checkWdlForImportsAndSetFirecloudUrl in
setupPublicEntry().
To avoid too many calls to fetch secondary files, store the last time
workflow and version that was queried, and make sure we don't query
twice for the same workflow/version. Less than perfect, but will
will redo in ga4gh/dockstore#1575.
> Fix Launch With Disabling for Checker Workflows

- src/app/workflow/view/view.component.ts
For issue ga4gh/dockstore#1564
Previously every view button (each version has one) does the GET request prior to the user clicking on the button.  It is now changed so that the GET request is only performed once the user clicks on the button.  This means that there's a slightly longer delay before the modal is shown.
> Reduce GET TestParameterFiles calls

- src/app/workflow/register-workflow-modal/register-workflow-modal.component.html
Enhancement for ga4gh/dockstore#1391
Previously, when enter is pressed, it is not entire clear what happens in the register modal with valid form and invalid form.
What actually happened is the close button gets pressed regardless of valid/invalid. 
This fix:
- correctly sets the close button to not be the focus and passes focus to the submit button.
- does nothing when enter pressed on invalid form
- submits on correct form when enter pressed
> Enter on Register Modal Fix

- src/app/loginComponents/onboarding/downloadcliclient/downloadcliclient.component.spec.ts
- src/app/loginComponents/onboarding/downloadcliclient/downloadcliclient.component.ts
Was using the UI URI instead of the API URI for some reason.  Fixing it.  
Also parsing requirements.txt file from the live endpoint since it may not be clear otherwise.
For ga4gh/dockstore#1381
> Use API URI

- src/app/app.module.ts
- src/app/test/mocked-objects.ts
- src/app/test/service-stubs.ts
- src/app/workflow/launch-third-party/launch-third-party.component.html
- src/app/workflow/launch-third-party/launch-third-party.component.scss
- src/app/workflow/launch-third-party/launch-third-party.component.spec.ts
- src/app/workflow/launch-third-party/launch-third-party.component.ts
gahgh/dockstore#1575
* Changed to Material
* Use/implement OnChanges in LaunchThirdPartyComponent; simplified
things, including getting rid of _workflow and _selectedVersion
properties.
* Changed links to buttons, as disable doesn't work on links (sort of
had it working with links, but then tests would complain about <a> not
having the disabled attribute).
* Disabling logic:
* Disable all if there is no content for the current version. For
DNAstack, could arguably not disable in this case, since you can
select any version in their UI, but then it would have been a
confusing message.
* Disable FireCloud if there are file-path imports.
* Display warning message if there are any imports for DNAstack, but
don't disable button.
* DNAnexus supports all imports, so never disable based on …
> Update Launch With Buttons

- src/app/workflow/launch-third-party/launch-third-party.component.spec.ts
- src/app/workflow/launch-third-party/launch-third-party.component.ts
ga4gh/dockstore#1537
Was passing the wrong path to generate DNAnexus link.
Tested the link by replacing pasting it into the browser, replacing
local protocol/host/port with `https://dockstore.org:8443`, since
that is the only whitelisted by DNAnexus. Thought I had tried that
before, but apparently I hadn't.
> Fix url generated for DNAnexus

- src/app/container/info-tab/info-tab.component.html
- src/app/container/info-tab/info-tab.component.ts
- src/app/shared/entry/versionProviderUrl.pipe.ts
- src/app/workflow/info-tab/info-tab.component.html
- src/app/workflow/info-tab/info-tab.component.ts
TRS link is now only shown when public and looking at a valid version. Also using relative path endpoint.
https://github.com/ga4gh/dockstore/issues/1631
> Fix for TRS link, only show if public

- src/app/workflow/permissions/permissions.component.html
- src/app/workflow/permissions/permissions.component.ts
ga4gh/dockstore#1627
Toggling disabled on the input was causing the containing mat-form-field
to generate the exception.
I believe this is an Angular Material bug and the only fix I could
figure out changes the UX a bit.
Before you had to wait for the adding/removing a user operation to
complete before you could start typing in a new value. Now you don't
have to wait for the adding/removing a user to complete
before you start typing in a new one.
Although being "forced" into it, I think this behavior is OK; if you
want to add a bunch of users, there's no reason to force you to wait
for each one to complete. On top of that, in my tests, the operation
is fairly fast anyway, so depending on network connection, you
typically won't even be able to start typing in a new value before
the …
> Eliminate console error when adding user

- .travis.yml
- cypress/integration/sharedWorkflows.js
- src/app/workflow/workflow.component.html
- src/app/workflow/workflow.component.ts
- travisci/web.yml
UI portion of ga4gh/dockstore#1589
This has a dependency on PR ga4gh/dockstore#1638, which has a new
endpoint.
Call new endpoint to get allowable actions. If SHARE action is one
of the actions, then user is an owner, and go ahead and fetch all
permissions for the workflow.
Unfortunately, generated TS code doesn't generate a type for the enum
returned by Actions.
> WIP: Better Handling for Permissions

- src/app/container/add-tag/add-tag.component.html
- src/app/container/container.component.html
- src/app/container/descriptors/descriptors.component.html
- src/app/container/dockerfile/dockerfile.component.html
- src/app/container/paramfiles/paramfiles.component.html
- src/app/container/version-modal/version-modal.component.html
- src/app/containers/list/list.component.html
- src/app/mytools/my-tool/my-tool.component.html
- src/app/myworkflows/my-workflow/my-workflow.component.html
- src/app/navbar/navbar.component.html
- src/app/shared/refresh-organization/refresh-organization.component.html
- src/app/workflow/descriptors/descriptors.component.html
- src/app/workflow/paramfiles/paramfiles.component.html
- src/app/workflow/version-modal/version-modal.component.html
- src/app/workflow/workflow.component.html
- src/app/workflows/list/list.component.html
- src/bootstrap4.scss
- src/ds-style-fix.scss
- src/styles.scss
- Fixes the WDL test parameter files style in the version modal.
- Added partial bootstrap 4 utility style classes because they've been useful and will be useful
- Remove several generic style (there should be many more to remove at some later point in time)
If we never migrate to bootstrap 4+, keep these because they're generally useful.
If we do migrate, remove this file.
> Use bootstrap 4 classes, fix workflow version editor form style

- src/app/container/launch/launch.component.html
- src/app/shared/entry/launch-checker-workflow/launch-checker-workflow.component.html
- src/app/shared/entry/launch-checker-workflow/launch-checker-workflow.component.ts
- src/app/workflow/launch/launch.component.html
The checker entry2json convert command was missing the version name.  This fixes it.
> Add version to checker entry2json convert command

- src/app/workflow/permissions/permissions.component.ts
Related to ga4gh/dockstore#1657, now that the PR there returns
an error message when trying to change the permissions of an
original owner.
1. When removing a user failed, wasn't displaying an feedback at all.
2. Now by default display the message that comes back from the
API; have a default message if it is not present.
> Better error handling for permissions

- src/app/workflow/dag/cwl-viewer/cwl-viewer.component.ts
- src/app/workflow/dag/dag.component.html
- src/app/workflow/dag/dag.component.ts
ga4gh/dockstore#1487
Changed HTML to not block CWL viewer. Also tried
to simplify it a little bit. Still a bit of a mess
though, as in dag.component.html, there are error
elements only for DAG, but some controls right in the
middle that also affect the CWL Viewer.
* Also removed a couple of unused fields
* And added a default error message in cwl viewer if one didn't
come back from server.
> Don't block CWL Viewer on classic Dag error

- src/app/shared/twitter.service.ts
prevent Twitter from creating a new script every time home component is visited.  Ideally, it should destroy the script when leaving but...oh well.
Partial solution for ga4gh/dockstore#1630
> Fix twitter from creating multiple scripts

- cypress/integration/mytools.js
- src/styles.scss
Reduces the tabs of the sidebar by half so that the "Unpublished" tab is not hidden too early.  Works for screens 1265px or wider.  Previously only works for screens 1605 and wider.
> Cut size of sidenav tabs by half

- src/app/loginComponents/accounts/external/accounts.component.html
- src/app/loginComponents/accounts/external/accounts.component.ts
For ga4gh/dockstore#1735
Indicates that GitHub and Google are the login methods and that one of the two are required using a chip + longer descriptions
> Add chip, lengthen description

- cypress/integration/mytools.js
- src/app/loginComponents/accounts/controls/controls.component.html
- src/app/loginComponents/accounts/controls/controls.component.spec.ts
- src/app/loginComponents/accounts/internal/change-username/change-username.component.html
- src/app/loginComponents/accounts/internal/change-username/change-username.component.spec.ts
- src/app/loginComponents/accounts/internal/change-username/change-username.component.ts
- src/app/shared/error-state-matcher.ts
Several changes for ga4gh/dockstore#1761
1. Split username exist and invalid username into two separate indicators (current + an additional form error message underneath the input field)
2. Add a debouncer so that it's only checked whether it exists or not every 250ms at most
3. Don't even bother checking if username exists when the username is invalid.
4. Added custom error matcher so form errors are triggered after touched and dirty
Doesn't really do anything for the 2nd part because changing username is optional and button click is required to actually change the username
> More form errors

- src/app/stargazers/stargazers.module.ts
ga4gh/dockstore#1764
UserService is listed as a provider in app.module.ts. A second instance
of the UserService was getting loaded due to the 2 declarations, in
here and in app.module.ts, which led to odd behavior:
Logging in and out out would only update one of the instances of the
service, and then when the other instance came into play for some
components, that instances would still have a reference to the previous
user.
> Don't create 2 instances of UserService

- src/app/shared/tooltip.ts
Updates the tooltip for default versions, before it was too general.
https://github.com/ga4gh/dockstore/issues/1230
> improved default version tooltip

- src/app/workflow/workflow.component.ts
Looks like we were asking for permissions for all workflows, not just hosted workflows. 
This is a quick patch, but the UI should be tolerant of a 401 long term, showing a workflow to its owner in this example, rather than dying completely.
> Fix for permissions killing non-hosted workflow viewing

- src/app/workflow/workflow.component.ts
#1823
@denis-yuen Let me know if you prefer I target a hotfix branch instead. I feel it's borderline; no harm comes from the call itself, although the unnecessary Ajax call might slow down the page loading a tiny bit.
> Don't call actions endpoint for public workflow

- src/app/test/service-stubs.ts
- src/app/workflow/tool-tab/tool-tab.component.html
- src/app/workflow/tool-tab/tool-tab.component.spec.ts
- src/app/workflow/tool-tab/tool-tab.component.ts
Fix for table tool content endpoint being called twice:
- first when the tool changes
- 2nd when version selected inevitably changes due to change detection
Now calls the endpoint when version is gotten and then workflow is gotten (relies on workflow$ being updated before version).
> Fix for table tool content called twice

- src/app/shared/code-editor-list/code-editor-list.component.ts
In the hosted entry edit mode, if you click add file and then delete it, it would previously keep the file in the array of source files even though it is hidden. This can mess some stuff up when saving the new version fails, and possibly other scenarios. Now if the file did not exist in the previous version it will be deleted.
A workaround for this is to simply refresh the page.
> Deleting file in hosted edit mode

- src/app/loginComponents/accounts/external/accounts.component.html
https://github.com/ga4gh/dockstore/issues/1841
After more thought I ended up only linking to the onboarding from the accounts page. I thought that adding the config would be cluttered. I still think this solves the problem, because a user would probably go to the accounts page to figure out how to setup the CLI and the link to onboarding would be right at the top.
> added link to onboarding for CLI info

- src/app/footer/footer.component.html
Footer links now open in new tab.
https://github.com/ga4gh/dockstore/issues/1844
> open footer links in new tabs

- .travis.yml
- README.md
- package.json
- scripts/install-travis-script.sh
Generating the code from swagger.yaml was getting a little annoying.  Making a script for it and adding it to prebuild
> Put all prebuild steps into prebuild

- src/app/containers/list/list.component.html
- src/app/search/search-tool-table/search-tool-table.component.html
- src/app/search/search-workflow-table/search-workflow-table.component.html
- src/app/workflows/list/list.component.html
In search and tools/workflows pages it no shows the org or namespace
https://github.com/ga4gh/dockstore/issues/1338
> show org and namespace

- src/index.html
Kind of for ga4gh/dockstore#1899
The TOC which uses the scrollspy no longer exists. Removing it.
> Remove scrollspy

- src/app/container/descriptors/descriptors.component.html
- src/app/container/dockerfile/dockerfile.component.html
- src/app/container/dockerfile/dockerfile.component.ts
- src/app/container/paramfiles/paramfiles.component.html
- src/app/shared/ga4gh-files/ga4gh-files.query.ts
- src/app/shared/ga4gh-files/ga4gh-files.service.ts
- src/app/shared/selectors/entry-file-selector.ts
- src/app/workflow/descriptors/descriptors.component.html
- src/app/workflow/descriptors/descriptors.component.ts
- src/app/workflow/launch/launch.component.ts
- src/app/workflow/paramfiles/paramfiles.component.html
ga4gh/dockstore#1937
When there are no descriptors, `nullDescriptors` is set to `true`, so go
off that instead of content
> See if descriptors exist before saying they don't

- src/app/search/search.component.html
- src/app/search/search.component.spec.ts
- src/app/search/search.component.ts
- src/app/search/search.module.ts
- src/app/shared/base.ts
For ga4gh/dockstore#1987
Our previous `<datalist>` causes problems somehow with Chrome/Chromium 71.  Not sure why.  Changing it to material autocomplete circumvents the issue.
Also adds a proper debounce to the form input
This is going to cause plenty of merge conflicts with develop :cry:
> Debounce, material autocomplete

- src/app/shared/ga4gh-files/ga4gh-files.service.ts
- src/app/workflow/files/files.component.ts
- src/app/workflow/workflow.component.ts
For ga4gh/dockstore#2004 
Gets the GA4GH files in the workflow component instead of files component.  Results in:
- Going to Files tab is slightly faster
- Launch tab correctly has the wget command without needing to visit the Files tab beforehand
- There is no "Expression has changed after it was checked" error when switching from Launch tab to Files tab and back 
- Going to the workflow component (and not visiting files tab) now has slightly higher data usage
This also:
- Removes a redundant select version call (it is already done so in the subscription)
Tool component has still kept the previous flow because none of its tabs use the GA4GH Files (though that can also be changed if needed).
@rjbautis to check if this actually works for his PR. maybe cherry-pick it to avoid merge …
> Update files in workflow component

- cypress/integration/group1/hostedTools.ts
- cypress/integration/group1/hostedWorkflows.ts
- src/app/shared/extended-tools.service.ts
- src/app/shared/extended-workflows.service.ts
ga4gh/dockstore#2050
Generated code in ContainersService and WorkflowsService classes had changed with the switch to OpenAPI client code generator; update ExtendedToolsService and ExtendedWorkflowsService to match.
> Fix export as zip for unpublished workflows

- src/app/workflow/info-tab/info-tab.component.html
Empty description now shows help message based on language type.
https://github.com/ga4gh/dockstore/issues/1836
> fixed issue with empty description always assuming CWL

- src/app/organizations/events/events.component.html
- src/app/organizations/state/events.service.ts
Show at most 10 events in ui. Unfortunately since not all events are shown, grab 30 and hope that at least 10 of them are types to be shown. In the future we need to add support to the events endpoint to filter by type.
https://github.com/ga4gh/dockstore/issues/2166
> only show subset of all events

- src/app/search/search.component.ts
- src/app/search/search.module.ts
ga4gh/dockstore#2124
After looking more into it, seems like the error message wouldn't disappear only if you navigated to the search page. Fixed by calling alertService.clearEverything() in search component.
> Fix error message not going away

- src/app/organizations/organizations/organizations.component.html
- src/app/organizations/organizations/organizations.component.scss
Small fix for the organizations page.  Display name now has spaces and should not be broken up and wrapped.
Overall, I'm still not content with organizations page layout but i'm not content with other alternatives offered so far either.
Currently using option 1.  There's many more alternatives that include some variation of grow, shrink, min-size, max-size but here's 4 major ones.  Everyone vote on it.
Makes the size of each item equal to the size of the content.  Variable width.  Each row is always full.  If not enough space in row, tosses the next item to the next row.
Pros: 
- Most simple to implement, don't need to worry about varying screen sizes
- Each item will always be large enough to hold the item's contents (and not have a large amount of  empty space)
- Smooth transitions when …
> Don't break title

- src/app/shared/dockstore.model.ts
ga4gh/dockstore#1594
This doesn't drop the port 80 if on default port of http, but
doesn't seem worth it.
There are a lot of places that use API_URL; instead of massaging
them one by one to remove the 443 port, it seems like we
should just do it here. A lot of those places have user-facing
URLs, e.g., the TRS url, the launch with instructions...
Will create a corresponding PR in compose_setup if this gets
approved.
> If webservice on port 443, omit port in url

- src/app/container/tool-file-editor/tool-file-editor.component.ts
- src/app/shared/alert/state/alert.service.ts
- src/app/shared/file-editing.ts
- src/app/workflow/workflow-file-editor/workflow-file-editor.component.ts
For issue ga4gh/dockstore#2164 
It was expected that the endpoint would always return a workflow object on success.  But since there's a possible 204 now, the UI needs to know how to handle it.
Edit: This also has the same problems with tools
> Handle 204

- src/app/container/container.component.html
- src/app/shared/entry.ts
- src/app/workflow/workflow.component.html
For ga4gh/dockstore#2265 
Was a fun bug while it lasted.
`[selectedTabChange]` doesn't quite behave the same as `[selectedIndexChange]`.  If there's `[selectedIndex]`, there must be `[selectedIndexChange]`.  It's kind of odd that there's 2 change handlers now but they don't seem to conflict with each other.  The `[selectedTabChange]` is still needed because only it knows the names of the tabs.
Push cancelled because I don't care about it
> Fix tab bounce

- src/app/shared/code-editor/code-editor.component.scss
ga4gh/dockstore#1687
In https://github.com/ajaxorg/ace/blob/ded791fcd6f0f346fb01314eaba82d89610284d2/lib/ace/virtual_renderer.js#L351,
the el.clientHeight and el.scrollHeight are always 0 on iOS. This
leads to size.$dirty never getting set to true in https://github.com/ajaxorg/ace/blob/ded791fcd6f0f346fb01314eaba82d89610284d2/lib/ace/virtual_renderer.js#L422,
which means the editor never paints.
Considered scoping this CSS for iOS only, but doesn't seem to change
the behavior on non-iOS devices, so didn't restrict it.
Note: when you look at the installed npm package, the source files
mentioned above have been concatenated into ace.js.
> Files now display on iOS

- src/app/container/descriptors/descriptors.component.html
- src/app/container/launch/launch.component.html
- src/app/container/paramfiles/paramfiles.component.html
For ga4gh/dockstore#2257
The tools should now have the descriptor types again.
> Show all descriptor types. Revert later!

- src/app/organizations/organizations/organizations.component.ts
For ga4gh/dockstore#2285
Clear store during initial form creation.  Forms are always recreated upon component init, but the store stays.  Apparently valueChanges doesn't emit the first value so I have to set it the first time on init.
Still doesn't clear search if you're on the organizations page and you click it again (no route change)
http://dockstore-ui2.herokuapp.com/organizations for demo
> Clear searchtext upon component (and form) init

- src/app/organizations/collections/state/create-collection.service.spec.ts
- src/app/organizations/collections/state/create-collection.service.ts
For ga4gh/dockstore#2294
We have a PUT and don't have the entire object, so it was setting it to null every time. Now giving it more of the entire object.
> Same hacky fix like organization

- .travis.yml
- scripts/install-travis-script.sh
- src/app/workflow/launch/launch.component.html
- src/app/workflow/launch/workflow-launch.service.ts
* Note workflow id also needs an escaped prefix
This is a follow-up for https://github.com/ga4gh/dockstore/issues/2300 discovered during testing. 
Commented code relies on and is reactivated after https://github.com/common-workflow-language/cwltool/pull/1093
> Suppress cwltool instructions for workflows

- src/app/search/basic-search/basic-search.component.html
- src/app/search/basic-search/basic-search.component.ts
- src/app/search/search.module.ts
For ga4gh/dockstore#2314
The issue says 1.6.x
There were 3 variables for roughly the same thing:
searchText$ from the state
searchText$ from the view
searchText from the view
Using reactive forms, now there are two:
searchText$ from the state
searchFormControl from the view
Ideally, it should just be using the Akita form manager
> Reactive form for debounce

- cypress/support/commands.ts
- scripts/resetDb.sql
- src/app/workflow/dag/state/dag.service.ts
- Fixes DAG labels overlapping ga4gh/dockstore#2281
- Revert the cy.exec timeout back to the default because it appears if it does timeout with the default, it will timeout with a longer one too
- Use transaction for postgres reset script because it's better practice that way
> Use transaction postgres + DAG fix

- cypress/integration/group3/starEntry.ts
- src/app/organizations/organization.module.ts
- src/app/organizations/organization/organization.component.html
- src/app/organizations/organization/organization.component.ts
- src/app/organizations/organization/time-ago-msg.pipe.ts
- src/app/organizations/time-ago-message.pipe.spec.ts
- src/app/shared/pipe/pipe.module.ts
- src/app/stargazers/stargazers.component.html
- src/app/starredentries/starredentries.component.html
- src/app/workflow/workflow.component.html
dockstore/dockstore#2392
Stargazers visually consistent for tools/workflows/organizations
Made stargazer images smaller
remove redundant titles
don't show info on my starred organizations if info null
> feature/2392/org UI fixes

- .circleci/config.yml
dockstore/dockstore#2446
* Only run for tags (for now)
* Requires the following environment variables to be set in CircleCI
1. AWS_ACCESS_KEY_ID
2. AWS_SECRET_ACCESS_KEY
3. AWS_BUCKET
4. AWS_REGION (needed even though no region is needed for s3 API)
* If the AWS_BUCKET is not set, the upload is skipped.
For now, upload the builds to <TAG NAME>-<sha> folder.
This ticket only uploads to s3; subsequent tickets will handle
the actual serving of content from s3. Some tweaks may need to be
made then, but this gets the core uploading in place.
> Upload build to s3

- .circleci/config.yml
Part of dockstore/dockstore-ui2#2447
We don't want browser to cache index.html; when we
do a new a release, we want latest index.html to be
fetched.
> Don't cache index.html

- src/app/configuration.service.ts
- src/app/loginComponents/accounts/external/accounts.component.ts
- src/app/loginComponents/accounts/external/accounts.service.ts
- src/app/loginComponents/accounts/external/links.model.ts
- src/app/loginComponents/auth/auth.component.ts
- src/app/shared/dockstore.model.ts
- src/app/shared/enum/provider.enum.ts
- src/app/shared/enum/token-source.enum.ts
- src/app/shared/state/token.query.ts
- src/app/shared/state/token.service.ts
Enables the Dockstore user to link their Zenodo credentials to Dockstore so they can create DOIs for workflows through the Dockstore UI
DOCK-763
> Links Zenodo credentials in Dockstore

- .circleci/config.yml
Next step in future PR will be to update our
continuous Cloudfront distribution to use it.
> Continuous copying of build on develop to s3

- src/app/organizations/state/organizations.query.spec.ts
- src/app/organizations/state/organizations.query.ts
For dockstore/dockstore#2282
Can't search by collections still, but now can search all string properties of the organizations.
> Search organization by all string properties

- src/app/shared/entry/info-tab-checker-workflow-path/info-tab-checker-workflow-path.component.html
- src/app/shared/entry/info-tab-checker-workflow-path/info-tab-checker-workflow-path.component.ts
UI portion of dockstore/dockstore#2330
When getting the checker workflow errors out (for whatever reason), the checker ID is still known but the actual checker workflow URL is unknown.   This checks that the actual checker workflow URL exists before showing the view checker workflow button.
No error is displayed to the user though because it might not be relevant enough (can easily change it though)
> Hide view checker workflow button on error

- cypress/integration/group2/organizations.ts
Sometimes the get image-url and click fails because it is not visible.  This appears to be caused by Cypress seeing two image-url fields instead of one.  My guess is that the previous modal was not closed before opening it again to edit.  This ensures the previous modal is closed before trying.
> Check modal is closed before opening another

- src/app/configuration.service.ts
- src/app/shared/auth.model.ts
dockstore/dockstore#2745
Problem was we weren't getting a refresh token back in the
initial authentication dance.
Looks like a dependabot update of ng2-ui-auth caused this.
Changed AuthConfig in auth.model to have a type (when I changed
it, compilation errors happened), then adjusted the code. Note
the defaultHeaders gave a compilation error as well, so I removed
it.
Regarding, changing the value of prompt to "consent", this page,
https://developers.google.com/identity/protocols/OpenIDConnect#prompt,
says the only allowed values are none, consent, and select_account.
I went with consent, because you may not get a refresh token if
you already requested an access token only before. See
https://github.com/googleapis/google-api-python-client/issues/213.
Had to use TypeScript User Defined Type …
> Fix refreshing Google tokens

- src/app/workflow/dag/dag.module.ts
dockstore/dockstore#1993
I don't think this was being covered by the sidebar anymore? Anyway, fixed the two tooltips not showing in fullscreen mode by adding the overlaycontainer.
> add fullscreen overlay so the tooltips for the 2 dag toggles show

- src/app/app.routing.ts
I don't know why it stopped working, but this fixes it.
There's no ticket for this as far as I know.  But the issue was the "Start Here" button of the home page required clicking twice.  This PR enables anchor links to the same page.
https://angular.io/api/router/ExtraOptions#anchorScrolling
> Allow same page anchor links

- src/app/mytools/my-tool/my-tool.component.html
On the My tools page accordion, we simply used a header and a flat button for the title and refresh all. I have changed this to use a mat toolbar and regular button to be consistent with the my workflows page.
> make my tools panel look like my workflows

- cypress/integration/immutableDatabaseTests/services.ts
- src/app/shared/session/session.query.ts
Do not say `Available Tools/Workflows/Services`, for now just say `Tools/Workflows/Services`.
https://github.com/dockstore/dockstore/issues/2532
> do not say available Tools/Workflows/Services

- src/app/loginComponents/auth/auth.component.spec.ts
- src/app/loginComponents/auth/auth.component.ts
dockstore/dockstore#1747
It ended up being that the errors were being suppressed because other functions in `requests.service.ts`, like `updateMyMemberships()`, were setting the state to info/clearing the errors and we only store one thing at a time.
Using the detailed matsnackbar as a workaround, but does disappear after a couple of secs.
> add snack bar error alerts to link accounts page

- src/app/loginComponents/onboarding/downloadcliclient/downloadcliclient.component.ts
Recommend OpenJDK 11 and Docker 19+
https://github.com/dockstore/dockstore/issues/2816
https://github.com/dockstore/dockstore/issues/2772
> recommend java 11 openjdk and docker 19

- src/app/shared/file.service.spec.ts
- src/app/shared/file.service.ts
- src/app/test/mocked-objects.ts
- src/app/workflow/launch-third-party/launch-third-party.component.html
- src/app/workflow/launch-third-party/launch-third-party.component.ts
- src/app/workflow/launch-third-party/state/descriptors-query.ts
dockstore/dockstore#2819
Use regexes to test for CWL http(s) imports, and disable
the CGC button if any are detected.
This is an admittedly crude test, but until dockstore/dockstore#2834,
it should do.
I couldn't find any examples of CWL http imports/mixins/includes, so I deduced them from non-https examples, hopefully correctly.
> Detect http(s) imports in CWL

- angular.json
- src/app/shared/code-editor/code-editor.component.ts
For dockstore/dockstore#2759
Staging is directing to https://staging.dockstore.org/worker-json.js instead of https://gui.dockstore.org/2.4.0-rc.0-4930df6/worker-json.js  .  Too much of a pain to direct it to the right location.  Using the publicly available cloudflare CDN version of it instead.  
Our build is smaller and I actually trust the cloudflare one more.
Our ace version is 1.4.4, so using 1.4.4.  If we update ace-editor, we will need to update the URL too sadly.
> Use cloudflare

- cypress/integration/group2/myworkflows.ts
- cypress/integration/immutableDatabaseTests/workflowDetails.ts
- src/app/workflow/view/view.component.ts
- src/app/workflow/view/view.service.ts
This PR is meant to bring the snapshot/doi UI features into a working state by changing the logic of refresh and turning the tests back on.
Address SEAB-430
> Turn back on tests for snapshotting

- src/app/home-page/home-page.component.html
- src/app/home-page/home-page.component.spec.ts
- src/app/home-page/home-page.component.ts
- src/app/home-page/home-page.module.ts
- src/app/home-page/home-page.service.ts
- src/index.html
* removed json-ld from index.html because as stated here https://www.searchenginejournal.com/google-do-not-put-organization-schema-markup-on-every-page/289981/#close and here https://developers.google.com/search/docs/data-types/sitelinks-searchbox it should not be on every page, just the homepage
* removed twitter links because as stated here https://developers.google.com/search/docs/data-types/social-profile including social media links is deprecated
* the search bar part appears to be set up right. it's up to google to decide to display it or not.
* added a few more fields from the schema.org Website and Organization categories
> updated to google recommendation

- src/app/entry/entry-file-tab/entry-file-tab.component.html
- src/app/entry/entry-file-tab/entry-file-tab.component.ts
- src/app/entry/entry-file-tab/state/entry-file-tab.query.ts
- src/app/entry/entry-file-tab/state/entry-file-tab.service.ts
- src/app/entry/entry-file-tab/state/entry-file-tab.store.ts
- src/app/workflow/version-modal/version-modal.component.html
- src/app/workflow/view/view.component.ts
- src/app/workflow/workflow.component.html
dockstore/dockstore#2707
Displays validation messages for services. There is a bug where if you navigate to a specific service or workflow on /my-services or /my-services, then the validation messages do not get grabbed. I addressed this here https://github.com/dockstore/dockstore/pull/2874 , but unsure if that's what I should be doing.
There was a fix for the tooltip but I don't think that problem exists anymore. The only time I see it is if you're in that weird half logged in state in the UI (that I don't think regular users can enter), but before it was visible when you were logged in normally.
> display validation messages

- cypress/integration/group2/myworkflows.ts
- cypress/integration/immutableDatabaseTests/workflowDetails.ts
- src/app/workflow/versions/versions.component.html
- src/app/workflow/view/view.component.html
- src/app/workflow/view/view.service.ts
Opening as draft. Currently you will be redirected back to the workflow but not the versions tab itself after linking your zenodo account. I think it's probably ok for now.
> Check to see if zenodo account is linked

- src/app/loginComponents/onboarding/downloadcliclient/downloadcliclient.component.ts
- src/app/workflow/view/view.service.ts
Fixing two typos. The order of commands in the client download instructions wasn't correct and there was a floating question mark on the snapshot dialog.
> Fixing typos

- cypress/integration/group1/hostedWorkflows.ts
- src/app/myworkflows/my-workflow/my-workflow.component.ts
dockstore/dockstore#2854
When you navigate within the app, e.g., from home page to My Workflows, the `NavigationEnd` event fires (line 132), which leads to `selectEntry` being called.
If you navigate directly to a workflow, by reloading, bookmark, etc., there is no NavigationEnd event, so `selectEntry` is never called.
Changed the code that was calling `setWorkflow` to instead call `selectEntry` (selectEntry does call setWorkflow, as well as do other stuff), which leads to a validations Ajax call, which both gets the file contents and should also fix Natalie's issue with validation messages.
@NatalieEO would you be able to test the issue you were running into with this branch?
This could probably use a test, but discovered it at the end of my day, so opening for initial review and …
> Files visible after direct navigation to workflow

- src/app/sponsors/sponsors.component.html
- src/app/sponsors/sponsors.component.ts
- src/app/sponsors/sponsors.service.ts
dockstore/dockstore#2911
Separate languages and partners into their own rows.
> Rearrange logos

- .circleci/config.yml
For dockstore/dockstore#2475
I created this branch kind of off develop but a few commits short (before all the Angular updates).
If you go to https://github.com/dockstore/dockstore-ui2/tree/feature/2475/testMergeCircleCI, you'll see that it's 7 commits behind.
You can tell this PR works because if you go into CircleCI, the Angular version is printed out and it correctly shows version 8.x.x .
Printing the Angular version is for testing purposes only, I'll be reverting it after approval.
> Merge base on CircleCI before tests

- cypress/integration/immutableDatabaseTests/toolDetails.ts
Adds a test for sharebuttons, there were already tests for the pipeline-builder
For SEAB-547
> Add test for sharebuttons

- src/app/mytools/my-tool/my-tool.component.ts
https://github.com/dockstore/dockstore/issues/2960
Previously only clicking close on a register too modal will clear the error. Now this occurs if user presses esc key or clicks outside of the modal.
> clear error msg on dialog close

- src/app/container/versions/versions.component.ts
- src/app/workflow/versions/versions.component.ts
For SEAB-636
The webservice should now automatically update the metadata and refreshing is no longer needed.
Can't be merged until https://github.com/dockstore/dockstore/pull/3024
> Don't refresh entry

- src/app/organizations/organization/update-organization-description/update-organization-description.component.html
https://github.com/dockstore/dockstore/issues/2864
cdkAutosize is apparently deprecated, changed to matTextareaAutosize and that seems to have fixed things. Pop-up window now changes with screen size.
Normal screen:
Mobile (small):
> Autosize Update Organization/Collection Description Window

- cypress/integration/group2/myworkflows.ts
- src/app/home-page/widget/entries/entries.component.html
Will now show b/c/d instead of a/b/c/d. I think the registry usually doesn't matter, so it makes sense to hide it. This is how search currently works.
Depends on https://github.com/dockstore/dockstore/pull/3061
> Recent entries does not show the registry

- src/app/footer/footer.component.html
Adds a link to Discourse (Help Desk) in the footer.
Edit:
Updated screenshot
> link to help desk in footer

- src/app/home-page/home-logged-in/home-logged-in.component.ts
- src/app/home-page/home-logged-out/home.component.ts
- src/app/shared/twitter.service.ts
For dockstore/dockstore#1630
Can't seem to stop polling on other pages, disabling polling altogether by grabbing a fixed amount of tweets.
Functionality lost:
- height is no longer fixed, no scrollbar, height auto-adjusts based on the height of the specified amount of tweets
- can no longer view more tweets when scrolling down
> Use fixed tweet limit to avoid constant polling

- src/app/home-page/home-logged-in/home-logged-in.component.html
- src/app/home-page/home-logged-in/home-logged-in.component.scss
* discourse link now says forum
* added a help desk link
* no more list bullets
Open to critique on the list bullet/no bullet.
> discourse is now forum; help desk added; no bullets

- src/app/home-page/widget/organizations/organizations.component.html
My org tooltip is now the same as the text shown.
> my org tooltip is now the display name

- src/app/organizations/organizations/organizations.component.html
- src/app/organizations/organizations/organizations.component.scss
https://github.com/dockstore/dockstore/issues/2432
Could not figure out how to deal with overflow :cry:. I think that the current design is bad anyways (I designed it) so I moved it to using rows instead of columns (on screens below large).
> on medium and smaller screens change to rows

- src/app/shared/view.ts
- src/app/workflow/view/view.component.ts
The text of the button was set, but the mode of the dialog was not.
This fixes it
dockstore/dockstore#3067
> Fix for version dialog being in wrong mode

- src/app/loginComponents/onboarding/downloadcliclient/downloadcliclient.component.ts
- src/app/loginComponents/onboarding/onboarding.component.html
- src/app/loginComponents/onboarding/onboarding.component.scss
- src/app/loginComponents/onboarding/onboarding.component.ts
https://github.com/dockstore/dockstore/issues/3114
Onboarding wizard was good for setting up your third party accounts and installing Dockstore, but then doesn't really tell you where to go next. I've added another stepper option that helps new users figure out where to go next.
EDIT: see comment for newer version
Open to more ideas.
> added next steps to onboarding

- src/app/footer/footer.component.html
On small screens (phones) the footer content switches from rows to column.
Previously
Now
> footer is column on small screens and below

- src/app/search/search.component.scss
dockstore/dockstore#2963
Current. Button defaults to count. 
Option 1
Option 2
Option 3
Option 4
Option 5
> facet buttons

- src/app/footer/footer.component.html
Somehow this got removed from my previous PR. It makes the footer content change from columns to rows on small screens.
> readd footer change to rows

- src/app/home-page/home-logged-in/home-logged-in.component.html
- src/app/home-page/home-page.module.ts
- src/app/home-page/widget/getting-started/getting-started.component.html
- src/app/home-page/widget/getting-started/getting-started.component.scss
- src/app/home-page/widget/getting-started/getting-started.component.spec.ts
- src/app/home-page/widget/getting-started/getting-started.component.ts
- src/featured-content.scss
Filling up logged-in homepage with content from on-boarding until events widget is ready. 
* added getting started widget to logged-in homepage
* added minor styling changes for featured content widget
screenshot:
> getting started widget for logged-in homepage

- src/featured-content.scss
Really minor fix, removes text underline when card is clicked, also still removes the underline on hover.
> remove underline text styling when card is clicked

- package.json
- src/app/configuration.service.ts
- src/app/shared/dockstore.model.ts
- src/app/workflow/launch-third-party/launch-third-party.component.html
- src/app/workflow/launch-third-party/launch-third-party.component.scss
- src/app/workflow/launch-third-party/launch-third-party.component.ts
dockstore/dockstore#3123
As we don't have appropriately sized logos and we don't have room to say "powered by <platform>", the button labels are text-only "NHLBI BioData Catalyst", with a tooltip mentioning the platform.
We will revisit the launch UI in the future to better handle this and other upcoming use cases, but for now this approach will suffice.
For now, go with a
> Add BD Catalyst launch buttons

- src/app/workflow/dag/dag.component.html
- src/app/workflow/dag/dag.component.ts
Instead of saying 'A valid descriptor could not be found' when the WDL file is malformed and a DAG cannot be created print the message 'Please ensure that the Descriptor is a valid WDL workflow.' 
The error message from the parser will be printed in the File tab area so the user can determine what is wrong with the WDL file. https://github.com/dockstore/dockstore/pull/3225
Addresses https://ucsc-cgl.atlassian.net/browse/DOCK-1137
For dockstore/dockstore#3118
> New error message for DAG tab

- src/app/home-page/home-logged-out/home.component.html
- src/app/home-page/home-logged-out/home.component.scss
Made another PR since the other one came from develop. This updates the logged off homepage to include the truck/ship, the landing message, and removal of the start here button.
https://github.com/dockstore/dockstore/issues/3183
> Logged off homepage changes

- .circleci/config.yml
https://github.com/dockstore/dockstore/issues/3160
Added a circleCI job that will run when a UI PR is merged to UI develop. The job will check whether UI develop can build against webservice develop and will error otherwise. The new job runs after s3 upload so UI bits will still upload.
> Build UI develop against webservice develop

- src/app/search/search.component.html
dockstore/dockstore#3249
Changes: 
- randomly set the width to 12rem (seems to fit both buttons), buttons are now the same size
- when wrapped, buttons are full width
- slight horizontal margin defect compared to the accordions because fxLayoutGap doesn't seem to work well with flex wrap
- less vertical margin for the reset filters button
Cannot seem to make the text break out of the button (aside from making the button incredibly small)
> Use flexbox for stacked buttons

- src/app/shared/code-editor/code-editor.component.ts
For dockstore/dockstore#3268
.yaml and .yml is already using the yaml highlighter
Using json highlighting for .ga
> Use JSON highlighter for .ga files

- tsconfig.json
Differential loading is failing everything on CircleCI (not enough wam), reverting now rather than later.  Keeping the updated Angular CLI though.
> Revert differential loading, keeping updated CLI though

- src/app/entry/entry-file-tab/entry-file-tab.component.html
- src/app/entry/entry-file-tab/state/entry-file-tab.service.ts
If a file is missing in the .dockstore.yml, the validation message appears when viewing the Files > Files tab and the Files > Primary Descriptor tab.
In Files > Files tab:
In Files > Primary Descriptor tab:
While I was testing the validation for services, I noticed that when I selected a new version from the drop down menu at the top, the previous version's validation message still remained. This was fixed in my [second commit](https://github.com/dockstore/dockstore-ui2/commit/6909076c3cc79327438021f7ff358b881e0f468e). The problem was that previous validation message wasn't being cleared if you changed the version when you were in the Files > Files tab.
I also noticed that if you were in the Files > Primary Descriptor tab and you selected a new version from the drop down, it would load …
> Display missing file validation for services

- src/app/container/container.component.html
- src/app/container/container.component.ts
- src/app/container/versions/versions.component.html
- src/app/container/versions/versions.component.ts
- src/app/shared/tool/tool.query.ts
Warning/error handling was moved outside of the versions.component.ts a while ago (so that the relatively large component will not be initialized.  Sadly, the add tag was inside versions.component.ts, so it disappeared alongside it.
Moving the add tag component outside.
This needs a test. I can't get Cypress to work locally 😢
> Fix missing Add Tag

- src/app/workflow/launch-third-party/launch-third-party.component.ts
dockstore/dockstore#3342
Only do it for GitHub based-workflows, as Terra is getting
the imported files directly from GitHub.
> Enable Terra for workflows with file imports

- package-lock.json
- package.json
- src/app/app.module.ts
- src/app/interceptors/custom-header.interceptor.spec.ts
- src/app/interceptors/custom-header.interceptor.ts
- tsconfig.json
For https://github.com/dockstore/dockstore/issues/3113
Added the following custom headers to track API calls from the Dockstore UI:
- X-Dockstore-UI: Dockstore UI version
- X-Request-ID: UUID for each request
- X-Session-ID: UUID for each browser session
Here's an example of what the headers look like:
> Add custom X-Dockstore-UI header

- src/app/entry/extendedDescriptorLanguage.ts
- src/app/search/map-friendly-values.pipe.ts
- src/app/shared/entry/descriptor-language.service.spec.ts
- src/app/shared/entry/descriptor-language.service.ts
For dockstore/dockstore#3292
Originally going to use a short friendly name from the webservice. but realized merging the frontend descriptor language with the backend descriptor language bean is required first
Just making a frontend-only shortFriendlyName field for now.
> Add short friendly name to extended descriptor languages

- src/app/footer/footer.component.ts
- src/app/shared/refresh.service.ts
dockstore/dockstore#3319
This tackles the scenario the case where the webservice Docker container is down/constantly restarting, but the rest of the Dockstore stack is up. What happens is that the nginx container redirects to the webservice container, but because the container has not finished initializing (or maybe because it's down -- not 100% sure), nginx returns a 404.
Comments are in code, but I think it's safe to assume for this endpoint that a 404 means the webservice is down.
See dockstore/dockstore#3319 for a more detailed discussion, and dockstore/dockstore#3387 as an issue for how the UI could check more frequently.
> Redirect to maintenance page if web service down

- src/app/shared/entry/launch-checker-workflow/launch-checker-workflow.component.html
https://github.com/dockstore/dockstore/issues/2856
Fixed the order of launch instructions to first show creating a template json and then explain how to run a checker workflow. Changed name of test file from Dockstore.json to checkparam.json to prevent overwriting the parent workflow json. 
I only changed how launch tab instructions are displayed on a parent entry. Did not change the way the instructions for a checker's stand alone entry since the functionality isn't impacted. Could do so in this PR if others feels strongly about it, but would rather coordinate changes in the scope of a larger usability update.
> checker workflow instructions

- cypress/integration/immutableDatabaseTests/dropdown.ts
- src/app/app.module.ts
- src/app/app.routing.ts
- src/app/logout/logout.component.html
- src/app/logout/logout.component.spec.ts
- src/app/logout/logout.component.ts
- src/app/shared/logout.service.ts
- src/app/shared/track-login.service.ts
dockstore/dockstore#3363
Verbiage warns user that they may not be as logged out as they think.
In looking at code to understand how to do this, noticed an unused field
in track-login.service.ts, so removed it. Also took IDE recommendation
to shorten an import.
> Add logout page

- src/app/navbar/navbar.component.html
https://github.com/dockstore/dockstore/issues/3461
Adds a permanent link to the forum directly in the toolbar.
> add help link to toolbar

- src/app/search/search-tool-table/search-tool-table.component.html
- src/app/search/search-tool-table/search-tool-table.component.ts
- src/app/search/search-workflow-table/search-workflow-table.component.html
- src/app/search/search-workflow-table/search-workflow-table.component.ts
Elasticsearch actually returns an object type that is NOT DockstoreTool or Workflow.  This object actually has verification status of the entry.  Simply using that instead.
For https://ucsc-cgl.atlassian.net/browse/SEAB-440
> Use backend verification status

- src/app/loginComponents/auth/auth.component.html
dockstore/dockstore#3446
https://github.com/dockstore/dockstore-ui2/blob/develop/.circleci/config.yml#L178
The src for this image only had a `/` in front so it was not being picked up by the regex above so the image wasn't being served by gui.dockstore.org
> broken loading gif

- src/app/entry/entry-file-tab/entry-file-tab.component.html
- src/app/entry/file-path.pipe.ts
- src/app/shared/pipe/pipe.module.ts
- src/app/workflow/register-workflow-modal/register-workflow-modal.component.html
dockstore/dockstore#3490
https://docs.google.com/document/d/1cJDSe4TSBdkZ-rt6nlxGGHPuh-W8t39BQlDw487Uzhg/edit
Addressed some of the comments Charles made
- Don't open GitHub installations page in new tab
- only ever display /.dockstore.yml as its path
- We decided the dialog pop up didn't make sense so not doing that
I didn't see an obvious way to change the default files tab, but I can look more into it if others agree with the comment.
> partial github app feedback

- src/app/home-page/recent-events/recent-events.component.html
- src/ds-style-fix.scss
For dockstore/dockstore#3219
We currently have several ways of displaying links right now.
1. Black sentence text:  use blue link with underline on hover
2. Link only: use blue link with underline on hover
3. External link only: use blue link + icon with underline on hover
4. Blue sentence text: use blue link (full URL) with underline on hover
This PR removes number 4 by simply not using blue sentences anywhere.
> Change alert style

- package-lock.json
- package.json
This PR bumps the jQuery version embedded on the Dockstore page from 3.4.0 to 3.4.1, per the recommended Netsparker remediation. This is a temporary fix for the problem of an out-of-date jQuery version; the long-term fix is to remove components that depend on jQuery, and then to remove jQuery itself. Work to accomplish this is ongoing.
Related Jira ticket: [SEAB-1204](https://ucsc-cgl.atlassian.net/browse/SEAB-1204)
> Bump jQuery version from 3.4.0 to 3.4.1

- cypress/integration/manualTests/auth-tests.ts
- package.json
- tests were failing because they were running against the wrong URL. Fixed this
- Actions menu was sometimes not going away, keeping Cypress from clicking on other parts of the page even though they are visible to the user. Added { force : true } to fix this.
> fixed base URL, made snapshot menu test less flaky

- src/app/workflow/info-tab/info-tab.service.ts
dockstore/dockstore#3489
The original ticket isn't really right. That behavior happens any time you switch descriptor types on a stub and update/save the primary descriptor path. Ended up being just this missing this line.....
> descriptor type bug

- src/app/myworkflows/sidebar-accordion/github-apps-logs/github-apps-logs.component.html
- src/app/myworkflows/sidebar-accordion/github-apps-logs/github-apps-logs.component.ts
- src/app/myworkflows/sidebar-accordion/github-apps-logs/github-apps-logs.module.ts
- src/app/search/map-friendly-values.pipe.ts
Assist Gary with the lambda display
SEAB-1367
Imported DatePipe in order to format the eventDate into a string,
which enables the filter string to match with the eventDate
Added a new animation state and transition in order to fix
material sort triggering expandable rows
Added a new map friendly value to replace the 'true' and 'false'
values to 'Success' and 'Failed' for the 'success' column
Added a new map friendly value to replace 'PUSH', 'DELETE', and 'INSTALL' to
'Git Push', 'Git Delete', and 'Install' for the 'type' column
Image of how the log would look with new friendly values:
> Feature/seab 1367/assist lambda display

- src/app/home-page/recent-events/recent-events.component.scss
- src/app/home-page/widget/news-updates/news-updates.component.html
- src/app/home-page/widget/news-updates/news-updates.component.scss
- src/styles.scss
As described in https://github.com/dockstore/dockstore/issues/3307
The changes add timestamps to `News and Updates` entries as seen in the following screenshot:
> timestamps on news and updates UI

- src/app/container/container.component.html
https://ucsc-cgl.atlassian.net/browse/SEAB-1393
If an auto tool from Quay.io has no build triggers with a Git URL, display a message asking to add a build trigger.
Edit: message is now
> This Quay.io tool does not have an associated Git repository. Please view the Quay.io repository and add a build trigger for a valid Git repository. Once the build has been added, refresh the tool.
> error message for tools with no git url

- src/app/container/container.component.html
- src/app/container/deregister-modal/deregister-modal.component.ts
- src/app/container/info-tab/info-tab.component.html
- src/app/container/versions/versions.component.html
- src/app/containers/list/list.component.html
- src/app/docs/docs.component.html
- src/app/footer/footer.component.html
- src/app/home-page/home-logged-out/home.component.html
- src/app/home-page/widget/getting-started/getting-started.component.html
- src/app/loginComponents/onboarding/onboarding.component.html
- src/app/loginComponents/onboarding/quickstart.component.html
- src/app/navbar/navbar.component.html
- src/app/search/search-tool-table/search-tool-table.component.html
- src/app/search/search-workflow-table/search-workflow-table.component.html
- src/app/sitemap/sitemap.component.html
- src/app/sponsors/sponsors.component.html
- src/app/starredentries/starredentries.component.html
- src/app/workflow/info-tab/info-tab.component.html
- src/app/workflow/register-workflow-modal/register-workflow-modal.component.html
- src/app/workflow/tool-tab/tool-tab.component.html
- src/app/workflow/versions/versions.component.html
- src/app/workflow/workflow.component.html
- src/app/workflows/list/list.component.html
This PR accepts two suggested changes from [LGTM](https://lgtm.com/projects/g/dockstore/dockstore-ui2/alerts/?mode=list).
1. Use bound attributes in links instead of double braces. Using double-braces in a link can cause rendering of a broken link in some circumstances. [more info](https://lgtm.com/rules/1945880031/)
1. remove unused imports
This issue was also observed in reviewing the LGTM alerts. https://github.com/dockstore/dockstore/issues/3645
> Use bound href attribute (lgtm fixes)

- src/app/container/info-tab/info-tab.component.html
- src/app/workflow/info-tab/info-tab.component.html
- src/styles.scss
Main issue: https://github.com/dockstore/dockstore/issues/1450
Using `flex` for the inline forms in a very similar way as Bootstrap 4.1+ https://getbootstrap.com/docs/4.1/utilities/flex/
Screenshots in next comment
> fill input fields to available width when editing in info tab

- tsconfig.json
Until we can figure out what's wrong with SRI + differential loading
Reverts dockstore/dockstore-ui2#1028
> Revert "Feature/differential loading take4"

- src/app/navbar/navbar.component.css
- swagger-config.json
For dockstore/dockstore#3552
Override bootstrap.  Wonder if I should move this to the styles.scss.  Can anyone think of another place where there's a dropdown with anchors?
> Override bootstrap

- .circleci/config.yml
This change should add a notification (that includes a link to the build) when a failure occurs during the smoke tests. There isn't a great way to test it since it requires the job to run and fail, and its set to run on a timer. To verify this worked we will have to wait until a smoke test runs (and fails). However, the tests appear to be failing at the moment so that should happen pretty quickly.
https://circleci.com/workflow-run/6168c2f9-e770-40a6-97f7-67a2c1420b96
> Add a notification when smoke test fails.

- .circleci/config.yml
They are just firing an alert every day that I am ignoring.
SEAB-1454 is in the current sprint to fix auth tests.
> Disable auth tests for now

- .circleci/config.yml
- cypress/integration/manualTests/auth-tests.ts
https://ucsc-cgl.atlassian.net/browse/SEAB-1454
Fixes the auth smoke tests so that they run on dev, also made changes to make the tests less flaky. 
Not sure why, but certain operations seem more flaky when pointing to a live server (dev). Tried a bunch of the official cypress best practices, but they either didn't help with the flakiness or in some cases made things worse. 
- Should assertions and routes are particularly flaky
- pretty much whenever visit() is used only hardcoded wait times consistently resolved flakiness, I minimized using this, but nothing else worked in the places where they're added here.
- Usually using routes + waits helps resolve some flakiness, but didn't seem to help much for some parts of the auth tests on dev.  
- Sometimes waiting for the routes to resolve …
> fix authorized automated smoke tests

- cypress/integration/immutableDatabaseTests/searchTable.ts
- cypress/integration/immutableDatabaseTests/verification.ts
- cypress/integration/manualTests/basic-enduser.ts
- src/app/app.module.ts
- src/app/banner/banner.component.spec.ts
- src/app/container/descriptors/descriptors.component.spec.ts
- src/app/container/descriptors/descriptors.component.ts
- src/app/container/launch/tool-launch.service.spec.ts
- src/app/container/paramfiles/paramfiles.component.ts
- src/app/entry/entry-file-tab/state/entry-file-tab.service.ts
- src/app/footer/footer.component.spec.ts
- src/app/search/elastic-search-client.ts
- src/app/shared/constants.ts
- src/app/shared/file.service.spec.ts
- src/app/shared/ga4gh-files/ga4gh-files.service.ts
- src/app/shared/refresh.service.spec.ts
- src/app/shared/selectors/entry-file-selector.ts
- src/app/test/service-stubs.ts
- src/app/workflow/descriptors/descriptors.component.spec.ts
- src/app/workflow/descriptors/descriptors.component.ts
- src/app/workflow/files/files.component.spec.ts
- src/app/workflow/info-tab/info-tab.service.spec.ts
- src/app/workflow/launch-third-party/launch-third-party.component.spec.ts
- src/app/workflow/launch-third-party/state/descriptors.service.spec.ts
- src/app/workflow/launch/launch.component.spec.ts
- src/app/workflow/launch/workflow-launch.service.spec.ts
- src/app/workflow/paramfiles/paramfiles.component.spec.ts
- src/app/workflow/paramfiles/paramfiles.component.ts
Main issue: https://github.com/dockstore/dockstore/issues/3468
See https://dockstore.org/api/static/swagger-ui/index.html for API reference.
**Goal:**
- Convert GA4GH (TRS 2.0.0 beta) `/api/ga4gh/v2` URLs to GA4GHV20 (TRS 2.0.0 final) `/ga4gh/trs/v2`
**Exceptions:**
- extendedGA4GH URLs use `/api/ga4gh/v2/extended`
- `/api/ga4gh/v2/metadata` has no equivalent in TRS 2.0.0 final
+ used by `MetaDataService` & `DownloadCLIClientComponent`
**Changes:**
- Update `ga4ghPath` constant to be `/ga4gh/trs/v2`
- Create new `ga4ghExtendedPath` constant `/api/ga4gh/v2/extended` to replace `ga4ghPath` for GA4GH API extensions
- Use these constants for URL strings wherever possible
- Replace `GA4GHService` with `GA4GHV20Service` everywhere except for `MetaDataService` & `DownloadCLIClientComponent`
> Update UI to use TRS 2.0 final rather than beta endpoints

- cypress/integration/manualTests/zenodo.ts
- src/app/workflow/info-tab/info-tab.component.html
- src/app/workflow/info-tab/info-tab.component.ts
Main issue: https://github.com/dockstore/dockstore/issues/3673
Use Zenodo-badge DOI links on Info tab:
Copying the usage in the Versions tab:
> info-tab DOI links

- package-lock.json
- package.json
- src/app/app.module.ts
- src/app/configuration.service.ts
- src/app/footer/footer.component.html
- src/app/footer/footer.component.spec.ts
- src/app/footer/footer.component.ts
- src/app/footer/footer.service.spec.ts
- src/app/footer/footer.service.ts
- src/app/footer/git-tag.pipe.spec.ts
- src/app/footer/git-tag.pipe.ts
- src/app/shared/dockstore.model.ts
dockstore/dockstore#3509
* Update copyright year by making it dynamic
* Change link to ga4gh/dockstore to dockstore/dockstore
dockstore/dockstore#3698
* Link for UI (and web service) works for actual commits. Try to figure out if the link should be to a tag
or commit and generate link accordingly.
* For web service, if the version is a SNAPSHOT jar (which it is on dev), or a `development-build`, show commit id
SEAB-1552
Add a "Build Info" link, which copies build info in markdown form to clipboard:
```
[Webservice](https://github.com/dockstore/dockstore/commits/981edd1) - 981edd1
[UI](https://github.com/dockstore/dockstore-ui2/commits/597aeeed) - 2.6.1-39-g597aeeed
[Compose Setup](https://github.com/dockstore/compose_setup/releases/tag/1.9.0) - 1.9.0 …
```
> Footer improvements and fixes

- src/app/home-page/widget/organizations/organizations.component.ts
- was working on [3182](https://github.com/dockstore/dockstore/issues/3182), which appears to be already fixed
- organizations.component.ts had a `debounceTime(formInputDebounceTime)` which is not needed
- removed the line, searching in the Organizations widget on the logged-in homepage should continue to wait for typing to stop before making any API calls
> Delete unneeded debounce line in organizations widget

- package-lock.json
- package.json
- src/app/workflow/dag/dag.component.html
- src/app/workflow/dag/dag.component.ts
- src/app/workflow/dag/dag.module.ts
- src/app/workflow/dag/wdl-viewer/state/wdl-viewer.service.spec.ts
- src/app/workflow/dag/wdl-viewer/state/wdl-viewer.service.ts
- src/app/workflow/dag/wdl-viewer/wdl-viewer.component.scss
- src/app/workflow/dag/wdl-viewer/wdl-viewer.component.spec.ts
- src/app/workflow/dag/wdl-viewer/wdl-viewer.component.ts
- src/app/workflow/dag/wdl-viewer/wdl-viewer.html
- src/app/workflow/dag/wdl-viewer/wdl-viewer.service.spec.ts
https://ucsc-cgl.atlassian.net/browse/SEAB-1402 
Removed pipeline-builder because of https://github.com/epam/pipeline-builder/issues/57 and it doesn't handle WDL 1.0. Commented out wdl-viewer.
Used Gary's suggestion in his comment for rc because it needs to update minimist https://github.com/dominictarr/rc/issues/113
> npm audit fixes

- src/app/organizations/registerOrganization/register-organization.component.html
- src/app/organizations/registerOrganization/register-organization.component.ts
- src/app/organizations/state/register-organization.service.ts
Part 1 of 2 Draft for https://ucsc-cgl.atlassian.net/browse/SEAB-203
The idea is we disable all normal users from editing the approved organization name and display name. In the kind of unlikely case where they want to do so, they'll need to contact Dockstore (us). We would use the exact same endpoint (PUT) in the swagger-ui.
Other PR https://github.com/dockstore/dockstore/pull/3815
Disabled Material input looks like:
> Disable name and display name when editing organization

- src/styles.scss
For partial dockstore/dockstore#3179
Global style to break on all tables. None of them should horizontal scroll ever.
It's still a mystery to me why tools and workflows behaved differently
> Word break on all td elements

- angular.json
- package-lock.json
- package.json
- src/styles.scss
Original ticket: https://ucsc-cgl.atlassian.net/browse/SEAB-1651
Using a forked and separately maintained [module](https://www.npmjs.com/package/material-design-icons-iconfont) of Google's material icons. This is due to Google's material icons module being out-of-date, see [issue](https://github.com/google/material-design-icons/issues/798).
> Switched material icons module to a maintained version

- .circleci/config.yml
UI repo portion of #3891
Created a CircleCI context which has dockstoretestuser4 password/token.
Turns out CircleCI has a deal where there aren't limits in most cases. But they
say the limits may go into affect in the future: https://support.circleci.com/hc/en-us/articles/360050623311-Docker-Hub-rate-limiting-FAQ.
Punted on orbs for now; It's not trivial; you need to replicate the logic of the orb,
or wait for the orb to add auth options.
See
https://support.circleci.com/hc/en-us/articles/360051099071-Docker-Hub-Authentication-With-Orb-Executors
> Make Authorized Calls to fetch DockerHub images

- cypress/integration/immutableDatabaseTests/app-spec.ts
- cypress/integration/immutableDatabaseTests/searchTable.ts
- src/app/containers/list/list.component.html
- src/app/search/search-tool-table/search-tool-table.component.html
- src/app/search/search-workflow-table/search-workflow-table.component.html
- src/app/workflows/list/list.component.html
- src/styles.scss
Issue: dockstore/dockstore#3925
Changed class name for mat-icon stars to prevent icon duplication.
> Changed class name for star icon styling to prevent duplicate icons

- src/app/sponsors/sponsors.component.html
So close yet so far
Tried for a considerably long time to get that 1%...turns out I'm bad at CSS. https://ucsc-cgl.atlassian.net/browse/SEAB-1951
Actual differences
Before:
After:
> Fix alt images

- src/app/container/tool-file-editor/tool-file-editor.component.ts
switched from "hosted entry" to "hosted tool" as suggested, and replaced the namespace var with name to get the hosted tool's name instead of it's namespace. The namespace and my hosted tool's names were similar, I think, so that was why I didn't catch it.
> made some minor changes to the detailed success message

- src/app/shared/dockstore.model.ts
- src/app/shared/entry.ts
https://ucsc-cgl.atlassian.net/browse/SEAB-2162
Add slash so that Discourse URL shouldn't require one but will work either way.
> Discourse URL Slash

- src/app/shared/code-editor/code-editor.component.ts
Main ticket: https://github.com/dockstore/dockstore/issues/3518
Original PR: #1129
We substitute assets with the actual CDN path via substitution; my original code was not matching. I updated the URLs to fit the pattern: https://github.com/dockstore/dockstore-ui2/blob/ec8ef9efce43f6cc8365e8bed5770a6235d93df4/.circleci/config.yml#L195
> Fix sample descriptor code URLs for CDN path substitution

- src/app/search/query-builder.service.ts
Part 2 of 2 for dockstore/dockstore#3985
The code comment explains why this fix is needed and why it works. Seems the current implementation gave the illusion that search works because it's searching through a lot of other fields.  
New behaviour:
Matches when tool_path or full_workflow_path contains the search text even if the path has a prefix or suffix
Note: the results are still unordered. Sourcefile content matches have the same priority as full_workflow_path matches.
Reviewers should test it locally to be thorough.
> Fix for text search

- cypress/integration/manualTests/search.ts
Fix for a test due to dockstore/dockstore#3985
Whereas before, searching "dockstore_" yielded no results, the fix for dockstore/dockstore#3985, does yield results such as:
"BD2KGenomics/dockstore_workflow_cnv"
This is because path matching actually works now. You can try this on dev vs prod
> Search a worse string in test

- src/app/organizations/collection/collection.component.scss
- src/app/organizations/organizations/organizations.component.html
- src/app/search/search-workflow-table/search-workflow-table.component.html
- src/app/search/search-workflow-table/search-workflow-table.component.ts
1. [dockstore/issues/4106](https://github.com/dockstore/dockstore/issues/4106)
2. [SEAB-2283 comment about card titles](https://ucsc-cgl.atlassian.net/browse/SEAB-2283)
The screenshot of the messed up tools and workflows line height is fixed, it seems like that only happened on Firefox. At the same time I realized on Chrome the line does not break when screen size is small. They are all fixed now.
3. [SEAB-2283 comment about organization img](https://ucsc-cgl.atlassian.net/browse/SEAB-2283)
Gave it an empty `div` when `src` is unknown, so the problem is right now some `src` are there but they are no longer valid. Wondering if anyone could give me some input on this
> styling bugs

- src/app/search/query-builder.service.ts
In migrating to AWS elasticsearch, we had to go drop back to ES 7.9,
which does not support `case_insensitive`.
> Remove ES 7.10 feature

- src/app/container/info-tab/info-tab.component.html
- src/app/docs/docs.component.ts
- src/app/funding/funding.component.ts
- src/app/home-page/home-logged-out/home.component.html
- src/app/shared/user/user.service.ts
- src/app/workflow/info-tab/info-tab.component.html
Fixing an easy sonarcloud security hotspot. https://sonarcloud.io/project/security_hotspots?id=dockstore_dockstore-ui2&hotspots=AXbOBYtivLLK457gggR_
There are a few other places that we may be able to switch to https
> Change links to https when there are no other side effects

- cypress/integration/manualTests/search.ts
https://github.com/dockstore/dockstore/issues/4008
Seems like I'm unable to reproduce this problem, added wait(1000) and modified assertion.
Note, right now there's a `michaelgatzen/dockstore_demo/HelloWorldWorkflow` when searching for `dockstore_d`, so I changed that to `dockstore_i`
> search.ts reset filters

- THIRD-PARTY-LICENSES.csv
- package-lock.json
- package.json
- src/app/workflow/dag/state/dag.service.ts
* update cytoscape version
* Use @types/cytoscape for stylesheet section
* Change font-size and opacity definitions
I was a bit confused the string representation of the font-size `16px` wouldn't build so I removed the `px` and quotes and it builds as expected.
https://github.com/dockstore/dockstore/issues/4005
> Update cytoscape and use Stylesheet type

- src/app/container/launch/launch.component.html
- src/app/container/launch/launch.component.ts
https://github.com/dockstore/dockstore/issues/3676
The problem before was when displaying the code block inside a container, _sometimes_ the correct descriptor type(for exmaple WDL) was not passed into some `launchService` functions. Thus this resulted in a missing `--descriptor wdl`
Here is after the fix:
Optimization ticket: https://github.com/dockstore/dockstore/issues/4194
> passing in the correct parameter value of descriptor type before displaying code block

- src/app/loginComponents/accounts/external/accounts.component.html
First part of [SEAB-1713](https://ucsc-cgl.atlassian.net/browse/SEAB-1713)
Hid the show token button and copy token button for non-Dockstore tokens so users can't access it. Looks like the following:
> Hide display of non-Dockstore tokens

- src/app/workflow/info-tab/info-tab.component.html
https://github.com/dockstore/dockstore/issues/3704
remove the restub button on checker workflow
(Currently the restub button is broken even outside of checker workflow, already created a ticket on this: https://github.com/dockstore/dockstore/issues/4193)
> remove restub button on checker workflow

- cypress/fixtures/refreshedChecker.json
- package.json
- scripts/generate-openapi-script.sh
- scripts/run-webservice-script.sh
- src/app/myworkflows/my-workflow/my-workflow.component.ts
- src/app/shared/state/token.service.ts
- src/app/source-file-tabs/source-file-tabs.component.spec.ts
- src/app/test/service-stubs.ts
Part 2 of [SEAB-1713](https://ucsc-cgl.atlassian.net/browse/SEAB-1713).
The UI was getting the user's GitHub organizations itself, so I removed it and used the webservice endpoint instead. From what I could find, the function was only being called in my-workflow.
> Use webservice endpoint to get user's GitHub organizations

- src/app/loginComponents/accounts/external/accounts.component.html
- src/app/loginComponents/accounts/external/accounts.component.ts
- src/app/stargazers/stargazers.component.css
- src/styles.scss
https://ucsc-cgl.atlassian.net/browse/SEAB-2781
Added orcid branded button and changed wording of linking account buttons.
Add an explanation of what we do with ORCID credentials.
After reading the documentation, I don't think the person's name is necessary. The name is an option if you aren't using the full or compact id display
> orcid branding

- src/app/about/about.component.html
- src/bootstrap4.scss
- src/material.scss
For https://ucsc-cgl.atlassian.net/browse/SEAB-2850
The headings are now an arbitrary 10% of the width of the subcomponent
Renamed candy because why not.
> Feature/seab 2850/about page cleanup

- src/app/about/about.component.scss
- src/app/about/about.component.ts
- src/app/footer/footer.component.scss
- src/app/footer/footer.component.ts
- src/app/home-page/home-logged-out/home.component.html
- src/app/home-page/home-logged-out/home.component.scss
- src/app/home-page/widget/getting-started/getting-started.component.scss
- src/app/organizations/organization/organization.component.scss
- src/app/organizations/organizations/organizations.component.scss
- src/material.scss
- src/materialColorScheme.scss
- src/styles.scss
PR just to remove duplicate 397a84
Demonstrates how not to repeat colors
Split material.scss to a different file because:
https://material.angular.io/guide/theming#defining-a-custom-theme
"Your custom theme file should not be imported into other SCSS files. This will duplicate styles in your CSS output. If you want to consume your theme definition object (e.g., $candy-app-theme) in other SCSS files, then the definition of the theme object should be broken into its own file, separate from the inclusion of the mat-core and angular-material-theme mixins."
> Remove duplicate secondary color

- src/app/container/container.component.html
- src/app/organizations/collection/collection.component.html
- src/app/organizations/collection/collection.component.scss
- src/app/organizations/organization/organization-starring/organization-starring.module.ts
- src/app/organizations/organization/organization.component.html
- src/app/organizations/organizations/organizations.component.html
- src/app/organizations/organizations/organizations.component.scss
- src/app/stargazers/stargazers.component.css
- src/app/stargazers/stargazers.component.html
- src/app/starring/starring.component.html
- src/app/starring/starring.module.ts
- src/app/workflow/workflow.component.html
- src/styles.scss
For [SEAB-2849](https://ucsc-cgl.atlassian.net/browse/SEAB-2849)
Did 17, 19 - 22 from the [Dockstore UI review doc](https://docs.google.com/document/d/1GLshBv7Ue09ceCFDSLmFvrgbEofGkY6R0jXlKxVjqHc/edit)
- **Collection page breadcrumb**
- **Consistent logo location**
- Stargazer page has the same header as the organization page so the logo and org title location is the same
Also note the stargazers breadcrumb
- For the most part, the logo location from the organization page to the collection page is the same
The logo location may be a little different if the description of the organization is longer than the collection (i.e. 2 line org description vs 1 line collection description). I couldn't really find a way to make it consistent with different length descriptions unless I put the logo at …
> Clean up collections and stargazers page

- src/app/app.routing.ts
- src/app/home-page/home-logged-out/home.component.html
- src/app/login/login.component.html
- src/app/login/login.component.ts
- src/app/navbar/navbar.component.html
The register button was implemented as per mock up but realized that the register button on the nav bar is on the left whereas on the page it is on the right, should the register button be on the right instead for consistency?
Probably: https://ucsc-cgl.atlassian.net/browse/SEAB-2844
> Adding register button 

- cypress/integration/manualTests/basic-enduser.ts
Breaking out from https://github.com/dockstore/dockstore-ui2/pull/1247
This will fix the test for the next deployment, and I'll merge the nightly smoke testing changes afterwards (otherwise we'll get nightly smoke test failure reports until the new release of both staging and prod)
> Removed input that breaks smoke tests

- scripts/generate-openapi-script.sh
- src/app/configuration.service.ts
- src/app/home-page/home-logged-in/home-logged-in.component.html
- src/app/home-page/home-logged-out/home.component.html
- src/app/home-page/home-page.module.ts
- src/app/home-page/widget/featured-content/featured-content.component.ts
- src/app/home-page/widget/featured-content/featured-news.component.ts
- src/app/shared/dockstore.model.ts
* makes featured news pull from cloudfront just like featured content
* probably need help styling and reusing the featured component
Relies on https://github.com/dockstore/extra-content/pull/23 to provide content (split up news and content, plus remove styles on news to match mock-ups) and https://github.com/dockstore/dockstore/pull/4269 for a back-end change
Eventually should make it to https://projects.invisionapp.com/share/VNZ92Z0T2B3#/screens/434510663
Currently looks like 
Logged off homepage
Logged in (will be very different in 1.12)
> Featured news update

- src/app/organizations/organizations/organizations.component.html
- src/app/stargazers/stargazers.component.html
A fix for the odd spacing for stargazers and organizations identified in the comments of: https://ucsc-cgl.atlassian.net/browse/SEAB-2849
> Fix stargazers and organizations card spacing

- .circleci/config.yml
The release tag `2.8.0-rc.0` broke the regex for automated smoke testing, as it didn't consider `-` a valid character (I had only considered dots).
Now, the regex accepts `-`, `.` and `alphanumeric` characters. I don't think there should be any other characters for the regex to consider, but if there are, I can modify further.
> Tags with a dash broke the regex

- cypress/integration/manualTests/basic-enduser.ts
Collapse the two commands into one so that Cypress does not see 
and keep trying to find an img in it
Also doubled up on the DAG tab clicking...the new material does weird things
> Use one command

- package.json
- scripts/generate-openapi-script.sh
- scripts/run-webservice-script.sh
All frontend develop builds or PRs broken because our JARs were 30 days old
Had to use the release branch's JAR (even though we're generally not supposed to) because the frontend merged the release branch's featuredNewsUrl to the frontend develop branch but the backend hasn't merged the featuredNewsUrl to the backend develop branch
> Update backend artifacts

- src/app/search/search.component.html
https://github.com/dockstore/dockstore/issues/4250
Wrapped the search string if it was super long:
> Wrap long search string

- src/app/workflow/snapshot-exporter-modal/snaphot-exporter-modal.component.html
For dockstore/dockstore#4285
Instead of checking if you have a Zenodo token, check if the version has a DOI URL first
Not much to show, just looks normal:
> Check if there's a DOI URL first

- cypress/support/commands.ts
- package.json
- scripts/generate-openapi-script.sh
- scripts/run-webservice-script.sh
There was merge issues or something. It was using a CircleCI Jar for openapi generation but actual release jar for running the webservice
Also changing generate-openapi-script.sh to not need to comment/uncomment to first two lines
> Use develop CIRCLECI JAR

- angular.json
This fixes the missing subresource integrity attribute on the CSS styles inside noscript tags generated by Angular.
This is necessary because the `inlineCritical` setting changed its default value from false (Angular 11) to true (Angular 12).
See [SEAB-3225](https://ucsc-cgl.atlassian.net/browse/SEAB-3225) and #1325 (this pull request replaces 1325).
> Fix missing SRI for CSS styles inside noscript tags

- src/app/workflow/snapshot-exporter-modal/snapshot-exporter-modal.service.ts
For dockstore/dockstore#4366
Going to use `workflowName || repository` as the workflow name (it's not unique btw, only `workflow.full_workflow_path` is). suggestions welcome.  Another option is to omit it entirely and only mention version
hosted workflows use `repository` only in the error message (because workflowname isn't a thing)
> Fall back to repository

- src/app/workflow/info-tab/info-tab.component.html
Although what's live does resolve to the FAQ page successfully, the FAQ page does not have anything about the github app on it -- it probably got removed and the relevant section given its own page. I replaced it with a link that resolves on stable and develop to a header in the github app docs page instead.
> Hotfix URL

- .circleci/config.yml
- cypress/integration/group2/mytools.ts
- package.json
- src/app/container/info-tab/info-tab.component.html
- src/app/container/register-tool/register-tool.component.html
- src/app/container/register-tool/register-tool.component.ts
- src/app/container/register-tool/register-tool.service.ts
- src/app/search/state/search.service.spec.ts
- src/app/shared/image-provider.service.spec.ts
- src/app/shared/image-provider.service.ts
- src/app/shared/validationMessages.model.ts
- src/app/test/service-stubs.ts
- src/styles.scss
For https://github.com/dockstore/dockstore/issues/4331
Corresponding webservice PR: https://github.com/dockstore/dockstore/pull/4420
Registering a public Amazon ECR tool: [public.ecr.aws/x5g7o3i3/appropriate/curl](https://gallery.ecr.aws/x5g7o3i3/appropriate/curl)
- Docker registry path is pre-filled and disabled
- `x5g7o3i3` is what Amazon calls a registry alias. For our use, it's a namespace. 
- Side note: Amazon allows you to request a custom alias that's more readable. For example, for the repository: [public.ecr.aws/ubuntu/ubuntu](https://gallery.ecr.aws/ubuntu/ubuntu), the first `ubuntu` is a custom registry alias
- `appropriate/curl` is the repository name (this one has slashes in it)
Registering a private Amazon ECR tool: `467982390456.dkr.ecr.us-east-1.amazonaws.com/kathy-test`
- …
> Allow public and private Amazon ECR tools to be registered

- src/app/loginComponents/onboarding/downloadcliclient/downloadcliclient.component.ts
Whilst fixing the formatting issues in the quick-start MacOS Java installation section, I discovered that some of the instructions were incorrect ("/usr/libexec/java_home -v (version)" prints the path to the specified Java version, but doesn't set anything).  So, I decided to overhaul the section that discusses the non-Brew Java install to improve clarity and prioritize the common success case.  The "unset JAVA_HOME" line before exporting JAVA_HOME is a workaround for a purported Big Sur bug (https://developer.apple.com/forums/thread/666681) which I'm unable to confirm because I'm running Mojave.  I tested all the commands, but I am a Mac n00b so please scrutinize xtra.
https://ucsc-cgl.atlassian.net/browse/DOCK-1888
https://github.com/dockstore/dockstore/issues/4417
Screenshot of …
> Overhauled Quick-Start MacOS Java installation instructions

- src/app/loginComponents/accounts/external/accounts.component.html
- src/app/loginComponents/accounts/external/accounts.component.ts
- src/app/loginComponents/accounts/external/accounts.service.spec.ts
- src/app/loginComponents/accounts/external/accounts.service.ts
Changed the ORCID accounts box to use the root of Dockstore.ORCID_AUTH_URL to create the link to the user's ORCID.
https://github.com/dockstore/dockstore/issues/4253
https://ucsc-cgl.atlassian.net/browse/DOCK-1795
This was hard to test: the better testing methods would consume much more effort to implement than the fix itself.  Gary suggested that user testing on dev might be easiest, and, in lieu of that, Charles suggested I move the helper function getRoot() into AccountsService and write some tests for it since it contained a regexp, and submit a PR.  And here we are.  I tested the modified clause in the HTML template by copying it elsewhere in the template, where it rendered successfully, so I'm 98%+ sure it'll work whenever we deploy it on dev/staging.  Someone will need to check.
I …
> Feature/dock 1795/use sandbox orcid on dev

- src/styles.scss
Parts of the class were being overwritten by Material. Some options:
- This change
- Use !important
- Make the class component specific (possible duplication further down the road)
> Fix class being overwritten by Material

- .circleci/config.yml
- consequence of the channel re-ordering, we want smoke tests to go into channels that reflect what server got tested
- would use 4.4.4 of the Slack orb but it requires switching to context immediately
- can look at sample output at https://app.slack.com/archives/CTAGGL7G9/p1631139351010900
> specific channels for smoke tests

- .circleci/config.yml
Towards https://ucsc-cgl.atlassian.net/browse/SEAB-2852
CircleCI will use project-level environment variables first, but
once we remove them this will enable the UI to fall back on the
context.
> Use the AWS context

- package.json
- src/app/container/view/view.component.html
For https://github.com/dockstore/dockstore/issues/4325
Removed a few asyncs and wrapped the non-public buttons in an ng-container (just like how workflow does it)
> Disable public set default version

- .circleci/config.yml
Got an email from circle ci
> You're currently using a legacy image that is not optimized for performance on CircleCI on the following project(s):
> [dockstore-ui2]
> As of Dec 31, 2021, legacy images will no longer be supported on CircleCI
More info at https://circleci.com/blog/announcing-our-next-generation-convenience-images-smaller-faster-more-deterministic/ and https://discuss.circleci.com/t/legacy-convenience-image-deprecation/41034
This deals with part of  it, but not all since postgres is blocked due to the linked issue in a commit below
**Issue**
https://github.com/dockstore/dockstore/issues/4555
> migrate circle ci images

- .circleci/config.yml
Circle CI has optimised images and will be EOL existing images at the end of 2021
**Issue**
https://github.com/dockstore/dockstore/issues/4555
> migrate postgres cimg image

- cypress.json
Disable Cypress retries locally.
**Issue**
Ad hoc issue. Disabling the Cypress retries locally because the idea is that:
- Non-flakey tests should not require any retries on CI or locally
- Tests that are flakey on CI but not locally will still have retries (not great but is considered acceptable for now)
- But tests that are flakey locally (and maybe the CI too) should be caught immediately and fixed. Disabling the retries would let developers immediately know that they should fix the test.
> No Cypress retries locally

- src/app/organizations/collections/collections.component.html
- src/app/organizations/organization-members/organization-members.component.html
- src/app/shared/entry-actions/tool-actions.component.html
- src/app/shared/entry-actions/workflow-actions.component.html
Remove `color="basic"` throughout the codebase
**Issue**
Ad hoc issue. Noticed we had `color="basic"` applied to material components. The only known options that do anything are primary, accent, warn, etc. Removing it so this isn't perpetuated through new components added.
> Remove unnecessary code

- src/app/container/version-modal/version-modal.component.html
Fix the docker pull copy button 
**Issue**
dockstore/dockstore#4533
> fix copy button

- src/app/search/search.component.ts
It was shown that rapidly changing the tabs before the page has finished loading causes the infinite loop.
For some reason the event gets triggered even though it's not the active tab. Do a quick check.
Note: Rapidly changing tabs is incredibly noticeable by most users. There may be another infinite loop elsewhere that I can't find.
**Issue**
For SEAB-3548
> Prevent tab change infinite loop

- cypress/integration/immutableDatabaseTests/workflowDetails.ts
- src/bootstrap4.scss
- src/styles.scss
In order to remove bootstrap, the main hurdles left are the grid and container class usages. The idea of us removing our container usage throughout the site seems...unlikely. Copying the container classes instead (at least until after we actually remove bootstrap 3). Might need to do the same for grid.  Notable differences: 
for 1200px <= screen size width < 1400px, it's now 60px smaller.  
for screen width >= 1400px, it's now 120px wider (1320px, this is what i see on my desktop monitors which should be the same for most users/developers). This is in fact even larger than the search mockup (1275px)
So temporarily, most of the classes added are redundent until we actually remove bootstrap 3.
You may want to check this out and see for yourself. Most of our pages (search, …
> Add container classes

- src/app/loginComponents/onboarding/downloadcliclient/downloadcliclient.component.ts
This updates the install instructions for OpenJDK on Mac using homebrew. Complements #1342 which covered Mac install instructions for the OpenJDK-provided tarball.
**Issue**
dockstore/dockstore#4486
https://ucsc-cgl.atlassian.net/browse/DOCK-1925
> Fix OpenJDK installation instructions for Mac OS X homebrew

- cypress/integration/group2/categories.ts
- src/app/categories/button/category-button.component.scss
- src/app/categories/state/entry-categories.query.ts
- src/app/categories/state/entry-categories.service.ts
- src/app/categories/state/entry-categories.store.ts
- src/app/container/container.component.css
- src/app/container/container.component.html
- src/app/container/container.component.ts
- src/app/organizations/collection/state/add-entry.service.ts
- src/app/shared/entry.ts
- src/app/shared/modules/container.module.ts
- src/app/shared/modules/workflow.module.ts
- src/app/workflow/workflow.component.css
- src/app/workflow/workflow.component.html
- src/app/workflow/workflow.component.ts
- src/styles.scss
Third and final Categories PR of the initial UI implementation, which adds category buttons to the workflow and tool pages.  
The appearance is pretty close to the mockups, except that the indentation of the button row is similar to the existing "Last Modified" text directly above, so it matches.   It looked funny otherwise.
**Update: the below has been edited to reflect a new approach @ 2021/Nov/19 3:35pm PST**
To avoid a race condition bug, `EntryCategoriesService.updateEntryCategories()` is implemented slightly differently than other similar existing methods.  Before the HTTP request, the current update subscription (if it exists) is unsubscribed, and then set to the subscription for the new HTTP request.  This avoids the case where the updates for entry A and B …
> Feature/dock 1765/entry page category buttons

- src/app/home-page/home-logged-out/home.component.html
Corrects the references to the icon svgs in the "browse popular categories" portion of the logged-out home page.  It worked locally, but malfunctions on dev. 
**Issue**
broadly related to DOCK-1765
> correct category homepage icon image references

- src/app/search/basic-search/basic-search.component.html
A previous PR increased width of the containers globally across the site which introduced an oddity in the search term input
**Issue**
Adhoc issue
> Fix search term input size

- src/app/container/view/view.component.html
- src/app/container/view/view.component.ts
Prevents the user from deleting a tool's default tag.
The referenced issue noted that the user received no feedback when an attempting to delete the default tag (which is not allowed) failed on the webservice.  This PR implements some UI feedback via the alert service.
However, that's a band-aid fix, because the UI should simply not give the user the option to delete the default tag.
To that end, this PR disables the "Delete" button if the tag is the default tag, using the same disable code as the "Set as Default Version" button directly below it.
I user tested both the "notice" change, and then the "disable delete" change.  The latter makes a code path through the former very rare.
I can write integration tests for either, but IMHO, my time is better invested elsewhere. …
> DOCK-1958: Disable delete menu option for default tag, inform on tag deletion error

- package.json
Nightly tests failed because the CircleCI artifacts expired and don't exist anymore. Updating the CircleCI artifacts to the most recent develop build
**Issue**
n/a
> Update circleci artifacts

- cypress/integration/group2/mytools.ts
- cypress/integration/group2/myworkflows.ts
- package.json
- src/app/container/info-tab/info-tab.component.html
- src/app/container/info-tab/info-tab.component.ts
- src/app/container/info-tab/info-tab.service.ts
- src/app/search/query-builder.service.ts
- src/app/search/search-tool-table/search-tool-table.component.html
- src/app/search/search-workflow-table/search-workflow-table.component.html
- src/app/search/search-workflow-table/search-workflow-table.component.scss
- src/app/shared/container.service.ts
- src/app/shared/state/workflow.service.ts
- src/app/workflow/info-tab/info-tab.component.html
- src/app/workflow/info-tab/info-tab.component.ts
- src/app/workflow/info-tab/info-tab.service.ts
- src/styles.scss
Add topic sentence display to workflow information card. Also add the ability to update it (like workflow path).
Forgot to mention...it's slightly different than existing info tab buttons and such because it's closer to mocks. Presumably the rest of the info tab is converted to the mock ups before the next release.
Soon to be replaced by phase 2
**Issue**
For SEAB-3656
> Feature/seab 3656/topic sentence

- src/app/search/state/search.service.ts
This PR moves the category search facet from the middle to the top of the search sidebar, per our mockups.
**NOTE TO TESTER: make sure you have created a category with at least one entry in it, or the category search facet will not appear.**
**Issue**
https://ucsc-cgl.atlassian.net/browse/SEAB-3799
> move category search facet to top of sidebar

- src/app/organizations/collections/collections.component.html
- src/app/organizations/collections/create-collection/create-collection.component.html
- src/app/organizations/collections/create-collection/create-collection.component.ts
- src/app/organizations/collections/state/create-collection.query.ts
- src/app/organizations/collections/state/create-collection.service.ts
- src/app/organizations/collections/state/create-collection.store.ts
This PR prevents a click on the "edit collection" button from propagating to the parent collection summary, which triggered the page to change to the collection page behind the "edit collection" dialog.  Fix is similar to that used to prevent the same type of problem on the "remove entry from collection" button.
Also, implemented the "nice to have" goal: in the "edit collection" dialog, changed the save button label from "Edit Collection" to "Save".
**Issue**
https://ucsc-cgl.atlassian.net/browse/DOCK-1756
https://github.com/dockstore/dockstore/issues/4166
**Screenshot**
> prevent edit collection click event from propagating to parent

- src/app/containers/list/list.component.html
- src/app/search/search-tool-table/search-tool-table.component.html
- src/app/search/search-workflow-table/search-workflow-table.component.html
- src/app/shared/styles/entry-table.scss
- src/app/workflow/info-tab/info-tab.component.css
- src/app/workflow/info-tab/info-tab.component.html
- src/app/workflow/versions/versions.component.css
- src/app/workflows/list/list.component.html
- src/styles.scss
Added padding to the columns and set a max-width for the name column and a fixed width for the ORCID id column. Also hid some of the columns if the screen size was small.
Screenshots of the Authors table for public workflows:
Screenshots of hidden columns:
Notes:
- The padding was being set in specific component styling sheets, so I moved it to the global sheet to reduce duplication. 
- I also made the no multi-line headers style global and while I was checking all the tables on the site, I noticed this style made the Project Links column in search table weird so I changed the column name to Links (which is used by the [new design](https://app.zeplin.io/project/5fc690a2717ee9144814f190/screen/5fc7ceb4fd8d340926d62d6d))
- Old: ![Screenshot 2022-01-18 at 10-07-10 Dockstore …
> Fix authors table columns

- src/app/container/container.component.html
- src/app/container/info-tab/info-tab.component.html
- src/app/workflow/info-tab/info-tab.component.html
- src/app/workflow/workflow.component.html
Replacing hyperlinked trailing spaces with non-hyperlinked non-breaking spaces
**Issue**
https://ucsc-cgl.atlassian.net/browse/DOCK-2007
> remove trailing hyperlink underlines

- src/app/search/search-tool-table/search-tool-table.component.html
- src/app/search/search-workflow-table/search-workflow-table.component.html
The default mat-cell uses flexLayout="row". Previously it was overriden to "row wrap" which appear to work for all cases. Turns out, there was an issue with a very short topic + very short entry path. 
Circumventing the flexLayout by putting everything inside in a single div
**Issue**
Fix for issue discovered from previous SEAB-3698 PR
> Fix short search topic

- .circleci/config.yml
- .gitallowed
- src/app/container/launch/launch.component.ts
Reduce the number of changeDescriptor calls from 3 or 4 to 1 or 2 using behavior subjects and combineLatest with an odd trick (debounceTime(0)). Downside of this PR is that it introduces 3 new behavior subjects which is kind of duplicating values
Not entirely sure if it's even worth doing.
**Issue**
dockstore/dockstore#4194
> Reduce changeDescriptor calls

- src/app/workflow/workflow.component.ts
Again, couldn't really reproduce the flakiness of what the original ticket described, but this is a related bug nonetheless. The public tool page wasn't redirecting correctly to the home page if the tool was unpublished.
**Issue**
https://ucsc-cgl.atlassian.net/browse/DOCK-2038
> redirect correctly

- .circleci/config.yml
- src/app/container/info-tab/info-tab.component.html
- src/app/shared/entry/base-url.pipe.spec.ts
- src/app/shared/entry/base-url.pipe.ts
- src/app/shared/entry/entry.module.ts
- src/app/shared/markdown-wrapper/markdown-wrapper.component.spec.ts
- src/app/shared/markdown-wrapper/markdown-wrapper.component.ts
- src/app/workflow/info-tab/info-tab.component.html
This PR fixes the relative links displayed in an entry's README description by specifying a base URL for relative links. 
ngx-markdown allows options like `baseUrl` (prefix url for relative links) to be specified as [MarkedOptions](https://github.com/jfcere/ngx-markdown#markedoptions). However, MarkedOptions is meant to be defined globally, which isn't ideal for us because relative links only really show up in README descriptions and not in other places where we use markdown. Setting it globally also prevents us from changing the base URL dynamically based on entry repo.
Found a work-around by passing in MarkedOptions in the MarkDownService's `compile` method, which we already use. My PR only specifies base URLs for tool and workflow descriptions.
I found that GitLab and …
> Fix relative links in README descriptions

- cypress/integration/group2/githubAppTools.ts
- cypress/integration/group2/myworkflows.ts
- src/app/workflow/version-modal/version-modal.component.ts
- src/app/workflow/version-modal/version-modal.service.spec.ts
- src/app/workflow/version-modal/version-modal.service.ts
The version table wasn't updating before after hiding/unhiding a version for workflows in general. This fixes that.
**Issue**
https://ucsc-cgl.atlassian.net/browse/SEAB-3847
> Hiding a version should show on table without refreshing page

- src/app/workflow/launch-third-party/launch-third-party.component.ts
Fixes the enabling/disabling of the "launch" buttons on the right side of the workflow page, by replacing the `share` with a `shareReplay` call, which makes the multiple observables that depend on the `hasContent$` observable work correctly.
**Issue**
https://ucsc-cgl.atlassian.net/browse/DOCK-1891
dockstore/dockstore#4423
> disable launch buttons correctly

- src/app/loginComponents/accounts/accounts.component.ts
A fix suggested by LGTM to avoid missing other `&` in the parameters.
**Issue**
https://ucsc-cgl.atlassian.net/browse/SEAB-3876
> LGTM fix - Use regex replaceAll until EC2021

- src/styles.scss
When working on my search sidebar ticket I noticed something strange about the fonts used on Dockstore... according to styles.scss we're supposed to be using Roboto as our primary font, but after some investigation I realized that we're actually not.  There isn't an import for the Roboto font family specified anywhere in our repository, so Dockstore has been rendering with fallback fonts for probably this entire time.
Depending on your operating system, with use of inspect you can find that for these fonts have been used as fallbacks:
* **Ubuntu:** Liberation Sans (3rd fallback: default sans serif font)
* **Windows:** Arial (3rd fallback: default sans serif font)
* **Mac:** Helvetica Neue (2nd fallback)
Its pretty inconsistent and also doesn't match Zeplin which calls  for …
> Global import of Roboto font family

- src/app/starredentries/starredentries.component.html
This PR adapts the starred tools tab to properly handle apptools.  Before this PR, any apptools returned by the `getStarredTools` endpoint were misformatted (see "Before PR" screenshot below).  The basic concept here is that the apptool summary boxes are rendered with an adapted version of the workflow summary box rendering code.  Please check the workflow template to make sure I found all of the stuff that needs to be rendered conditionally.
The entryType is not included with each tool returned by `getStarredTools`, so I use `mode == 'DOCKSTORE_YML'` to differentiate apptools from normal tools, which Denis advises is correct.
The diffs look big, but most of the action is moving the tool and workflow rendering code into templates.
**Issue** …
> Feature/seab 4040/fix starred page for apptools

- package.json
- src/app/home-page/recent-events/recent-events.component.html
- src/app/home-page/recent-events/recent-events.component.ts
Adds UI support for github app tools (pretty ugly though) 
Also publishing and unpublishing events because I got confused as to why they weren't showing up
Blocks on https://github.com/dockstore/dockstore/pull/4778
**Issue**
https://ucsc-cgl.atlassian.net/browse/SEAB-4041
https://ucsc-cgl.atlassian.net/browse/SEAB-3787
> recent activity update for apptools and publishing/unpublishing

- .circleci/config.yml
- cypress/integration/smokeTests/sharedTests/auth-tests.ts
- package.json
- scripts/run-webservice-script.sh
This PR introduces staging tests to the nightly CI job. The current auth smoke tests do not function against prod, but do against dev and staging. After the release is complete, the smoke tests should work everywhere, and the prod tests can be turned on.
Working dev auth tests: https://app.circleci.com/pipelines/github/dockstore/dockstore-ui2/7371/workflows/dd3967ca-4b86-40f0-9dff-d039f13ef6e6/jobs/25898
Working staging auth tests: https://app.circleci.com/pipelines/github/dockstore/dockstore-ui2/7371/workflows/dd3967ca-4b86-40f0-9dff-d039f13ef6e6/jobs/25897
Setup process (doesn't need to be repeated, just documenting):
1. The user `DockstoreTestUser4` was added to each stage manually.
2. Registered this workflow: …
> Smoke tests structure for staging and prod

- cypress/integration/group2/githubAppTools.ts
- package.json
- src/app/app.routing.ts
- src/app/entry/router-link.pipe.spec.ts
- src/app/entry/router-link.pipe.ts
- src/app/shared/modules/list-workflows.module.ts
- src/app/shared/pipe/pipe.module.ts
- src/app/shared/session/session.query.ts
- src/app/sitemap/sitemap.component.html
- src/app/test/openapi-mocked-objects.ts
- src/app/workflows/apptools/apptools.module.ts
- src/app/workflows/apptools/apptools.routing.ts
- src/app/workflows/list/list.component.html
- src/app/workflows/list/list.component.ts
- src/app/workflows/list/published-workflows.datasource.ts
Add browse view of app tools.
This makes the term "App tool" sort of public, but this is a fallback UI if ES is not working, and it page is not linked to directly on the main Dockstore pages (there is a link to it on the sitemap).
**Issue**
[SEAB-4047](https://ucsc-cgl.atlassian.net/browse/SEAB-4047)
> Feature/seab 4047/published app tools

- src/app/home-page/home-logged-in/home-logged-in.component.html
- src/app/home-page/home-logged-in/home-logged-in.component.scss
So I added the my sidebar to the home/dashboard page as a final change on Friday and didn't to check for resizing… forgot to enclose all of the components into a new “row” `fxLayout` div. Went and updated that. Also added z-indexes so that the sidebar shadow can fall on top of the component next to it.
> My Sidebar for Homepage - Fixed Small Window Layout

- src/app/workflow/info-tab/info-tab.component.ts
- src/app/workflow/info-tab/info-tab.service.spec.ts
- src/app/workflow/info-tab/info-tab.service.ts
We were appending `tool` to the TRS ID, which we shouldn't.
I could have gone for a simpler fix, but tried to cut down on duplication.
**Issue**
https://ucsc-cgl.atlassian.net/browse/SEAB-3828
> Fix Copy TRS ID

- src/app/organizations/collections/create-collection/create-collection.component.html
- src/app/organizations/collections/state/create-collection.service.ts
This PR adds UI support for internal nonconsecutive dashes in collection/category names.  Basically, it's a regexp change and a tweak to the message which describes what's allowed.
**Issue**
https://ucsc-cgl.atlassian.net/browse/DOCK-2090
> Feature/dock 2090/support dashes in collection names

- src/app/organizations/events/events.component.scss
- src/app/organizations/organization-members/organization-members.component.html
- src/app/organizations/organization-members/organization-members.component.scss
- src/styles.scss
JIRA: [SEAB-2248](https://ucsc-cgl.atlassian.net/browse/SEAB-2284?atlOrigin=eyJpIjoiYjc1YjNhZDVkMjFhNDQ4OGFjZTZkYTBlODVjYTczMmQiLCJwIjoiaiJ9)
The purpose of this ticket is to update the organization members tab to match the redesign on [Zeplin](https://app.zeplin.io/project/5fc690a2717ee9144814f190/screen/60073fdcfd3287a25b5169a6), in particular, reformatting the cards into two columns.
**Without Changes:**
**With Changes:**
**And a single column when in mobile view:**
**Wrapping for long usernames and keep bubble in card:**
**Small changes to global "bubble" style to match Zeplin:**
* Tighter border radius and font weight change
**Updated mat-chip on " Organization Updates" to match the bubble style**
* There's no Zeplin page for this tab but I think it makes sense to …
> Align Organization Members in Columns

- cypress/integration/group2/githubAppTools.ts
- src/app/app.module.ts
- src/app/shared/entry/entry.module.ts
- src/app/shared/pipe/pipe.module.ts
- src/app/starredentries/starredentries.component.html
- src/app/starredentries/starredentries.component.ts
This PR changes the "starred" entry pages so that (up to) the first three lines of the formatted description is displayed with each workflow or app tool, rather than the full block of raw Markdown.
See https://ucsc-cgl.atlassian.net/browse/SEAB-4106 for the "before", and the screenshot below for the "after".
Note that the description that's displayed on the "starred" entry pages is the value of the "description" field of the entry object returned by the starred endpoint, which I believe corresponds to the value of the "description" column in the entry's table.  This is not necessarily the same as the description that is displayed in the info tab, which corresponds to the currently-selected version.  Many workflows have versions with descriptions, but no description is …
> nicely format starred app tool and workflow descriptions

- package.json
- src/app/container/container.component.html
- src/app/container/container.component.ts
- src/app/shared/entry.ts
- src/app/workflow/workflow.component.html
This PR changes the labels on tools to link to the search results for tools.  Not much else to add, it does what it says.
This PR contains the cherrypick that allows it to build on CircleCI.
**Issue**
https://ucsc-cgl.atlassian.net/browse/DOCK-2024
> link tool labels to tool search results

- package.json
- src/app/shared/entry.ts
This PR improves the success message displayed when an entry is successfully published/unpublished.
A utility method that updates the version's file types was setting an obscure alertService snackbar message, which was being displayed upon success, overriding the "published successful" message.  This PR removes the intermediate message, and also removes the `simpleSuccess` call from the method (and another neighboring method), in the spirit of the "how to use the alert service" documentation: https://github.com/dockstore/dockstore-ui2/blob/ba49d9365ee90d45eb4a8b13a424227e7c63d9bc/src/app/shared/alert/state/alert.service.ts#L23
Here's the post-PR message for a successful publish:
This PR contains the cherrypick that allows it to build on CircleCI.
**Issue** …
> improve success message on publish/unpublish

- .circleci/config.yml
- cypress/support/commands.ts
- package.json
- scripts/generate-openapi-script.sh
- scripts/get-circleci-artifact-url.sh
- scripts/run-webservice-script.sh
This PR fixes the failure to retrieve CircleCI artifacts. They're not missing from CircleCI (can see them in the Artifacts URL of a CircleCI build). The problem is that the artifact download URL changed after this [build](https://app.circleci.com/pipelines/github/dockstore/dockstore/7435/workflows/b025395e-4a6e-4c55-a449-62226dc54729/jobs/18239).
- Old URL: `https://18239-33383826-gh.circle-artifacts.com/0/tmp/artifacts/dockstore-webservice-1.13.0-SNAPSHOT.jar`
- New URL: `https://output.circle-artifacts.com/output/job/94cd379a-e46a-4a0a-b24e-0a644c192a5d/artifacts/0/tmp/artifacts/dockstore-webservice-1.13.0-SNAPSHOT.jar`
This [discuss topic](https://discuss.circleci.com/t/artifact-urls-now-private/43282) has people who ran into this change as well and a [CircleCI employee …
> Fix CircleCI artifacts URL

- .github/workflows/update_license.yml
This PR adds a GitHub action that is triggered on a push event for branches that begin with `dependabot/`, updates the license file, and pushes the changes if there are any.
From [dependabot docs](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#pull-request-branch-nameseparator):
> Dependabot generates a branch for each pull request. Each branch name includes dependabot, and the package manager and dependency that are updated. By default, these parts are separated by a `/` symbol, for example: `dependabot/npm_and_yarn/next_js/acorn-6.4.1`.
If you happen to create a branch that starts with `dependabot/` then this action will run, but it's probably unlikely to happen since we use hubflow.
A git …
> Add GitHub Action for updating license file for dependabot branches

- .github/workflows/update_license.yml
Tried running the update license GItHub action for a Dependabot branch and it [failed](https://github.com/dockstore/dockstore-ui2/runs/6278398811?check_suite_focus=true). Turns out workflows triggered by Dependabot use a [read-only `GITHUB_TOKEN` by default](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#responding-to-events) so the workflow couldn't commit the change. If we manually re-run the failed Dependabot workflow, then it'll work because it'll use a [read-write token](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#manually-re-running-a-workflow). 
It's not really ideal to manually re-run it, so this PR increases the …
> Add contents write permissions for update license GitHub Action

- .github/dependabot.yml
Number of updates a bit overwhelming, limiting it to security updates for now
**Issue**
n/a
> limit dependabot to security updates for now

- src/app/myworkflows/sidebar-accordion/github-apps-logs/github-apps-logs.component.html
- src/app/myworkflows/sidebar-accordion/github-apps-logs/github-apps-logs.component.scss
This PR changes the UI so that newlines in the github apps log messages are formatted as newlines, rather than whitespace.  The log message style is changed so it preserves whitespace and is rendered in a small, monospace font, with a tighter-than-usual line height to fit more output in the available space.  The formatting is similar to how the message might look if it was within a `<pre>` tag.
These changes will improve the readability of multiline messages, and preserve the formatting of useful, preformatted messages, such as [some of] those that emerge via exceptions from deep in the YAML parser.
This PR was motivated by Kathy's review ticket feedback, combined with my earlier realization that it was The Right Thing to Do.
**Issue** …
> DOCK-2105: Render newlines in GitHub app log messages

- src/app/footer/footer.component.html
Original JIRA ticket asked for adding the link to two places (docs.dockstore.org and dockstore.org) but the docs page already has it in the ToC sidebar. New link is only added to the dockstore.org footer under Help Resources.
**Issue**
[JIRA DOCK-2072](https://ucsc-cgl.atlassian.net/browse/DOCK-2072)
> [DOCK-2072] Add blog link to footer of dockstore.org

- src/app/notifications/notifications.component.scss
A previous change caused the notification bar to not extend the full width, now this PR should change it back to fitting the entire width.
**Issue**
[DOCK-2115](https://ucsc-cgl.atlassian.net/browse/DOCK-2115)
> Fix notification bar styling

- src/app/stargazers/stargazers.component.html
The change of font caused the original defined font-size to be too small, increased font size by a bit (0.1em) to match prod.
**Issue**
[DOCK-2146](https://ucsc-cgl.atlassian.net/browse/DOCK-2146)
> Fix ORCID ID font size

- cypress/integration/group3/githubAppTools.ts
- cypress/support/commands.ts
Added some `cy.wait()`s to fix that flaky ui2 test, which was due to the DOM changing during the test, detaching the element we were about to `click()` on.   Before this change, the test was failing about 50% of the time.  I ran this fix four times in a row on CircleCI with no failures, so it's probably done.
This took me a bit longer to solve than it would have if I'd first examined the Cypress "Recorded Run" page, available at the end of the logs in the "Test" step of the CircleCI run:
https://dashboard.cypress.io/projects/1ya4vj/runs/23089
All of the relevant information is available in one place, letting you get to the root of the problem quickly.
**Issue**
https://ucsc-cgl.atlassian.net/browse/SEAB-4344
Please make sure that you've checked the following before …
> Feature/seab 4344/fix flaky apptool test

- src/app/workflow/info-tab/info-tab.component.html
There was a bug that caused the "Restub" button to overlap with the Mode text when viewing workflow information of a full and unpublished workflow.
**Issue**
[GitHub issue](https://github.com/dockstore/dockstore/issues/4761)
[JIRA ticket](https://ucsc-cgl.atlassian.net/browse/DOCK-2086)
> Fix "Restub" button overlapping with mode in Workflow Information

- .circleci/config.yml
- cypress/integration/smokeTests/sharedTests/auth-tests.ts
This PR makes it so that the nightly tests always report their outcomes to slack (before they only reported when they failed).
This PR also updated config.yml so that it uses the slack orb `circleci/slack@4.4.4` instead of `circleci/slack@3.4.2`. 
**Issue**
[SEAB-4301](https://ucsc-cgl.atlassian.net/browse/SEAB-4301?atlOrigin=eyJpIjoiYmYwN2JlYmQ3ZWVjNDQyZGI0MmJkY2E2NTBkODU0NjUiLCJwIjoiaiJ9) 
> Feature/seab 4301/reporting nightly tests

- cypress/integration/smokeTests/sharedTests/auth-tests.ts
A smoke test to check hiding versions was disabled in this [pull request](https://github.com/dockstore/dockstore-ui2/pull/1050), however the issue that caused this test to fail has been fixed on the backend.
This PR re-enables the test.
**Issue**
[DOCK-1585](https://ucsc-cgl.atlassian.net/browse/DOCK-1585)
https://github.com/dockstore/dockstore/issues/3816
> re-enabled test in auth-tests.ts

- package.json
- src/app/organizations/collection/collection.component.html
This PR uses the `mapFriendlyValue` pipe to display `gxformat2` as `Galaxy` for Galaxy workflows on a collection page. 
This PR also changes the `base_branch` in `package.json` to the hotfix branch so the CircleCI audit tests run against the hotfix branch instead of develop.
Before:
After:
**Issue**
dockstore/dockstore#4427
> Display gxformat2 as Galaxy on collections page

- src/app/home-page/recent-events/recent-events.component.html
- src/app/home-page/recent-events/recent-events.module.ts
On the new user page, the 'info' icon was not appearing correctly and was appearing as text instead under the activity bar. This was fixed by manually adding material-icon and mat-icon classes to the mat-icon element that should appear for it automatically but does not in this case. Unsure as to why it does not work here and would love to hear ideas/alternative solutions from other devs.
**Issue**
GitHub issue: [#4902](https://github.com/dockstore/dockstore/issues/4902)
Jira: [DOCK-2168](https://ucsc-cgl.atlassian.net/browse/DOCK-2168)
> Fix 'info' icon not appearing under Activity of user page

- .circleci/config.yml
This PR changes the name of the CI smoke tests such that they are a bit more intuitive.
**Issue**
A link to a github issue or SEAB- ticket (using that as a prefix)
> rename smoke tests

- src/app/mytools/my-tool/my-tool.component.html
If a user has tools, when the user tries to load their tools, in the process of loading them, they may see a message that says "You have not registered any tools" before they are fetched. This may be misleading for them. This fix adds a check to see if the page is still loading before presenting that message. Note that this bug was recreated only on 'coverbeck''s account.
**Issue**
GitHub Issue: [#4777](https://github.com/dockstore/dockstore/issues/4777)
JIRA ticket: [DOCK-2096](https://ucsc-cgl.atlassian.net/browse/DOCK-2096)
> My Tools temporarily show "No tools registered" when loading is not complete

- src/app/shared/entry-wizard/entry-wizard.component.ts
When creating a workflow from the "Quickly register remote workflows" step, the list of repositories are ordered case sensitively (uppercase repositories are listed at the top). This PR should remove case-sensitivity in sorting. 
**Issue**
GitHub issue: [#4583](https://github.com/dockstore/dockstore/issues/4583)
JIRA ticket: [DOCK-1993](https://ucsc-cgl.atlassian.net/browse/DOCK-1993)
> Remove case-sensitive sort for repositories

- .circleci/config.yml
- cypress/integration/smokeTests/sharedTests/auth-tests.ts
Makes it so that the night auth and nightly no_auth tests run at different times. This makes it so that it is easier to diagnose the problem when something goes wrong.
**Issue**
[SEAB-4406](https://ucsc-cgl.atlassian.net/browse/SEAB-4406)
> Feature/flynn/seab 4406/spread out timings of tests

- src/app/categories/state/entry-categories.service.ts
- src/app/container/container.component.ts
- src/app/organizations/collection/state/add-entry.service.ts
- src/app/shared/entry.ts
- src/app/workflow/workflow.component.ts
Removes fetching of categories for non-published entries. Attempting to request categories for a 
non-published workflow will currently result in a 400.
**Issue**
https://github.com/dockstore/dockstore/issues/4821
> Don't request categories for unpublished entries (dockstore/dockstore#4821)

- package.json
- src/app/organizations/organization-members/organization-members.component.html
- src/styles.scss
When viewing the organization's members page as an admin, there are too many buttons in one row, causing the UI to look very bunched and crowded. This PR proposes putting the edit/delete buttons that only appear for organization admins onto a separate row below, and removes the 'min-width' set for `bubble` type labels (admin/maintainer) which caused the maintainer label to overflow.
**Issue**
[SEAB-4362](https://ucsc-cgl.atlassian.net/browse/SEAB-4362)
> Organization members page has crowded UI

- src/app/organizations/organization-members/organization-members.component.html
As an admin of an organization, when looking at the members page, their own member card's edit and delete buttons are disabled however they do not appear as disabled. Since the icons are fixed in colour, I think it makes sense to not show the buttons at all in this case.
**Issue**
GitHub Issue [4963](https://github.com/dockstore/dockstore/issues/4963)
JIRA ticket: [DOCK-2188](https://ucsc-cgl.atlassian.net/browse/DOCK-2188)
> Fix disabled member edit/delete buttons do not look disabled

- src/app/navbar/navbar.component.html
Items in the navigation bar overlap when the window is sized down, narrowing it further sets it to a new row. Chrome does not have the overlapping issue, the solution is tested on both browser types and works as expected.
**Issue**
GitHub Issue [#4872](https://github.com/dockstore/dockstore/issues/4872)
JIRA: [DOCK-2149](https://github.com/dockstore/dockstore/issues/4872)
> Fix Navigation bar items overlap

- package.json
- src/app/shared/entry.ts
Currently labels displayed in the workflow use `href` instead of angular routing, causing the page to reload each time a label is clicked, this PR changes it to `router` instead. 
**Issue**
GitHub Issue [#4076](https://github.com/dockstore/dockstore/issues/4076)
JIRA ticket: [DOCK-1727](https://ucsc-cgl.atlassian.net/browse/DOCK-1727)
> Change Workflow 'Labels' to Angular routing

- cypress/integration/immutableDatabaseTests/titleTag.ts
- src/app/app.routing.ts
- src/app/shared/auth.guard.ts
- test/web.yml
Companion PRs:
- compose_setup: https://github.com/dockstore/compose_setup/pull/230
- webservice: https://github.com/dockstore/dockstore/pull/5031
I recommend reviewing the compose_setup PR first, then this PR, then the webservice PR for things to make the most sense.
This PR checks if the user is authenticated by calling the get logged in user endpoint before navigating to authenticated pages. In a multiple webservice scenario where a user might have two browsers open, if they delete their account in browser 1, then browser 2 will still think they're authenticated until the page is refreshed because the token store isn't cleared in browser 2. I believe this is what happened during my experiment in the ticket description. Adding this check to the AuthGuard ensures that a …
> Get logged in user during canActivate to check authentication

- src/app/home-page/home-logged-in/home-logged-in.component.html
After the dashboard URL was changed to '/dashboard', the 'Quick start', 'Accounts', and 'Starred' links brought you to the wrong links ('dashboard/...'). This PR updates the links to the working addresses.
**Issue**
[SEAB-4594](https://ucsc-cgl.atlassian.net/browse/SEAB-4594)
> Update the links in the dashboard

- src/app/search/advancedsearch/state/advanced-search.query.ts
Part of https://github.com/dockstore/dockstore/pull/5042 is a display issue
An exact phrase search should not be broken up when displayed in the UI
**Issue**
https://github.com/dockstore/dockstore/issues/4059
> fix display issue with exact phrase search

- src/app/workflow/launch-third-party/launch-third-party.component.html
- src/app/workflow/launch-third-party/multi-cloud-launch/multi-cloud-launch.component.html
This PR adds some `data-cy` attributes required for a second PR I'll make for this ticket. This PR is required as my tests will not run on `localhost:4200` in circleCI due to this line,
https://github.com/dockstore/dockstore-ui2/blob/e88cc80d0fc2dc2b15a126e265202e4eae16348d/cypress/integration/smokeTests/sharedTests/basic-enduser.ts#L173
So, what I will do is merge this PR into develop, then use the circleCI nightly test setup (slightly modified) to run my proposed test for this ticket to verify it is working as intended and then make another PR.
**Issue**
[DOCK-1810](https://ucsc-cgl.atlassian.net/browse/DOCK-1810)
https://github.com/dockstore/dockstore/issues/4278
> Feature/dock 1810/galaxy launch button test part 1

- src/app/mytools/my-tool/my-tool.component.ts
- src/app/mytools/mytools.service.ts
- src/app/myworkflows/my-workflow/my-workflow.component.ts
- src/app/myworkflows/myworkflows.service.spec.ts
- src/app/myworkflows/myworkflows.service.ts
- src/app/shared/myentries.service.ts
- src/app/shared/state/token.query.ts
- src/app/shared/state/token.service.ts
- src/app/shared/state/token.store.ts
- src/app/test/service-stubs.ts
Call `/users/registries/github.com/organizations` endpoint instead of `/users/github/organizations` and use it. Create empty `OrgWorkflowObject`s for orgs without repos.
The new endpoint is currently slow, but it's the right thing to do if we want to show the logs for all GitHub orgs.
I will also create a web service PR that:
1. Optimizes the endpoint -- I think I see a way
2. Only returns logs for repos that you have permissions to
3. Deletes the now unused endpoint.
Apologies for the first review I requested; I was initially going to break this into 2 PRs, but then realized it was easier to to repurpose the code making the call to the unused endpoint.
***Small Other Changes***
* Changed a constructor to protected in abstract class because WebStorm gave  a warning
* Did a …
> Show all GitHub orgs you have access to, even if there are no entries

- src/app/loginComponents/accounts/account-sidebar/account-sidebar.component.ts
- src/app/organizations/organization/organization-stargazers/organization-stargazers.component.ts
- src/app/shared/user/user.service.ts
- src/app/stargazers/stargazers.component.ts
- src/app/user-page/user-page.component.ts
UI counterpart to https://github.com/dockstore/dockstore/pull/5062
Most of this is a red herring, the stargazers page seems to only really be using avatarurls anyway (due to lazy loading of user profiles)
**Issue**
https://github.com/dockstore/dockstore/pull/5062
> what if no email

- src/app/search/facet-search/facet-search.pipe.ts
- src/app/search/search.component.html
- src/app/search/search.component.ts
Adds mores search boxes. 
Efficiency issue, should be more familiar with change detection than I am, does it make sense that `GetFacetSearchUpdatePipe` is being called for all facets even if only one facet is being typed-in/changed?
**Issue**
https://github.com/dockstore/dockstore/issues/2062
> add more search boxes

- src/app/container/info-tab/info-tab.component.html
- src/app/workflow/info-tab/info-tab.component.html
ui portion of following issue, disallows topic selected for hosted workflows since hosted workflows have no source control to pull topics from
**Issue**
https://github.com/dockstore/dockstore/issues/4591
> disable topic selected for hosted

- src/app/search/search.component.html
- src/app/search/search.component.ts
- src/app/search/state/search.service.ts
This PR addresses three bugs in the UI2 search interface:
1. The "quick click" bug, which occurred when toggling rapidly between the workflows and tools results.  The search code was updating the `checkboxMap` object, and the template was accessing it while it was not fully-formed.
2. A bug with the back button, which would not allow the user to move from more than one level down in the search to back past the root search page. 
3. An inconsistent setting of `searchMode`.  It should be `file`, rather than `File` (I think).
**Issue**
https://ucsc-cgl.atlassian.net/browse/DOCK-2012
#4619
> DOCK-2012: Fix the search "quick click" bug (and some other problems)

- src/app/workflow/permissions/permissions.component.ts
Stop never-ending indeterminate progress bar.
As long as there is an uncleared item, created by the
alertService.start, the progress bar will keep going.
**Issue**
#3975
> Stop never-ending indeterminate progress bar

- src/app/container/tool-file-editor/tool-file-editor.component.spec.ts
- src/app/container/tool-file-editor/tool-file-editor.component.ts
- src/app/shared/file-editing.ts
- src/app/workflow/workflow-file-editor/workflow-file-editor.component.spec.ts
- src/app/workflow/workflow-file-editor/workflow-file-editor.component.ts
The problem was that a deep copy was made initially, so the first
revert worked, but the first revert used a shallow copy, so the
original data ended up being modified.
Did a little extra cleanup, removing some `any` types, and specifying
the correct imports (openapi vs swagger).
Tried to create a integration test, but ACE Editor and Cypress is not
a happy combination; seems safe/obvious enough, and added a unit test.
**Issue**
dockstore/dockstore#3800
> Fix second revert not working in hosted workflows

- src/app/container/add-tag/add-tag.component.html
- src/app/container/add-tag/add-tag.component.ts
Problem was that we reinitialized the form before completing API
requests, and Angular will show errors, after editing has begun,
if an input is not valid (and empty is not valid).
Gary had left a question in the code about whether we should reinitialize the form. I think the answer is no. If action succeeds, the dialog goes away. If it fails, you have a chance to edit your values again, without having to re-enter from scratch. See screenshot (before this PR, all your inputs would be empty in the screenshot).
Finally, I noticed we never toggled editMode, and a couple of fields weren't even checking it. This will prevent the user from changing values while the requests are in flight.
Additional tests: it's tricky and I punted. It's hard to test for ephermal UI. There is an …
> Don't show input errors when adding a tag

- src/app/loginComponents/onboarding/downloadcliclient/downloadcliclient.component.ts
Adds a note for fallback when cwltool can't install using our provided method.
**Issue**
https://ucsc-cgl.atlassian.net/browse/DOCK-2187
https://github.com/dockstore/dockstore/issues/4961
- [n/a] Do not use cookies, although this may change in the future
- [n/a] Do due diligence on new 3rd party libraries, checking for CVEs
- [n/a] Don't allow user-uploaded images to be served from the Dockstore domain
> Add note about fallback installation method

- cypress/integration/group2/myworkflows.ts
- src/app/workflow/info-tab/info-tab.component.html
- src/app/workflow/info-tab/info-tab.component.ts
- src/app/workflow/info-tab/info-tab.service.ts
Cancel workflow edit now reverts
It was sort of confusing, code-wise. See [this comment](https://github.com/dockstore/dockstore/issues/4592#issuecomment-1221073554) for details.
TLDR; There was a workflow object in InfoTabService that was being reverted, but the object wasn't being used by the component, so no reversion happened in the UI. So I removed the object entirely from the service to avoid confusion, and I do the revert in the component.
**Issue**
dockstore/dockstore#4592
> Cancel workflow edit now reverts

- src/app/workflow/version-modal/version-modal.component.html
- src/app/workflow/version-modal/version-modal.service.ts
When updating a workflow, we can't do it with one API request, we need to do it at least 2; one request for hidden and/or workflow path, then 1 or 2 more requests for adding/removing test parameter files. We were displaying the updating test parameter file success message last, which is what the user saw. Also, we displayed the updating test parameter files message, even if no request was made to update the test parameters.
The user shouldn't care about how many requests we are making underneath the hood, so now it's just a generic "Saving workflow version succeeded" message. I could have broken it apart, e.g., "Hiding version and adding one test parameter file", but it didn't seem worth the effort.
Also, if a refresh happens, a refresh message will be the last thing to …
> Show more generic message when updating workflow

- src/app/workflow/launch-third-party/multi-cloud-launch/multi-cloud-launch.component.html
- src/app/workflow/launch-third-party/multi-cloud-launch/multi-cloud-launch.component.spec.ts
- src/app/workflow/launch-third-party/multi-cloud-launch/multi-cloud-launch.component.ts
This PR:
- Adds `https://` to URLs that don't specify a protocol so `usegalaxy.ca` becomes `https://usegalaxy.ca`.
- Validates that the URL uses https. If it doesn't, the URL is considered invalid and a warning message is displayed.
- Removes the `href` attribute for the `Launch` button if the URL is invalid so the user isn't directed to that URL.
- Performs a truthy check on `url` so we only add new user cloud instances to the DB if the url was created successfully. Without this check, we could get an `undefined` error for invalid URLs.
**Issue**
[SEAB-3965](https://ucsc-cgl.atlassian.net/browse/SEAB-3965)
> Add https to custom multi-cloud launch URLs without a protocol

- cypress/integration/group2/myworkflows.ts
- cypress/integration/group3/mytools.ts
- cypress/integration/smokeTests/sharedTests/auth-tests.ts
- src/app/mytools/my-tool/my-tool.component.ts
- src/app/myworkflows/my-workflow/my-workflow.component.ts
The problem was that we now display your GitHub orgs even if you have no tools/workflows registered (so you can see the app logs). Now check also if there is a least one registered entry in one of the GitHub orgs.
Also restored commented out smoke test that this bug had broken.
**Issue**
dockstore/dockstore#5105
> Show user-friendly Add Tool/Workflow button

- src/app/loginComponents/requests/requests.component.html
Adds a newline to the organization description on a member invitation
**Issue**
DOCK-2196 (https://ucsc-cgl.atlassian.net/browse/DOCK-2196)
GitHub issue #5002  (https://github.com/dockstore/dockstore/issues/5002)
> Organization invitation newline fix

- package.json
- src/app/workflow/launch-third-party/multi-cloud-launch/multi-cloud-launch.component.spec.ts
- src/app/workflow/launch-third-party/multi-cloud-launch/multi-cloud-launch.component.ts
This PR fixes the bugs that Steve found while reviewing the ticket. Note that this is for 1.13. 
This PR:
- Constructs the https URL even if the user is logged out
- In `constructUrlWithHttpsProtocol`, returns the original url if it already contains the https protocol
**Issue**
[SEAB-3965](https://ucsc-cgl.atlassian.net/browse/SEAB-3965)
> Fix multi galaxy custom URL bugs

- cypress/integration/smokeTests/sharedTests/auth-tests.ts
- src/app/workflow/version-modal/version-modal.component.html
This PR adds a test for hiding and un-hiding workflow versions. This PR is incomplete and regrettably I won't be able to see it through, so I am leaving some comments.
**Issue**
[DOCK-2202](https://ucsc-cgl.atlassian.net/browse/DOCK-2202)
https://github.com/dockstore/dockstore/issues/5017
> Added in test for hiding version

- cypress/integration/group1/dashboard.ts
- cypress/support/commands.ts
- src/app/container/register-tool/register-tool.component.html
- src/app/home-page/widget/entry-box/entry-box.component.ts
- src/app/workflow/register-workflow-modal/register-workflow-modal.component.html
- test/web.yml
Fixes the github app link when registering  workflows, tools, and services on the new dashboard.
The changes specifically fixes the issue where the 'Manage Dockstore Installations on GitHub' button would redirect to the homepage instead of to github. This issue was caused due to the new dashboard not having an EntryType set in its session.
**Issue**
https://ucsc-cgl.atlassian.net/browse/DOCK-2239
https://github.com/dockstore/dockstore/issues/5123
> fixed github app link on new dashboard

- src/app/shared/entry.ts
Sometimes, the UI includes duplicate links to the discuss topic (post) from a workflow page. The source of the issue seems to be this code:
https://github.com/dockstore/dockstore-ui2/blob/4d77cfdea42ecd7d696b0b32eddccadde743f2eb/src/app/workflow/workflow.component.ts#L174
In some situations, it appears that the handler, which calls `discourseHelper` to add the link, is being invoked more than once for a given view of a workflow.  Alas, the invoked discourse embed script adds a link, rather than replacing the existing link if it exists, resulting in duplicates.
There is code in `discourseHelper` that attempts to remove the previous link.  However, multiple scripts may be in flight at once, and at removal time, a script from a previous call may not have generated its link …
> DOCK-2114: Fix Duplicate Links to Entry Discuss Topic

- src/app/container/container.component.html
- src/app/container/container.component.ts
- src/app/workflow/workflow.component.html
- src/app/workflow/workflow.component.ts
This PR changes the entry label editing interface so that its behavior is more natural.  Both issues mentioned in the ticket are fixed.
Part of problem stemmed from the `matChipInputAddOnBlur` = `true` setting, which caused a new chip (label) to be added when the chip list lost focus.  This setting, when there were no labels, for reasons that I was not able to determine, prevented the "save"/"cancel" button handler from being fired when the button was clicked.  It would also trigger unexpected behavior, like adding a partially-typed label when, for example, you had to click on another window to look up how to spell the rest of it.
I also fixed some code that was likely a bug - `undefined` should probably not be quoted in that `if` statement.
Please try this out, because if …
> DOCK-2061: Fix Weird Label Editing Behavior

- cypress/integration/group2/notificationBadge.ts
- cypress/support/commands.ts
- src/app/loginComponents/requests/organization-invite-confirm-dialog.html
- src/app/loginComponents/requests/organization-request-confirm-dialog.html
- src/app/navbar/navbar.component.html
- src/app/navbar/navbar.component.scss
- src/app/navbar/navbar.component.spec.ts
- src/app/navbar/navbar.component.ts
- src/app/organizations/registerOrganization/register-organization.component.html
Created a notification badge that links to their requests page. The badge will increment in count for organization invites, their rejected organizations, and any pending organization requests for admin/curators.
**Issue**
https://ucsc-cgl.atlassian.net/browse/DOCK-1918
https://github.com/dockstore/dockstore/issues/4477
When user has no notifications (no requests to approve , invitations, or rejected requests)
When a curator/admin has a organization request to approve
When a user has organization invitations
When a user has their organization request rejected
> added notification badge

- cypress/integration/group3/sidebarAccordion.ts
- cypress/support/commands.ts
- src/app/mytools/my-tool/my-tool.component.html
- src/app/mytools/my-tool/my-tool.component.ts
- src/app/myworkflows/my-workflow/my-workflow.component.html
- src/app/myworkflows/my-workflow/my-workflow.component.ts
- src/app/myworkflows/sidebar-accordion/sidebar-accordion.component.html
- src/app/myworkflows/sidebar-accordion/sidebar-accordion.component.ts
- src/app/shared-workflow-services/shared-workflow-services.module.ts
In both My Tools and My Services pages, the sidebar would show 'No published/unpublished workflows' instead of tools or services. 
Before fix:
After fix:
**Issue**
https://ucsc-cgl.atlassian.net/browse/DOCK-2255
> DOCK-2255 fixed bug in My Tools and My Services

- src/app/search/query-builder.service.ts
Note: Targeted for develop for now, but we could aim for a hotfix (upcoming one or the next) if preferred.
Set a size parameter to 0 in the request to get ES tagcloud aggregations. It's confusing, but the number of aggregations returned is based on a different size parameter. And the UI only looks at the `aggregations` portion of the response.
Recommendation from here: https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations.html#agg-caches
Locally, with a prod snapshot, it makes a huge difference -- the ES response has a [took property](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-search.html#search-api-response-body) that indicates how long it takes for ES to process the request, and it went from about 1 second to 1 …
> Set size of hits to 0 for tag cloud query

- src/app/home-page/widget/entry-box/entry-box.component.html
- src/app/home-page/widget/entry-box/entry-box.component.scss
- src/app/home-page/widget/entry-box/entry-box.component.ts
- src/materialColorScheme.scss
- src/styles.scss
Fixed some styling differences between the implemented entry widgets for the new dashboard on dev and the [zeplin mockup](https://app.zeplin.io/project/5fc690a2717ee9144814f190/screen/6022ab2d42df9f2c57c20982).
The number of entries label in each entry widget should have a color specific to the entry type (green for workflows, blue for tools, orange for services).
Before fix, they were all grey:
After fix:
Verify the implemented color match the zeplin mockup and that it correctly changes each bubble color.
**Issue**
https://ucsc-cgl.atlassian.net/browse/DOCK-2240
> DOCK-2240 Changed colors of each entry widget bubbles on new dashboard

- .github/dependabot.yml
automatically assign reviewers to dependabot tickets for better visibility
n/a
**Issue**
https://ucsc-cgl.atlassian.net/browse/SEAB-5002
https://github.blog/changelog/2020-07-15-assign-a-github-team-to-review-dependabot-pull-requests/
> assign reviewers [skip ci]

- src/app/footer/footer.component.ts
- src/app/footer/footer.service.spec.ts
- src/app/footer/footer.service.ts
This PR will now copy the domain when the Copy build info button is clicked. 
Before the fix, the Copy build info button copies all the build versions, but doesn't copy the domain, so you have to manually add the host/domain to that section of the issue.
Verify that the Copy build info button down at the footer now copies the domain as well.
**Issue**
https://github.com/dockstore/dockstore/issues/5015
https://ucsc-cgl.atlassian.net/browse/DOCK-2199
> DOCK-2199: Added domain onto the copy block on Copy build info button

- cypress/integration/group2/organizations.ts
- src/app/shared/twitter.service.ts
This PR fixes the broken twitter widget on the homepage of Dockstore.
The cause of this issue was due to the widget's width being set to `1px`. This PR overrides this value and sets the width to `100%`.
Before fix:
After fix: 
Verify that the twitter feed correctly shows on local following this change.
**Issue**
https://github.com/dockstore/dockstore/issues/5217
> DOCK-2271: fixed twitter widget width value

- cypress/integration/group2/organizations.ts
- src/app/home-page/widget/entry-box/entry-box.component.html
- src/styles.scss
This PR adds a "PREVIEW" button onto the new dashboard as shown in the zeplin mockups.
Before fix: 
After fix: 
Review the newly added bubble matches the zeplin mockup correctly
**Issue**
https://github.com/dockstore/dockstore/issues/5124
> DOCK-2240: added preview button

- src/app/search/query-builder.service.ts
- src/app/search/search.component.ts
Set the size of the sidebar query to 0. This will still return aggregations, which is all the UI processes, but it will not return the actual hits.
Since getSidebarQuery() is an aggregation query (see comment in search.component.ts two lines up from where it is invoked), rename the method to make that clearer.
Go to the search page and click the facets. Make sure it works in general, and that the numbers are specifically make sense.  Compare qa with prod, where the databases are fairly similar.
In addition, make sure the query is faster. The `took` field should probably be a single digit (see dockstore/dockstore#5257).
**Issue**
dockstore/dockstore#5257
> Don't requests hits for sidebar ES query

- .circleci/config.yml
PR #1658 broke s3 uploads. This fixes it, hopefully.
We require Node 18, which doesn't run on Ubuntu 18. The `cimg/python:2.7` image is an Ubuntu 18 image.
I couldn't find an Ubuntu 20 image for python 2.x, so upgrade so go to 3.11.
How this slipped through:
1. The audit CI step failed because it was running node18 against the develop branch CircleCI. To get this working would have required a one time fix (run audits against develop on with node16, but then switch back to node 18 after PR merged).
2. So I manually ran `npm audit` to verify that audits were better with the PR and merged
3. But, s3_upload only works if audits pass.
The s3_upload step in CircleCI should work.
**Issue**
None
Please make sure that you've checked the following before …
> Fix s3 upload

- cypress/integration/group3/githubAppTools.ts
- src/app/container/register-tool/register-tool.component.html
- src/app/container/register-tool/register-tool.component.ts
Recommend GitHub app registration for tools
GitHub apps is now the recommended tool (not just workflow) registration type.
Dialog box should work when trying different options
**Issue**
https://github.com/dockstore/dockstore/issues/4857
> re-order and recommend github apps for tools

- package.json
- scripts/get-circleci-artifact-url.sh
Updates to the latest web service.
Needed to update `get-circleci-artifact-url.sh` because of web service parallel unit test builds -- the openapi.yaml and swagger.yaml files are uploaded twice because of parallel builds; `https://circleci.com/api/v2/project/gh/dockstore/dockstore/${CIRCLECI_BUILD_ID}/artifacts` now returns two urls for each artifact. So convert the result to an array and grab the first one -- should continue to work even if we turn off parallel builds, or if we have enough tests and the artifacts are uploaded 3 times. 
The first (brief) attempt was to get rid of two uploads in the web service, but it didn't work; there were dependencies on the uploaded artifacts within the web service.
If it builds, it works.
**Issue**
No issue …
> Update to the latest web service

- cypress/integration/group1/checkerWorkflowFromTools.ts
- cypress/integration/group1/checkerWorkflowFromWorkflow.ts
- cypress/integration/group1/hostedTools.ts
- cypress/integration/group1/hostedWorkflows.ts
- cypress/integration/group2/aliases.ts
- cypress/integration/group2/myworkflows.ts
- cypress/integration/group2/organizations.ts
- cypress/integration/group2/sharedWorkflows.ts
- cypress/integration/group2/usernameChangeRequired.ts
- cypress/integration/group3/githubAppTools.ts
- cypress/integration/group3/mytools.ts
- cypress/integration/group3/sidebarAccordion.ts
- cypress/integration/group3/starErrorMessage.ts
- cypress/integration/immutableDatabaseTests/dropdown.ts
- cypress/integration/immutableDatabaseTests/newsUpdates.ts
- cypress/integration/immutableDatabaseTests/notifications.ts
- cypress/integration/immutableDatabaseTests/searchTable.ts
- cypress/integration/immutableDatabaseTests/toolDetails.ts
- cypress/integration/immutableDatabaseTests/tosAndPrivacyPolicy.ts
- cypress/integration/immutableDatabaseTests/verification.ts
- cypress/integration/immutableDatabaseTests/workflowDetails.ts
- cypress/integration/smokeTests/sharedTests/auth-tests.ts
`cy.route()` is deprecated in Cypress 8, the version we currently use, and no longer present in Cypress 12, the version we aspire to. `cy.server` is also deprecated in 8, gone in 12. If you use `cy.intercept`, you don't need `cy.server`.
This is the first step towards migrating to Cypress 12.
PR and smoke tests should be passing.
**Issue**
https://ucsc-cgl.atlassian.net/browse/SEAB-5091
> Replace cypress route() with intercept()

- .circleci/config.yml
Somehow missed this in the upgrade to Node 18, I guess because it's not a blocking check. We don't actually need Python 3.11 per se, we need an Ubuntu 20 image, which python 3.11 is based on.
If the check_build_develop build passes on Circle CI, it's good.
**Issue**
No issue created; cleanup on https://ucsc-cgl.atlassian.net/browse/SEAB-4852
**Security**
> Upgrade to Python 3.11 in check_build_develop

- .circleci/config.yml
Somewhat of a follow-up to https://github.com/dockstore/dockstore-ui2/pull/1676. That PR didn't fix the `Directory (/home/circleci/repo) you are trying to checkout to is not empty and not a git repository` failure for nightly no auth tests because the browser-tools were being installed twice. This PR removes the duplicate install and the nightly no auth tests pass now. Can see the passed tests [here](https://app.circleci.com/pipelines/github/dockstore/dockstore-ui2?branch=feature%2Ffix-no-auth-tests).
Nightly no auth tests should pass.
**Issue**
n/a
**Security**
Please make sure that you've checked the following before submitting your pull request. …
> Remove duplicate browser-tools install for nightly no auth tests

- package.json
- src/app/container/versions/versions.component.html
- src/app/workflow/versions/versions.component.html
A companion to dockstore/dockstore#5035 -- SourceFile language descriptor version is now in a nested SourceFileMetadata object.
Verify that that language descriptor versions show up correctly on the versions tab of workflows and tools.
**Issue**
https://ucsc-cgl.atlassian.net/browse/SEAB-5162
**Security**
> Handle backend change to for source file metadata

- src/app/changeUsernameBanner/changeUsernameBanner.component.html
- src/app/tosBanner/tos-banner.component.html
- src/styles.scss
At the time of addressing this ticket the "x" button to close the TOS banner is accesible on mobile but I noticed the text on the banner still gets cut off.
**Cut off text:**
**Solution:** change the banner height to fit the text and change the tos banner push.
I also noticed that updating the height also fixes the text cut off for the change-username-banner.
Remove your cookies to reveal the banner and ensure that the banner text isn't cut off when you resize to the smallest possible window size.
**Issue**
[DOCK-1780
](https://ucsc-cgl.atlassian.net/browse/DOCK-1780?atlOrigin=eyJpIjoiMTg2NzQ4NWI2OTA2NDcyMjhkNGExZmMzNTE5YTVkNDMiLCJwIjoiaiJ9)[github issue](https://github.com/dockstore/dockstore/issues/4223)
**Security**
Please make sure that you've …
> fix height of tos banner mobile

- THIRD-PARTY-LICENSES.csv
- cypress.config.ts
- cypress/e2e/group1/revokeDockstoreToken.ts
- cypress/e2e/group2/myworkflows.ts
- cypress/e2e/group2/notificationBadge.ts
- cypress/e2e/group2/organizations.ts
- cypress/e2e/group3/githubAppTools.ts
- cypress/e2e/immutableDatabaseTests/services.ts
- cypress/e2e/immutableDatabaseTests/toolsSearch.ts
- cypress/e2e/immutableDatabaseTests/workflowsSearch.ts
- cypress/e2e/smokeTests/sharedTests/auth-tests.ts
- cypress/e2e/smokeTests/sharedTests/basic-enduser.ts
- cypress/e2e/smokeTests/sharedTests/monitor.ts
- cypress/e2e/smokeTests/sharedTests/search.ts
- cypress/support/commands.ts
- package-lock.json
- package.json
- scripts/run-webservice-script.sh
Upgrade to Cypress 12.
The main migration issue is that in Cypress 12 tests are now isolated. This worked before:
```
it('Go to organizations page', () => {
cy.visit('/organizations');
});
it('Go to an org from organizations page', () => {
// Click UCSC org on /organizations page.
cy.get('UCSC').click();
});
```
The second `it` relies on the state of the first `it`, on the user being on the `/organizations` page.
This no longer works in Cypress 12. At the start of each `it`, you're not on a page, and your local storage/cookies have been cleared.
There are 2 possible fixes. Fix 1, add the `cy.visit()` to each `it`, and, if authorization needed, set the token as well.
```
it('Go to organizations page', () => {
cy.visit('/organizations');
});
it('Go to an org from …
```
> Feature/seab 5089/cypress12

- cypress/e2e/group2/myworkflows.ts
- src/app/workflow/info-tab/info-tab.component.html
- src/app/workflow/info-tab/info-tab.component.ts
This PR changes the Source Code link to point to the primary descriptor file instead of pointing to the root of the repo. Also, some workflows had very long paths so the text of the link was changed to only display the file name.
Verify the link is edited correctly
**Issue**
https://github.com/dockstore/dockstore/issues/5044
**Security**
> DOCK-2213: edit source code to link to primary descriptor

- src/app/shared/entry/register-checker-workflow/register-checker-workflow.component.html
Tooltip was sometimes covering the input during the integration tests, which led to a failure. I was able to reproduce intermittently locally, and unable to reproduce after this fix.
I picked position `after` because it's done fairly commonly already in the codebase.
If the tests pass, it's fixed the flakiness. But go to the Register Checker Workflow dialog, and verify the tooltip for each input is still visible.
**Issue**
https://ucsc-cgl.atlassian.net/browse/SEAB-5217
**Security**
> Change tooltip position to fix a flaky test

- src/app/file-tree/file-tree.component.ts
- src/app/source-file-tabs/source-file-tabs.component.html
- src/app/source-file-tabs/source-file-tabs.component.scss
This PR moves the primary descriptor indicator out of the dropdown. The badge is moved such that even if the file name is too long and truncated, the primary badge will still be shown. Also, this PR fixes the bug where the primary descriptor badge did not show in the file tree.
Before fix:
After fix:
Verify that the integration tests still pass and the primary descriptor badge is not visible in files with long names. Also verify that the primary badge is shown when opening the file tree.
**Issue**
https://github.com/dockstore/dockstore/issues/5321
**Security**
Please make sure that you've checked the following before submitting your pull request. …
> DOCK-2309: moved badge out of dropdown and fixed bug in file tree

- src/app/organizations/organizations/organizations.component.html
After hitting `enter` in the organization search box the form would clear, loosing the search results.  Small fix found [here](https://github.com/angular/angular/issues/12643#issuecomment-257620559) and now it behaves as expected.
**Left is QA and right is with changes:**
(Pretend that you can see I'm pressing `enter` after typing in "broad")
https://user-images.githubusercontent.com/97123241/217320548-a05f14a3-39b9-45e7-bc28-8d262a76235b.mp4
Test it out and ensure search doesn't clear after `enter`.
**Issue**
[DOCK-2308
](https://ucsc-cgl.atlassian.net/browse/DOCK-2308)[GitHub issue](https://github.com/dockstore/dockstore/issues/5318)
**Security** …
> Organization Search Clears After Enter - DOCK-2308

- src/app/navbar/navbar.component.ts
We were requesting the user's organization memberships even if not logged in. Don't do it any more.
I think there might be a more generic place for handling the logged out case, e.g., logging out could clear all user state data, but I'm going to pass on that.
1. Go to the home page
2. Log out if logged in
3. Open browser developer tools on network tab; clear network requests
4. Reload the page
5. Make sure there are no requests with 4xx responses.
**Issue**
dockstore/dockstore#2285
**Security**
> Don't make org membership requests if logged out

- angular.json
- cypress/e2e/smokeTests/sharedTests/basic-enduser.ts
- src/app/shared/code-editor/code-editor.component.ts
This PR has 3 fixes, the first one is the actual JIRA issue, the second one was blocking the first one, and the third one was noticed while investigating.
1. The `cy.wait()` in basic-enduser.ts seems to fix the import error causing flaky tests; hard to tell for sure with flaky bugs, but it worked for me 10 times in a row locally. My theory is that the new, faster Cypress 12 was clicking away from the editor while the editor was still synchronously downloading a JS file, and the aborted download caused the tests to fail.
2. PR #1704 broke smoke tests on qa only because it changed `svg` to `img` for the launch with images. Changed the selector to look for either `svg` or `img`, so it will run on both qa and staging/prod. Created a followup ticket, dockstore/dockstore#5372 to …
> Update smoke tests and Ace editor

- src/app/shared/code-editor/code-editor.component.ts
Follow up/fix to https://ucsc-cgl.atlassian.net/browse/SEAB-5240
The worker-json.js files were not being downloaded in qa, although they were in local tests. Because, in a deployment like qa, these files are served from gui.dockstore.org.
We need the ".." in front of the assets so that build in config.yml does the string substitution to add gui.dockstore.org.
1. Open browser developer tools
2. Go to search, select WDL facet
3. Click first workflow
4. Go to files, then click test parameter files
5. Check that worker-json.js file is downloaded correctly.
**Issue**
https://ucsc-cgl.atlassian.net/browse/SEAB-5240
**Security**
Please make sure that you've …
> Add ".." at beginning of workerPath

- cypress/e2e/smokeTests/sharedTests/basic-enduser.ts
Previously updated the smoke tests in this [pr](https://github.com/dockstore/dockstore-ui2/pull/1707/files#diff-0e83ac8adb043831f00e87fd557c3cbe8a82257c2ca3d5772e2a31d01dbc77feR110) to look for `Nextflow` instead of `NFL` since we switched to the friendly names, however the change in smoke test does not accommodate for staging/develop where these changes from develop are not present.  Updated the test to handle both cases of `NFL` and `Nextflow`, tested locally with `NFL` and `Nextflow` and appears to be passing well.
Added an additional note [here](https://github.com/dockstore/dockstore/issues/5372#issuecomment-1439116907) to remove the check for "NFL" after the 1.14 release.
**Issue**
SEAB-5269
**Security**
If there are any concerns that require …
> Fix Broken Smoke Test for Staging/Prod  - SEAB-5269

- src/app/search/search.component.html
- src/app/search/search.component.ts
- src/app/search/state/search.service.ts
- src/app/test/service-stubs.ts
Following the [mocks](https://app.zeplin.io/project/5fc690a2717ee9144814f190/screen/5fc690e874e0c807afeb299b), the search sidebar has a new default state in which about half of the panels are collapsed.  A nice little change which avoids that long scroll to the bottom of the page.  As Charles suggested in the [ticket](https://ucsc-cgl.atlassian.net/browse/DOCK-2317), the state of the panels is saved to local storage, so upon page reload or navigation, the panels that have been collapsed or expanded by the user is remembered.
The tools search looks identical, collapsed panels follow the tools search [mocks](https://app.zeplin.io/project/5fc690a2717ee9144814f190/screen/5fc7ceb4fd8d340926d62d6d):
| Workflows | Tools |
|:---:|:---:|
| …
> Collapse Search Panels - Dock 2317

- cypress/e2e/group1/checkerWorkflowFromTools.ts
- cypress/e2e/group2/myworkflows.ts
- cypress/e2e/group2/notificationBadge.ts
- cypress/e2e/immutableDatabaseTests/searchTable.ts
- cypress/e2e/immutableDatabaseTests/services.ts
- src/app/container/info-tab/info-tab.component.html
- src/app/loginComponents/accounts/controls/delete-account-dialog/delete-account-dialog.component.ts
- src/app/my-sidebar/my-sidebar.component.html
- src/app/myworkflows/my-workflow/my-workflow.component.ts
- src/app/organizations/collections/state/create-collection.service.ts
- src/app/organizations/registerOrganization/requireAccountsModal/require-accounts-modal.component.html
- src/app/search/state/search.service.spec.ts
- src/app/search/state/search.service.ts
- src/app/shared/entry-wizard/entry-wizard.component.ts
- src/app/shared/entry/descriptor-language.service.spec.ts
- src/app/shared/entry/register-checker-workflow/register-checker-workflow.component.ts
- src/app/shared/entry/verified-display/verified-display.component.ts
- src/app/shared/verified-by.service.ts
- src/app/test/service-stubs.ts
- src/app/workflow/dag/dag.component.ts
- src/app/workflow/register-workflow-modal/register-workflow-modal.component.html
- src/materialColorScheme.scss
- src/styles.scss
Description
This PR corrects a lot of typos found in this repo. This PR is very similar to https://github.com/dockstore/dockstore-cli/pull/227.
Review Instructions
Ensure that all of my corrections are valid (ie. I didn't replace a typo with a typo)
Issue
[DOCK-2325](https://ucsc-cgl.atlassian.net/browse/DOCK-2325)
https://github.com/dockstore/dockstore/issues/5365
(These issues aren't directly related to this work)
**Security**
[DOCK-2325]: https://ucsc-cgl.atlassian.net/browse/DOCK-2325?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Corrected typos in dockstore/dockstore-ui2

- src/styles.scss
Fixes a deprecation warning for use of scss imports with tildes. Trivial, but I believe it's gone, not deprecated, in the next version of Angular, so actually necessary.
I'd say mainly trust the compiler in this case, but you could look at the share (Facebook, Twitter, etc.) buttons on a public workflow page and make sure they look the same in QA and prod.
**Issue**
dockstore/dockstore#5364
**Security**
> Remove deprecated tildes in scss import

- src/app/container/container.component.html
- src/app/container/files/files.component.html
- src/app/home-page/new-dashboard/new-dashboard.component.html
- src/app/home-page/recent-events/recent-events.component.html
- src/app/loginComponents/requests/requests.component.html
- src/app/mytools/my-tool/my-tool.component.html
- src/app/myworkflows/my-workflow/my-workflow.component.html
- src/app/myworkflows/sidebar-accordion/github-apps-logs/github-apps-logs.component.html
- src/app/organizations/collection/add-entry/add-entry.component.html
- src/app/organizations/collection/collection.component.html
- src/app/organizations/collections/collections.component.html
- src/app/organizations/organization/organization.component.html
- src/app/organizations/organizations/organizations.component.html
- src/app/search/search.component.html
- src/app/shared/code-editor-list/code-editor-list.component.html
- src/app/stargazers/stargazers.component.html
- src/app/starredentries/starredentries.component.html
- src/app/workflow/info-tab/info-tab.component.html
- src/app/workflow/launch/launch.component.html
- src/app/workflow/workflow-file-editor/workflow-file-editor.component.html
- src/app/workflow/workflow.component.html
- src/materialColorScheme.scss
- src/styles.scss
Updates the blue `alert-info` banner style following the zeplin mock-ups and creates a new palette for `Accent 2` as defined [here](https://app.zeplin.io/project/5fc690a2717ee9144814f190/screen/5fc699d068c46f17551f745b).
New style has a blue border, light blue background and no box-shadow.
https://github.com/dockstore/dockstore-ui2/blob/cc245466e179fa7c0e80446f9f232fb26896854e/src/styles.scss#L1331-L1337
Zeplin mocks: [Dashboard](https://app.zeplin.io/project/5fc690a2717ee9144814f190/screen/60229885ad1715098caf03e5), [Starred](https://app.zeplin.io/project/5fc690a2717ee9144814f190/screen/602c3030c7ca5718b6e37c1c)
**Dashboard:**
**Before:**
**After:**
**Starred:**
**Before:**
**After:**
In this case, following the mocks, I removed the warning icon.
**Zeplin:**
**General:** …
> Updated Blue Banner Style

- package.json
- src/app/home-page/new-dashboard/new-dashboard.component.ts
- src/app/home-page/widget/entries/entries.component.html
- src/app/home-page/widget/entries/entries.component.ts
- src/app/home-page/widget/entry-box/entry-box.component.html
- src/app/home-page/widget/entry-box/entry-box.component.ts
This PR adjusts the UI for the extended type information (metadata) added to the openapi schema in https://github.com/dockstore/dockstore/pull/5403.
Two `EntryType`s are now defined: one in the schema (by the webservice), and the other by the UI code.  Eventually, we should probably completely replace the UI `EntryType` with the openapi `EntryType`, but until then, there will be occasional collisions.
The goal was to address these collisions with minimal changes, get the UI to build and run, and not break anything.  This PR makes none of the refactors that are enabled by the metadata, those will come later.
Ensure the UI builds, starts, and passes the tests.
**Issue**
https://ucsc-cgl.atlassian.net/browse/SEAB-5270
**Security**
If there are any …
> SEAB-5270: Ensure UI builds/runs with new entry type information

- src/app/search/map-friendly-values.pipe.ts
- src/app/search/state/search.service.ts
- src/app/shared/versions.ts
- src/app/workflow/info-tab/info-tab.component.html
- src/app/workflow/versions/versions.component.html
- src/app/workflow/versions/versions.component.ts
Adds an Open column to the versions table, and does corresponding renaming from Open Data to Open on the facets page.
***Background on the renaming***
* Initially, we were considering an open data version to be a workflow with a test parameter file with publicly accessible test data
* Now, we are considering an open version to be a version with publicly accessible test data, **OR**, a version that does not require any file inputs. The key point being that in both cases you don't need any additional permissions to run the version.
The versions table is getting crowded, although I think it might just be acceptable. Suggestions welcome.
Before:
After:
***Facets***
Before
After
Verify that the Open column appears on the versions table in both the public …
> Indicate open on versions table

- cypress/e2e/immutableDatabaseTests/services.ts
- src/app/github-callback/github-callback.service.spec.ts
- src/app/github-callback/github-callback.service.ts
- src/app/mytools/mytools.service.ts
- src/app/myworkflows/myworkflows.service.ts
- src/app/shared/feature.service.ts
- src/app/shared/myentries.service.ts
- src/app/shared/session/session.query.ts
The problem in the issue was that the My Workflows accordion changes after refreshing the page. I couldn't reproduce this locally or on QA.
I tried to fix other "refresh"/redirection problems that didn't align with the desired behaviour of this ticket, which was to return to the previous state the user was in after an action. 
This PR changes the behaviour of two scenarios:
1) When managing GItHub App installations on My Workflows, after the user clicks Save on GitHub, they're now redirected to the page they were previously on. If they were viewing a specific workflow, they would be redirected there. If they were on the new dashboard (which allows workflow registration), they would be directed back to the dashboard.
The following videos demonstrate the old and new GitHub …
> Redirect to same workflow after refresh if possible

- src/app/workflow/view/view.component.html
By default, the tooltip is positioned below the button. In the Actions menu, this can block other buttons. This PR sets the position of the tooltip to the left of the buttons in the Actions menu dropdown so that none of the tooltips are preventing users from pressing buttons under them. 
Before:
https://user-images.githubusercontent.com/25287123/223879359-5618a084-553b-44a4-aba0-58c7de28fc70.mp4
After:
https://user-images.githubusercontent.com/25287123/223879374-acfaf7b4-0a6b-46e7-b3a0-33bece08ab6d.mp4 
On QA,
- Go to My Workflows and click on a workflow with more than one valid version (so that there's the option to snapshot). If the version is a tag, even better because the Actions menu dropdown for the version will have options to Snapshot, …
> Position tooltip to the left in Actions menu dropdown

- cypress/e2e/group3/mytools.ts
- src/app/mytools/my-tool/my-tool.component.html
- src/app/mytools/my-tool/my-tool.component.ts
- src/app/myworkflows/my-workflow/my-workflow.component.ts
- src/app/shared/user/user.service.ts
- src/styles.scss
Essentially copies the `Discover Existing Dockstore Workflows` button and adds it to the my-tools page as the `Discover Existing Dockstore Tools`  button to add existing GitHub App Tools from your organization.
**Wording preference:** Any preference to update the text on the `Discover Existing Dockstore Workflows` button (and new tools button) to match the mocks or keep it as is? The tooltip has the updated text but the button itself is simplified:
| Current | Mocks |
|:---:|:---:|
| ![image](https://user-images.githubusercontent.com/97123241/224777594-9a72b4af-cd45-40e3-ba75-062e6ad60f71.png) | ![image](https://user-images.githubusercontent.com/97123241/224775475-25402d68-b345-4ce0-9959-9fb50ebdd2dd.png) |
Check that button exists and succeeds when …
> Add Discover Existing Tools Button - DOCK-2269

- src/app/app.module.ts
- src/app/entry/type-metadata/entry-type-metadata.service.spec.ts
- src/app/entry/type-metadata/entry-type-metadata.service.ts
This PR modifies the UI to read metadata about each entry type (in the form of a list of `EntryTypeMetadata`) from the webservice at startup, and provides a new `Injectable` service `EntryTypeMetadataService` with methods to get the full list or the metadata for a particular entry type.
The new Service handles a load failure in the same manner as the current `ConfigurationService`, which means that it basically ignores it.  From what I gather from reading the source, the assumption is that soon afterwards, when the `FooterComponent` is rendered, if the server is down, the footer's TRS request will fail, and from there, we'll "redirect" to the `/maintenance` page.
This works if the server is actually down for the entire UI initialization process.  But, if requests are …
> SEAB-5307: Retrieve entry type metadata at startup

- scripts/get-circleci-artifact-url.sh
UI builds have been failing because of the CircleCI artifacts script. This PR fixes the script by adding an empty `Circle-Token` header to the `curl` that the script makes to get the artifacts. 
The [docs](https://circleci.com/docs/api-developers-guide/#authentication-and-authorization) say that the API uses token-based authentication to manage access to the API server. Maybe they recently changed something so now the header is required :thinking:. The `getArtifacts` example [here](https://circleci.com/docs/api-developers-guide/#download-artifacts) also has the `Circle-Token` header. I just made the value an empty string and I think it works because the dockstore/dockstore project is public.
**EDIT:** accessibility_test_base runs the develop version of the script which …
> Fix CircleCI artifacts script

- cypress/e2e/group2/categories.ts
- cypress/e2e/group2/organizations.ts
- cypress/support/commands.ts
- package.json
- src/app/categories/button/category-button.component.html
- src/app/entry/current-collections/current-collections.component.html
- src/app/organizations/collection/add-entry/add-entry.component.html
This PR verifies that notebooks can be added onto collections/categories.
Verify that the new tests pass
**Issue**
https://ucsc-cgl.atlassian.net/browse/SEAB-5123
**Security**
> SEAB-5123: Verify notebooks can be added to collections/categories

- scripts/get-circleci-artifact-url.sh
This reverts commit b90bdc2d01fd5604bfb20e472dc36fce857106eb.
Did circle ci change behaviour again?
n/a
**Issue**
n/a
**Security**
> Revert "Add CircleToken header (#1734)"

- package.json
- scripts/get-circleci-artifact-url.sh
- src/app/container/info-tab/info-tab.component.html
- src/app/home-page/new-dashboard/new-dashboard.component.ts
- src/app/home-page/recent-events/recent-events.component.html
- src/app/home-page/recent-events/recent-events.component.ts
- src/app/home-page/widget/entry-box/entry-box.component.html
- src/app/home-page/widget/news-box/news-box.component.html
- src/app/home-page/widget/organization-box/my-organizations-dialog.component/my-organizations-dialog.component.html
- src/app/home-page/widget/organization-box/organization-box.component.html
- src/app/home-page/widget/starred-box/starred-box.component.html
- src/app/loginComponents/accounts/external/accounts.component.html
- src/app/mytools/my-tool/my-tool.component.ts
- src/app/shared/entry/recent-events.pipe.ts
- src/app/starredentries/starredentries.component.html
- src/app/starredentries/starredentries.component.scss
- src/app/user-page/user-page.component.html
- src/app/workflow/info-tab/info-tab.component.html
- src/styles.scss
Implements feedback following Dashboard [usability](https://docs.google.com/document/d/14QnlN-dL3bebsczPo-IAt8s2RNB1mASm2Licf43tA50/edit?usp=sharing) tests:
- Hide user avatar for admin/curator that approved/rejected an organization since we also don't display their name:
<p align=center>
</p>
- Provide link to invited user with org invitation events:
<p align=center>
</p>
- Use the collection `displayName` instead of just collection `name`:
<p align=center>
</p>
- Add missing period to `You are not in any organizations.`:
<p align=center>
</p>
- Add tool-tips to Pending Requests and Pending Invitations to provide more meaning:
- `Pending Request` - "See organizations you have created that are pending approval."
- `Pending Invitations` - "Accept and decline invitations to …
> Dashboard Usability Fixes - SEAB-5348

- src/app/organizations/collection/collection.component.html
- src/app/organizations/collection/collection.component.ts
While reviewing notebooks in collections, noticed header could be better
Test new header with notebooks on (and off)
**Issue**
https://ucsc-cgl.atlassian.net/browse/SEAB-5123
**Security**
> conditional header

- src/app/containers/list/list.component.html
- src/app/search/search-results/search-results.component.html
- src/app/search/search-results/search-results.component.scss
- src/app/search/search-tool-table/search-tool-table.component.html
- src/app/search/search-workflow-table/search-workflow-table.component.html
- src/app/search/search-workflow-table/search-workflow-table.component.scss
- src/app/shared/styles/entry-table.scss
- src/app/workflows/list/list.component.html
- src/styles.scss
Almost unnoticeable changes to the search tables... but I think it makes a difference, following the mocks:
- More padding around the entire table
- More padding between table rows
- Slightly smaller bubble sizes for "Format" entries
- Make the name column wider and the Author column a bit smaller
- Change heading "Name" -> "Name & Description"
- Purple stars and bolded text, switch order so star first then number
**Before - Search page workflows:**
**After - Search page workflows:**
**Before - Search page tools:**
**After - Search page tools:**
For entry specific search pages:
- Use friendly descriptor type names
- Same changes to starred - purple, bolded, swap order
**Before:**
**After:**
| Before | After |
|:---:|:---:|
| …
> Minor Search UI Updates

- .circleci/config.yml
- src/app/notebook/mathjax-config.js
This PR changes the notebook-related MathJax font path so it backtracks to the root via parent directory references, so that `.circleci/config.yml` finds the path and remaps it to the deployed asset URL.
Log into QA, register a notebook containing an equation embedded in a Markdown cell, via the "Preview" tab for said notebook, and make sure that the MathJax fonts are loaded properly and the equation renders using them. 
**Issue**
https://ucsc-cgl.atlassian.net/browse/SEAB-5435
**Security**
> SEAB-5435: Fix mathjax notebook fonts

- .circleci/config.yml
- src/app/notebook/mathjax-config.js
Fix mathjax font url, cherry pick of https://github.com/dockstore/dockstore-ui2/commit/b551eb927f11a241dcfacfc36c1cf3bb7d6c6ab9 to release/1.14
None, will be verified on develop and during deploy-related user testing.
**Issue**
https://ucsc-cgl.atlassian.net/browse/SEAB-5435
**Security**
> SEAB-5435: Fix mathjax notebooks font url

- src/app/workflow/launch-third-party/launch-third-party.component.html
The PR changes the "Launch with" button tooltips so they appear to the left of the button, rather than below.  This avoids the tooltip obscuring the next button in the list, which is frustrating and makes the buttons hard to use.
It would be great to be able to style this, but I suspect [but am not sure] that's not possible.
Fire up the UI and make sure the "Launch with" tooltips all appear correctly, to the left of the corresponding buttons.
**Issue**
https://ucsc-cgl.atlassian.net/browse/SEAB-5511
**Security**
> SEAB-5511: Make all "launch with" button tooltips appear to the left

- src/app/stargazers/stargazers.component.html
- src/app/stargazers/stargazers.component.ts
For an entry, display "There are no stargazers for this entry" instead of "There are no stargazers for this organization".
The "organization" property doesn't exist, so it's undefined, not null, which caused it to display the text "organization".
Also got rid of an `any`.
1. Navigate to a workflow or tool with no stargazers
2. Click on the star to view stargazers
3. Message should say "There are no stargazers for this entry".
**Issue**
dockstore/dockstore#5535
**Security**
> Display correct message for no stargazers

- src/app/search/search.component.ts
In some cases, on the Search page, when you clicked on a facet radiobox, its state would not toggle, and the URL would not update properly.  This behavior could be reproduced by visiting the "Notebooks" tab in search, clicking on a notebook link, using the browser's "Back" button to return to the Search page, and then clicking on the "Python" radiobox in the "Language" facet.  For a split second, the UI appears to be doing the right thing, but then fails.
This PR fixes the problem, by moving the code that initializes the mappings for a given tab index, so that it runs before the facet settings are extracted from the search URL and processed. 
Try the procedure mentioned in the above description, and confirm that the "Language" facet radiobox toggles …
> SEAB-5570: Fix "non-sticky" search facets

- cypress/e2e/immutableDatabaseTests/metrics.ts
- src/app/shared/entry/platform-partner.pipe.spec.ts
- src/app/shared/entry/platform-partner.pipe.ts
- src/app/shared/pipe/pipe.module.ts
- src/app/workflow/executions/executions-tab.component.html
- src/app/workflow/executions/executions-tab.component.spec.ts
- src/app/workflow/executions/executions-tab.component.ts
- src/app/workflows/workflows.module.ts
This PR creates a pipe to change the `PartnerEnum` values to its display names (ex. `DNA_STACK` -> `DNAstack`) in the metrics dropdown.
Before fix: 
After fix:
1. Go to https://qa.dockstore.org/workflows/github.com/broadinstitute/gatk-sv/merge-cohort-vcfs:v0.13-beta?tab=info&metrics
2. click the Metrics tab and confirm the dropdown shows 'DNAstack' instead of DNA_STACK.
3. Also the new unit tests should pass
**Issue**
https://ucsc-cgl.atlassian.net/browse/SEAB-5413
**Security**
> SEAB-5413: create pipe for partner display names

- cypress/e2e/smokeTests/sharedTests/basic-enduser.ts
This PR removes 1.13 specific code in the smoke tests.
Check in the various slack channels to verify that the nightly smoke tests pass for all environments.
**Issue**
dockstore/dockstore#5372
https://ucsc-cgl.atlassian.net/browse/DOCK-2328
**Security**
> Clean up smoke test code after 1.14 release

- .circleci/config.yml
On rare occasions, `apt-get` fails to retrieve some cypress dependencies so this ticket tries to reinstall these if the command fails the first time.
Check that dependencies are installed successfully.
**Issue**
[SEAB-5491](https://ucsc-cgl.atlassian.net/browse/SEAB-5491)
**Security**
[SEAB-5491]: https://ucsc-cgl.atlassian.net/browse/SEAB-5491?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SEAB-5491: Retry installing cypress dependencies

- cypress/e2e/immutableDatabaseTests/metrics.ts
- package.json
- src/app/workflow/executions/executions-tab.component.ts
This PR fixes the `Tool Not Found` error when viewing metrics for notebooks, apptools, and services by fixing the TRS ID used when called the `aggregatedMetricsGet` endpoint. The bug was happening for notebooks, apptools, and services because the TRS ID was using the `#workflow` prefix instead of the correct one for notebooks, apptools, and services so the endpoint returned a 404 because it couldn't find the entry.
Follow the instructions in the ticket and verify that there is no Tool Not Found error. Verify for notebooks, apptools, and services.
**Issue**
dockstore/dockstore#5561
https://ucsc-cgl.atlassian.net/browse/DOCK-2421
**Security**
Please …
> Fix TRS ID when getting metrics for notebooks, apptools, and services

- cypress/e2e/group2/myworkflows.ts
- cypress/e2e/group3/githubAppTools.ts
- src/app/myworkflows/sidebar-accordion/github-apps-logs/github-apps-logs.component.html
- src/app/myworkflows/sidebar-accordion/github-apps-logs/github-apps-logs.module.ts
This PR adds information to the error box that's displayed when the GitHub apps logs cannot be retrieved for a particular organization, informing the user of the typical problems and ways to fix them.
After surveying the UI and webservice codebases, I decided to go with a "low code" approach.  This error doesn't happen often and IMHO, the new informational text provides actionable solutions.  A different approach would be to detect the specific failure mode and display instructions tailored to it, but that would require significantly more modification, some to the webservice, and felt like overkill.
The error box links to the GitHib page that displays the prod Dockstore app's orgs/access.  We could try to display the correct link for qa/staging/etc, but there's probably …
> SEAB-4303: Improve error message when github app log retrieval fails

- src/app/descriptor-languages/Jupyter.ts
- src/app/home-page/widget/entry-box/entry-box.component.ts
Clicking on "Learn more about notebooks" in the dashboard would take you to a 404 page so this PR replaces the url with the correct one.
After enabling notebooks and going to the link in the dashboard, should take you to the correct documentation page.
**Issue**
[DOCK-2425](https://ucsc-cgl.atlassian.net/browse/DOCK-2425)
**Security**
[DOCK-2425]: https://ucsc-cgl.atlassian.net/browse/DOCK-2425?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOCK-2425: Fix notebooks documentation link

- .circleci/config.yml
- cypress/e2e/group3/githubAppTools.ts
- src/app/myworkflows/sidebar-accordion/github-apps-logs/github-apps-logs.component.ts
- src/app/myworkflows/sidebar-accordion/sidebar-accordion.component.ts
- src/app/user-page/user-page.component.html
- src/app/user-page/user-page.component.ts
This PR allows admins and curators to see users' GitHub app logs through their userpage. This new button is only visible for admins and curators.
Viewing user page as an admin (App logs button) 
When button clicked
Viewing user page as nonadmin nor curator (App Logs button should be hidden)
As an admin or curator, go to  https://qa.dockstore.org/users/hyunnaye and confirm that the button works properly.
Then log out and verify that the button is hidden.
**Issue**
https://ucsc-cgl.atlassian.net/browse/SEAB-5676
**Security**
> SEAB-5676: allow admins and curators to see a users GitHub app logs

- .circleci/config.yml
- cypress/e2e/immutableDatabaseTests/admin.ts
- src/app/loginComponents/accounts/external/accounts.component.ts
- src/app/loginComponents/requests/requests.component.html
- src/app/shared/constants.ts
- src/app/user-page/user-page.component.html
- src/app/user-page/user-page.component.ts
This PR adds a new tab "Other linked accounts" on a user's profile page that only admins and curators can see. This allows community leads to view what other types of accounts a user has linked.
When there are no other linked accounts
Tab is not visible when logged out or not an admin/curator
In requests page, the username is linked to their page
1. Log into an admin or curator account. 
2. Go to https://qa.dockstore.org/users/denis-yuen and confirm that a zenodo account is linked.
3. Log out and verify that the tab is not visible.
**Issue**
https://ucsc-cgl.atlassian.net/browse/SEAB-5655
**Security**
Please make sure that you've checked the following …
> SEAB-5655: allow admins and curators to see user's other linked accounts

- src/app/workflow/dag/dag.component.html
- src/app/workflow/dag/dag.component.spec.ts
- src/app/workflow/dag/state/dag.query.ts
When looking at the workflow DAG tab, sometimes there would be an error related to 'edges' being undefined and the tab would be blank. This is because sometimes `dagResults` would be an empty object so this PR adds a check to see if the results contain `edges` and `nodes`, and then display the missing message in the DAG tab.
Go to the DAG tab inside a workflow (such as the workflow mentioned in the linked issue) and check that there are no errors in the browser console.
**Issue**
[DOCK-2411](https://ucsc-cgl.atlassian.net/browse/DOCK-2411)
**Security** …
> DOCK-2411: Fix console errors when viewing dag tab

- src/app/gravatar/gravatar.service.spec.ts
- src/app/gravatar/gravatar.service.ts
This PR fixes the issue where the mystery person avatar is not showing up for starred events belonging to unknown users.
Before:
After:
NOTES: I tried to find a change log for gravatar but I wasn't able to, so I ended up changing the request url to include a fake hash similar to the examples in their [documentation](https://en.gravatar.com/site/implement/images/) (also we're doing something similar with `gravatarUrlForImageUrl` anyways). Typically, gravatar would try to return an image associated with the hashed email address and return the default when there's no image associated with the email. Before we would exclude the hash from the url so the default is returned, but I guess something changed with the gravatar api so that's no longer working. 
Also, I found out while …
> DOCK-2438: Fix mystery person avatar

- src/app/shared/markdown-wrapper/markdown-wrapper.component.spec.ts
- src/app/shared/markdown-wrapper/markdown-wrapper.service.spec.ts
- src/app/shared/markdown-wrapper/markdown-wrapper.service.ts
Some markdown tables do not render properly due to the presence of tab characters in the table. This PR removes tabs from table headers before parsing so that the html is generated correctly for the table.
Before:
After:
Go to the info tab for a workflow with a table in the description (e.g., the workflow mentioned in the related ticket /workflows/github.com/aofarrel/tree_nine/tree_nine:main?tab=info) and make sure the table is displayed properly.
**Issue**
[DOCK-2428](https://ucsc-cgl.atlassian.net/browse/DOCK-2428)
**Security**
[DOCK-2428]: …
> DOCK-2428: Display markdown tables correctly

- package.json
- src/app/user-page/user-page.component.ts
This PR allows community leads to see a user's linked accounts properly.
In the previous PR, the code was using `this.tokenQuery.tokens$` but that is wrong since it accesses the logged in user's tokens. This PR now use `this.usersService.getUserTokens(this.user.id)` to get the linked accounts for the desired user.
Fixed Screenshot - Note the logged in user is `user_curator` and the linked accounts show `user_A`'s accounts
Log into an admin or curator account.
Go to https://qa.dockstore.org/users/denis-yuen and confirm that a zenodo account is linked.
Log out and verify that the tab is not visible.
**Issue**
https://ucsc-cgl.atlassian.net/browse/SEAB-5655
**Security**
If there are any concerns that require extra attention from the security team, …
> SEAB-5655: fixed code regarding community leads seeing user's linked accounts

- src/app/shared/code-editor/code-editor.component.ts
This PR enables word wrapping in the ace code editor so that long lines are easier to navigate when viewing files (here the line length and formatting are preserved in case the file is being edited).
Before:
After:
Go to a workflow/tool/notebook, click on the Files tab, and check that long lines of text/code wrap around.
**Issue**
[DOCK-2449](https://ucsc-cgl.atlassian.net/browse/DOCK-2449)
**Security**
[DOCK-2449]: https://ucsc-cgl.atlassian.net/browse/DOCK-2449?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOCK-2449: Enable wrapping when viewing files

- .circleci/config.yml
Upgrading to a version of the orb that better deals with a missing chomedriver. 
Details in linked thread (basically, Google is not guaranteeing a synced ChromeDriver release with new Chrome versions)
See if nightly builds and develop builds pass the install chromedriver step
**Issue**
n/a
**Security**
> Fix ChromeDriver install

- .circleci/config.yml
Have not had a hotfix, but probably need https://github.com/dockstore/dockstore-ui2/pull/1835 in develop to avoid sonarcloud warning about Java 11 (and old sonarscanner version)
> SEAB-5808: Upgrade sonarscanner to 5.0.1 (#1835)

- src/app/search/query-builder.service.ts
- src/app/search/search-entry-table.ts
- src/app/search/search-notebook-table/search-notebook-table.component.html
- src/app/search/search-tool-table/search-tool-table.component.html
- src/app/search/search-workflow-table/search-workflow-table.component.html
This PR improves the relevance of Dockstore search results.
To run a search, the UI synthesizes a search query using the bodybuilder library and submits it to ES.  Before continuing, please read the following, which explains the structure of typical ES search queries:
https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-bool-query.html
In the previous implementation:
* Keyword subqueries were run in a `filter` context, preventing ES from scoring the results.
* The UI always sorted the results, per the header control settings, so even if ES returned results sorted by relevance, the UI would reorder them (in descending star order by default).
* Essentially, when we ran a search, ES was determining all of the hits that matched the search criteria, sorting …
> SEAB-5913: Improve search relevance

- src/app/home-page/recent-events/recent-events.component.html
In https://github.com/dockstore/dockstore/pull/5697, in the webservice, we added a Hibernate `NotFound` annotation to make dangling `Event` versions gracefully resolve to null.  This PR modifies the UI to gracefully handle said nulls by substituting some generic text where the detailed description of the version would have gone.
We don't know what kind of reference the null represented, so the most future-proof generic text would be "a version".  However, all of the `Events` with existing versions point to tags, so for now, it's probably relatively safe, and definitely less generic, to instead say "a tag".  This PR implements the latter.
```
webservice_test=# select distinct v.referenceType from event join workflowversion as v on event.versionid = v.id;
referencetype …
```
> DOCK-2442: Handle null version in Event

- src/app/home-page/home-logged-out/home.component.html
Fixes the news box on the homepage by putting the tag back into its parent div.
It looks like it got messed up in https://github.com/dockstore/dockstore-ui2/pull/1837
Review that the homepage news and updates box looks normal.
**Issue**
https://ucsc-cgl.atlassian.net/browse/SEAB-5982
**Security**
> SEAB-5982: fix news box on homepage

- cypress/e2e/group3/deletion.ts
- src/app/workflow/versions/versions.component.html
For Galaxy workflows, display `Galaxy` instead of `gxformat2` in the Versions tab.
TLDR; Use the pipe built just for this.
Longer explanation -- we weren't actually displaying the language version twice; we were displaying the language followed by the language version. For example, for WDL versions it displays something like `WDL draft-2`, where `WDL` is the language and  `draft-2` is the language version.
For Galaxy we made a mistake in having the language be `gxformat2` (not to be confused with the language version); the language is Galaxy. But it got baked in, so we use the pipe to display it as Galaxy, but missed this place.
1. Go to a Galaxy workflow
2. Select the Versions table
3. Ensure that it the language versions say `Galaxy gxformat1` …
> Use the descriptorLanguage pipe to handle Galaxy on the versions tab

- cypress/e2e/group1/dashboard.ts
- cypress/e2e/immutableDatabaseTests/app-spec.ts
- cypress/e2e/smokeTests/sharedTests/basic-enduser.ts
- cypress/support/commands.ts
Currently, Twitter widget is in staging/prod, Mastodon is in qa. Add an "or" selector to handle both cases.
Created a follow-up ticket, SEAB-5992, to undo after 1.15 is released.
Nightly smoke tests should pass in all environments.
**Issue**
No issue created.
**Security**
> Update smoke tests for both Twitter and Mastodon

- src/app/workflow/info-tab/info-tab.component.html
This PR goes with https://github.com/dockstore/dockstore/pull/5713 and disables manual topic editing in the UI for GitHub app entries since they should be updating it in the .dockstore.yml instead. Topic selection is left as is, so the user can still change the selection for a GitHub app entry.
Also updated some tooltips for the topics.
In addition to the instructions in https://github.com/dockstore/dockstore/pull/5713, verify that the `Edit` button for editing manual topics is disabled for GitHub App entries.
**Issue**
dockstore/dockstore#5625
[DOCK-2444](https://ucsc-cgl.atlassian.net/browse/DOCK-2444)
**Security**
Please make sure that you've …
> Disable manual topic editing in the UI for GitHub App entries

- cypress/e2e/group2/myworkflows.ts
This PR unskips a UI2 integration test that was skipped as part of a previous PR.  Per the description in https://ucsc-cgl.atlassian.net/browse/DOCK-2471, a flaky test was disabled.  Most of the description refers to a test in `mytools.ts`, however, the skipped test is in `myworkflows.ts`.  Possibly, this test was inadvertently disabled because the string argument to `it()` is the same as the test that was failing in mytools? https://github.com/dockstore/dockstore-ui2/blob/3fd09ee103c67c95f44774c1f63280d74c3637e4/cypress/e2e/group3/mytools.ts#L66
The mytools test was fixed in another previous PR.
Confirm that the reenabled test is passing when CircleCI runs.
**Issue**
https://ucsc-cgl.atlassian.net/browse/DOCK-2471
dockstore/dockstore#5696
Please …
> DOCK-2471: Reenable skipped test

- package.json
- src/app/app.module.ts
- src/app/configuration.service.ts
- src/app/shared/dockstore.model.ts
- src/app/workflow/launch-third-party/dialog/launch-to-codespace-dialog.component.html
- src/app/workflow/launch-third-party/dialog/launch-to-codespace-dialog.component.ts
- src/app/workflow/launch-third-party/launch-third-party.component.html
- src/app/workflow/launch-third-party/launch-third-party.component.ts
This PR adds a "Launch with" button to the public notebook entry page that runs the notebook in a GitHub Codespace.  See the webservice PR for GitHub Codespace background: https://github.com/dockstore/dockstore/pull/5721
The new Codespace "launch with" button works a bit differently than the other "launch with" buttons.  When it is clicked, it checks the notebook's devcontainer files (which the enclosing component fetches during initialization), and attempts to find a devcontainer file that contains a reference to the notebook file.  Currently, "reference" is defined as the devcontainer file contents containing the notebook file absolute path as a substring.  This is a rough heuristic, but probably works pretty good in practice, and is probably fine for now...
If we find a …
> SEAB-5951: "Launch with" to a GitHub Codespace

- src/app/workflow/info-tab/info-tab.component.html
Follow-up to https://github.com/dockstore/dockstore-ui2/pull/1859. During the demo, the `Edit` manual topic button wasn't disabled for GitHub app entries when it should've been. Turns out there was a bad automatic merge when I merged my PR, resulting in two `[disabled]` fields for the button. The UI took the first one and ignored the second. This PR combines both `[disabled]` conditions so that the `Edit` manual topic button is disabled for GitHub app entries.
See instructions in https://github.com/dockstore/dockstore-ui2/pull/1859
**Issue**
dockstore/dockstore#5635
https://ucsc-cgl.atlassian.net/browse/DOCK-2444
**Security**
Please make sure that …
> Fix merge of disable edit button for GitHub app entries PR

- cypress/e2e/group2/notebooks.ts
- src/app/file-tree/file-tree.component.ts
- src/app/source-file-tabs/source-file-tabs.component.ts
This PR removes the "Primary" label from the notebook file in the Files tab, since it arguably doesn't make sense, because there's no notion of a "primary descriptor" in the notebook world.
Navigate to the "Files" tab of a notebook, view the notebook file, and confirm that it is no longer labelled "Primary".
**Issue**
https://ucsc-cgl.atlassian.net/browse/SEAB-5443
> SEAB-5443: Remove "Primary" label from notebook file

- src/app/shared/markdown-wrapper/markdown-wrapper.service.spec.ts
- src/app/shared/markdown-wrapper/markdown-wrapper.service.ts
This PR modifies the UI's markdown service to generate correct HTML for relative inline images when the `baseUrl` references github, thus displaying them properly in an entry's description, and in a notebook's "Preview". 
Previously, Dockstore displayed relative inline markdown images as broken image icons, for example, see the broken flowchart images midway down the description here:
https://dockstore.org/workflows/github.com/aofarrel/myco/myco_sra:main?tab=info
The UI calculated a base URL, which it passed to the markdown converter, which prepended it to the relative generated `img` tag urls.  Alas, our base URL (and the URL constructed from it) referenced the github resource embedded _within a github page_.  So, when browser retrieved the image from the URL, it got back …
> DOCK-2373: Fix inline markdown images

- THIRD-PARTY-LICENSES.csv
- package-lock.json
- package.json
This PR updates the ini package to the latest available version: 4.1.1
QA should function properly.
**Issue**
https://ucsc-cgl.atlassian.net/browse/SEAB-3091
**Security**
> SEAB-3091: update ini to latest 4.1.1

- cypress/e2e/group3/githubAppTools.ts
- src/app/container/register-tool/register-tool.component.html
- src/app/home-page/dashboard/dashboard.component.ts
- src/app/home-page/home-page.module.ts
- src/app/myworkflows/myworkflows.service.ts
- src/app/shared-workflow-services-notebooks/shared-workflow-services-notebooks.module.ts
- src/app/shared/modules/register-github-app.module.ts
- src/app/shared/register-github-app/register-github-app.component.html
- src/app/shared/register-github-app/register-github-app.component.spec.ts
- src/app/shared/register-github-app/register-github-app.component.ts
- src/app/workflow/register-workflow-modal/register-github-app-modal/register-github-app-modal.component.html
- src/app/workflow/register-workflow-modal/register-workflow-modal.component.html
- src/app/workflow/register-workflow-modal/register-workflow-modal.service.ts
Adds more explicit steps for the GitHub App flow. This is hard to word, and I expect a lot of feedback. :)
Here's what it looks like now:
I know the steps are not comprehensive, e.g., it doesn't talk about optionally installing to the .github directory instead, nor does it cover the case where we now do discover a .dockstore.yml in certain branches after installation. I'm trying to balance it between being short enough that it will be read, but long enough to be informative and/or spark enough curiosity to click the documentation link.
Another option is to break up the list into "wizard pages", e.g., "Click here to install the Dockstore GitHub App. When you have completed, click Next"; then "Push a valid .dockstore.yml to your repo. When you have completed, click Next. …
> Refactor and change text for GitHub app registration

- package.json
- src/app/shared/state/entry-wizard.service.ts
A previous webservice PR https://github.com/dockstore/dockstore/pull/5747 narrowed the type of an endpoint argument, which propagated to the UI via openapi.yaml and caused the build to fail.  This PR makes the requisite adjustment to the UI code.  It feels a bit grimy but is probably fine.
Confirm UI builds successfully.
**Issue**
https://ucsc-cgl.atlassian.net/browse/DOCK-1946
https://github.com/dockstore/dockstore/issues/4513
**Security**
No concerns.
> DOCK-1946: Adjust for openapi change

- cypress/e2e/immutableDatabaseTests/dropdown.ts
- src/app/home-page/recent-events/recent-events.component.ts
- src/app/user-page/user-page.component.ts
This PR fixes the UI so that when the profile page switches from user X's to user Y's profile page, user Y's information is displayed.  Previously, the UI was broken, and would get "stuck" on user X's page.  The URL would change, but the information on the profile page did not.
The fix was to the `UserPageComponent` and `RecentEventsComponent` components, which comprise most of the profile page, and previously both read the username from the route upon construction.  Now, they observe the route parameters and update the user when they change.  
Both components were lightly refactored to make their internals more similar to each other.  Also, I deleted the unused property `username`, please inspect and confirm that it is unused. 
I kinda feel like both components should be …
> SEAB-6021: Fix stuck profile page

- src/app/shared/entry/recent-events.pipe.spec.ts
- src/app/shared/entry/recent-events.pipe.ts
This PR modifies the `recentEvents` pipe to use the referenced entry's type metadata so that it works for all entry types.  Previously, it malfunctioned when passed an event that referenced a notebook, service, or apptool. 
The PR adds some opinionated (in that they prescribe the underlying implementation in some cases) unit tests that exercise the new code.  Lots of duck typing, quaaack.
On qa, register and publish a notebook, service, or apptool.  Navigate to your profile, and confirm that the entries in the "Recent Events" section are formatted and linked correctly. 
**Issue**
https://ucsc-cgl.atlassian.net/browse/DOCK-2487
dockstore/dockstore#5735
**Security**
No concerns.
Please make sure that you've checked the following before submitting your …
> DOCK-2487: Generalize recentEvents pipe

- src/app/descriptor-languages/Jupyter.ts
- src/app/source-file-tabs/source-file-tabs.service.ts
The original intention for this PR's backing ticket (https://ucsc-cgl.atlassian.net/browse/SEAB-6024) was to add a "Configuration Files" tab to the notebook entry page, which seemed to be conspicuously missing.   However, it turns out that the code already defined a "Configuration Files" tab (how quickly I forget lol) and it simply wasn't appearing, because the code didn't categorize `.dockstore.yml` or devcontainer files as notebook Configuration files, and the existing tab code was written to always display the first two files tabs and hide the rest if they were empty.  Previously, the notebook "Configuration File" tab was third, and thus did not appear if it had no files.
So, this PR changes the UI to:
* Include `.dockstore.yml` and devcontainer files in the set of …
> SEAB-6024: Modify "Files" tabs, mostly for notebooks

- .circleci/config.yml
CircleCI was failing when installing circleci/browser-tools.  This PR bumps the version of circleci/browser-tools to 1.4.6 and fixes the problem.
The initialization steps of the UI2 CircleCI tests should complete successfully.
**Issue**
None
**Security**
No concerns.
> Fix circleci chromedriver installation error

- src/app/search/search-tool-table/search-tool-table.component.html
- src/app/search/search-workflow-table/search-workflow-table.component.html
This PR moves the tooltip for "Name and Description" portion of the search results to the left of the name/description.  Previously, it appeared below, thus covering some of the result and/or the next result, interfering as the user scanned or tried to interact with the results.  The new position overlaps the facets a little bit, but overall, the effect is much less deleterious to the typical flow...
Go to search on qa, mouse over the name/description of a result, and confirm that the tooltip appears to the left.
**Issue**
https://ucsc-cgl.atlassian.net/browse/SEAB-5971
**Security**
No concerns.
> SEAB-5971: Move search result tooltips to the left of results

- src/app/descriptor-languages/Jupyter.ts
- src/app/workflow/info-tab/info-tab.service.spec.ts
- src/app/workflow/info-tab/info-tab.service.ts
This PR changes the UI to generate the correct TRS link for a Galaxy workflow.  Previously, the UI was converting the Dockstore Galaxy descriptor type to the plain TRS type by uppercasing and prepending "PLAIN_", which didn't work for "gxformat2".
This PR also makes a couple of changes to the Jupyter "extended descriptor info" that are necessary for fully-functional TRS notebook support.
On qa, navigate to a info tab of a Galaxy workflow, click on the "TRS:" link, and confirm that the primary descriptor contents are displayed.
**Issue**
https://ucsc-cgl.atlassian.net/browse/DOCK-2496
dockstore/dockstore#5751
**Security**
No concerns.
> DOCK-2496: Fix TRS link for Galaxy workflows

- cypress/e2e/smokeTests/sharedTests/waf.ts
A failing smoke test due to change in the WAF rules is being silenced. More investigation to see if we can turn it on in an upcoming sprint.
Smoke tests pass
**Issue**
https://ucsc-cgl.atlassian.net/browse/SEAB-6084
**Security**
> Comment out failing WAF test due to rule change

- src/app/mytools/my-tool/my-tool.component.ts
One invocation of the register tool was missed when we went to a wider dialog; it was missed on the My Tools page (worked from the Dashboard page).
1. Go to the Dashboard, e.g., https://staging.dockstore.org
2. Click the `Register a tool` button, note the width of the dialog that pops up, dismiss it.
3. Click the `Tools` tile on the left side of the dashboard, so you are in My Tools
4. Click the `Register a tool` button. Ensure that its width is the same as in step 2.
**Issue**
SEAB-5999
**Security**
> Fix width of register tool dialog

- .github/workflows/accessibility_test.yml
Reverts dockstore/dockstore-ui2#1899
Actually, probably blocked by  https://github.com/actions/upload-artifact/releases/tag/v4.0.0 
and https://ucsc-cgl.atlassian.net/browse/SEAB-6108
> Revert "Bump actions/download-artifact from 3 to 4"

- THIRD-PARTY-LICENSES.csv
- package-lock.json
- package.json
Overrides the `ini` package, that is a transitive dependency, with a newer version.
Tried first upgrading `@dataroma/akita`, the package that uses the older `ini`, but that was a major upgrade with breaking changes.
See ticket for review instructions.
**Issue**
SEAB-3091
**Security**
> Update ini version

- .github/workflows/accessibility_test.yml
- scripts/run-pa11y-ci.sh
Actions Artifacts v4 no longer allows multiple jobs to upload to the same artifact. This caused the accessibility check to fail during builds ([example](https://github.com/dockstore/dockstore-ui2/actions/runs/7401876576/job/20139880557?pr=1882)). To fix this, the accessibility test should save each test result to its own unique artifact instead of a shared one.
To adhere to v4, the accessibility test results are saved to separately named artifacts, one for the current branch and one for the base branch. Both artifacts are then downloaded to the same directory to be compared as normal.
The accessibility test (using v4) should succeed upon creating this PR.
**Issue**
[SEAB-6108](https://ucsc-cgl.atlassian.net/browse/SEAB-6108?atlOrigin=eyJpIjoiODMyMmNl …
> SEAB-6108: Update upload/download artifacts from v3 to v4

- cypress/e2e/group3/metrics.ts
- src/app/myworkflows/myworkflows.service.ts
- src/app/workflow/versions/versions.component.html
It was showing all versions have metrics, regardless of whether they did have metrics or not.
This worked on the public facing page, because the public facing page calls a different [endpoint](https://staging.dockstore.org/api/static/swagger-ui/index.html#/workflows/getPublishedWorkflowByPath) than [my-workflows](https://staging.dockstore.org/api/static/swagger-ui/index.html#/workflows/getWorkflow). The public facing page was already passing the `metrics` query parameter value, my-workflows wasn't. 
1. Go to My Workflows
2. Select a workflow that has no metrics, or some metrics
3. Navigate to the versions tab
4. Verify that the Metrics column does not have a checkmark visible.
**Issue**
DOCK-2501
dockstore/dockstore#5790
**Security**
If there are …
> Metrics column value in my-workflows was wrong

- src/app/myworkflows/sidebar-accordion/sidebar-accordion.component.html
This PR removes the "Refresh Organization" button from the sidebar accordion on the my-notebooks page.  Notebooks are registered via `.dockstore.yml` only, so there's never anything to refresh. 
Navigate to your my-notebooks page, and confirm that the "Refresh Organization" no longer appears at the bottom of the sidebar accordion.
**Issue**
https://ucsc-cgl.atlassian.net/browse/SEAB-6185
**Security**
No concerns.
> SEAB-6185: Do not display "Refresh Organization" button in my-notebooks accordion

- src/app/home-page/widget/starred-box/starred-box.component.html
- src/app/home-page/widget/starred-box/starred-box.component.ts
This PR adds a count of starred notebooks to the "Starred" box that appears in lower right corner of the dashboard.  It also reorders the "get starred entry" requests so the results for the entry types that our userbase is most interested in will probably show up first.
Navigate to your dashboard and confirm that a correct count of starred notebooks in the "Starred" box.  Star a notebook.  Confirm that the count of starred notebooks has increased by one.
**Issue**
https://ucsc-cgl.atlassian.net/browse/SEAB-6189
**Security**
No concerns.
> SEAB-6189: Add notebooks count to dashboard "Starred" box

- cypress/e2e/group3/mytools.ts
- src/app/mytools/my-tool/my-tool.component.html
This PR removes the "More" button and the associated "Discover Existing Dockstore Tools" menu from the my-tools sidebar accordion.  The motivation was that this functionality was broken: when you clicked "Discover Existing Dockstore Tools", the sidebar would be populated with a list of discovered _workflows_, and if you clicked on one, it would be displayed as a tool.  More details here: https://ucsc-gi.slack.com/archives/C05EZH3RVNY/p1706134461646039
The original goal of this ticket was to add the "Discover Existing" functionality for notebooks, but if we simply added the button menu to the my-notebooks accordion, the same type of bug would happen.
After this merges, we will write a new ticket to add the "Discover Existing" functionality, for both tools and notebooks, …
> SEAB-6186: Remove "More" and "Discover Tools" button/menu from accordion.

- src/app/workflow/executions/executions-tab.component.ts
Recently, a new snackbar that says "Retrieving metrics data succeeded" has been appearing in the UI.  It pops up whenever an entry page loads or a version is selected or hidden, and possibly at other times.  While it serves as an effective advertisement for our new metrics feature, it's also a bit disruptive, and likely to annoy regular users (especially after it's happened a few dozen times).
So, I changed the code so that, on success, it doesn't pop up anymore.  This seems to make sense, it's kinda like other ancillary data we load in the background, like categories.  The end user only needs to be notified on failure (and even then, maybe not with a snackbar).
Whilst documenting this ticket, I noticed that, very occasionally, the snackbar only contained the words …
> SEAB-6190: Suppress "Retrieving metrics data succeeded" snackbar

- src/app/container/versions/versions.component.html
- src/app/workflow/versions/versions.component.html
Previously, the tooltips of the Versions table headings were positioned, by default, below the headings.  And, most of the time, when I'd move my cursor to the first "Info/Actions" button, the "Action" heading tooltip would pop up and cover the button, preventing me from clicking it.
This PR repositions the Versions table heading tooltips so that they appear _above_ the headings.  There, they will interfere less with user actions, and obscure less relevant information, assuming that, most commonly, the user is either moving the cursor:
* across the headings to figure out what they mean, whilst possibly looking at the version info below.
* down through the headings to reach the version information/elements below.
Navigate to the Versions table for an …
> DOCK-2504: Position tooltips above Versions table headings

- cypress/e2e/group2/notebooks.ts
- src/app/workflow/version-modal/version-modal.component.html
Prior to this PR, in the "Edit Notebook Version" dialog, the Git Reference and Notebook Path were displayed as form inputs, and the form validation was failing, because it was applying the regexp that it uses to check workflow paths, which didn't work on notebook paths ending with `.ipynb`.  Because the validation failed, the "Save Changes" button was disabled, thus preventing the only editable setting ("Hidden") from being submitted.
This PR displays a notebook's Git Reference and Notebook Path in `div`s, rather than `form` inputs, thus bypassing the validation, which is unnecessary because they're read only.  Thus, it enables the "Save Changes" button, allowing the user to hide a notebook. 
On qa, select a version of one of your notebooks, and use …
> SEAB-6188: Enable notebook versions to be hidden

- src/app/workflow/executions/executions-tab.component.html
- src/app/workflow/executions/executions-tab.component.ts
Add a passing rate to metrics' UI.
Only passed and failed executions are used in the calculation (aborted are skipped).
1. Navigate to a workflow with execution metrics
2. Go to metrics tab
3. See percentage of passing next to total passed.
**Issue**
SEAB-6201
**Security**
> Add successful passing rate

- cypress/e2e/group2/myworkflows.ts
- cypress/e2e/immutableDatabaseTests/workflowDetails.ts
- src/app/workflow/workflow.component.html
Gives a little more prominence to metrics, moving the tools tab out of the initial scrolling view, until we come up with a better solution.
Cypress test changes are annoying and a little hard-coded, but I'm going to limit the scope of this change for the release.
Navigate to a workflow and version with metrics and ensure the metrics tab visible. Something like this:
**Issue**
SEAB-6206
**Security**
> Swap position of Metrics and Tool tabs

- src/app/workflow/executions/executions-tab.component.ts
This PR only adds rows in the Execution Metrics section if there are data present.
Before Fix: 
After Fix:
Go to https://staging.dockstore.org/workflows/github.com/gatk-workflows/seq-format-conversion/BAM-to-Unmapped-BAM:3.0.0?tab=metrics and verify that the empty CPU, Memory, Cost rows are not shown.
**Issue**
https://ucsc-cgl.atlassian.net/browse/SEAB-6200
**Security**
> SEAB-6200: hide blank metrics rows

- cypress/e2e/group2/myworkflows.ts
- cypress/e2e/group3/metrics.ts
- cypress/e2e/immutableDatabaseTests/workflowDetails.ts
- src/app/shared/styles/workflow-container.component.scss
- src/app/workflow/workflow.component.html
Rolls back #1926, which reordered the tabs to make the Metrics tab visible without scrolling.
Instead make the tabs narrower, so they all fit, and no scrolling is required, per Steve's [comment](https://github.com/dockstore/dockstore-ui2/pull/1926#pullrequestreview-1857164742).
TLDR; restore original order of tabs on workflow component, tabs are now narrower to avoid scrolling.
1. Go to a workflow version with metrics
2. Ensure all tabs are visible and the "scroll arrows" are not present.
3. To make sure there's not a regression, do a browser refresh of the page when positioned on the metrics tab, and ensure the metrics tab is still the active tab.
What it looks like with the fix, full screen and minimum width screen:
**Issue**
SEAB-6231 …
> Make all tabs visible for a workflow

- cypress/e2e/immutableDatabaseTests/services.ts
- src/app/workflows/list/list.component.ts
This PR drops the "Format" column from the Services table. The value is not important when it comes to services (always equals "Service"), and it saves some space.
_(Services before removing "Format" column)_
The `serviceColumns` field excludes `'descriptorType'`, which removes "Format" for Services. Can visit the /services path to verify that the table and spacing look good.
_(Services after removing "Format" column)_
**Issue**
https://github.com/dockstore/dockstore/issues/2867
DOCK-984
**Security**
> DOCK-984: Remove "Format" column from Services table

- .circleci/config.yml
This PR defines parameters for the version numbers of `cimg/postgres` and `cimg/python`. This should help to keep Docker images in sync, thus preventing inconsistent versions within a configuration (see [previously conflicting `cimg/base` versions](https://github.com/dockstore/dockstore-ui2/blob/91f821ec5be06a877a97a3f5a859657856ed476f/.circleci/config.yml)) and making them easier to access/update.
All relevant version numbers in config.yml should be parameterized, and all CircleCI tests should pass.
**Issue**
SEAB-4703
**Security**
> SEAB-4703: Parameterize version numbers in CircleCI configuration

- src/app/descriptor-languages/Galaxy.ts
- src/app/shared/launch.service.ts
- src/app/shared/state/workflow.query.ts
- src/app/workflow/launch/launch.component.html
- src/app/workflow/launch/launch.component.ts
Adds Planemo `run` and `workflow_job_init` (parameter file creation)  to launch-with tab
View Galaxy workflows with and without test parameter files already registered, 
Galaxy workflows with test parameter files will give the user the command to download the first one, and show init, and run info. 
Galaxy workflows without them will skip the panel for downloading a test parameter file
**Issue**
https://ucsc-cgl.atlassian.net/browse/SEAB-6273
**Security**
> Add Galaxy planemo information to launch-with page

- cypress/e2e/group1/dashboard.ts
- cypress/e2e/immutableDatabaseTests/app-spec.ts
- cypress/e2e/smokeTests/sharedTests/basic-enduser.ts
- cypress/support/commands.ts
Previously, due to conflicting contents in staging/prod (i.e. Mastodon widget) versus qa (i.e. Twitter widget), smoke tests had to include Twitter in order to pass (https://github.com/dockstore/dockstore-ui2/pull/1861). Now that 1.15 has been deployed, we can remove the Twitter checks.
All additions of Twitter from https://github.com/dockstore/dockstore-ui2/pull/1861 should be removed, and smoke tests should succeed.
**Issue**
SEAB-5992
**Security**
> SEAB-5992: Remove Twitter from smoke tests

- cypress/e2e/immutableDatabaseTests/linkCheck.ts
- src/app/sitemap/sitemap.component.html
- test/web.yml
The goal of this PR is to experiment with integration testing for broken links, which aims to detect instances of broken URLs and images (currently falls under integration_test_4 as linkCheck.ts).
As of now, the test should iterate through relevant pages/selectors on the site (via `urlPages` and `imagePages`) and, for each, perform link checks. It targets anchor links by sending requests to their `href` property ([example](https://www.linkedin.com/pulse/finding-broken-links-using-cypress-brahma-rao-kothapalli)), and targets images by asserting their `naturalWidth` property is greater than zero ([example](https://stackoverflow.com/questions/51246606/test-loading-of-image-in-cypress/58641462#58641462)).
Look over …
> SEAB-6014: UI link checks

- src/app/search/map-friendly-values.pipe.ts
This PR adds a mapping of "UNINSTALL" to "Uninstall" in `MapFriendlyValuesPipe`, to properly handle the new lambda event type added in https://github.com/dockstore/dockstore/pull/5852
See https://github.com/dockstore/dockstore/pull/5852
**Issue**
https://ucsc-cgl.atlassian.net/browse/SEAB-6000
**Security**
> SEAB-6000: Adjust for UNINSTALL LambdaEvent

- src/app/container/info-tab/info-tab.component.html
- src/app/search/search-notebook-table/search-notebook-table.component.html
- src/app/search/search-tool-table/search-tool-table.component.html
- src/app/search/search-workflow-table/search-workflow-table.component.html
- src/app/shared/ai-bubble/ai-bubble.component.html
- src/app/shared/styles/entry-table.scss
- src/app/workflow/info-tab/info-tab.component.html
- src/styles.scss
This PR increases the max length of the Topic Manual field to 250 to match the max length in the webservice. PR https://github.com/dockstore/dockstore/pull/5847 increases the max length from 150 to 250 characters.
This PR also moves the AI bubble on the search page to the beginning of the topic. When the AI bubble is at the end, it becomes hidden by the `truncate-text-2` class because the topic and AI bubble are considered as one element to truncate.
What it looks like now:
Also changed the hover color to be darker than the non-hover color which is the pattern for other hover elements.
**Before**
Non-hover -> hover
**After**
Non-hover -> hover
Verify that you can save a manual topic with 250 characters in the UI. Verify that you can't save a manual …
> Increase manual topic max length to 250 & move ai bubble on search page

- cypress/e2e/group2/myworkflows.ts
- src/app/workflow/snapshot-exporter-modal/snaphot-exporter-modal.component.html
If only requesting a DOI, do not display a warning that the user needs to link their ORCID account.
1. On the Dockstore accounts page, ensure your Zenodo account is linked, and that ORCID account is **not** linked.
2. Go to My Workflows, then to the versions table of any of your workflows that has tags
3. Click on Actions, Request DOI
4. There should be no red box prompting you to link your ORCID account.
**Issue**
dockstore/dockstore#5796
DOCK-2506
**Security**
> Don't prompt for ORCID link if not required

- package.json
- src/app/container/paramfiles/paramfiles.service.ts
- src/app/workflow/launch-third-party/launch-third-party.component.ts
Smoke tests and builds are failing because the CircleCI artifacts are expired. This PR updates them to the latest develop artifacts.
n/a
**Issue**
n/a
**Security**
> Update develop artifacts

- .circleci/config.yml
- package.json
- scripts/get-circleci-artifact-url.sh
Moves the check_build_develop step earlier (conditionally) and controls it with a new parameter. 
This allows us to run a build nightly, checking for new issues caused by a changing webservice. 
Example of build as usual: 
https://app.circleci.com/pipelines/github/dockstore/dockstore-ui2/11796/workflows/0959c4f8-e5d1-42d4-8d0b-2f428b23a2cc
Example  of build with moved check develop step:
https://app.circleci.com/pipelines/github/dockstore/dockstore-ui2/11797/workflows/9f04c924-c765-43aa-9f68-8dcc7d5225f5/jobs/53146
On merge, will create a cron trigger, similar to what we have for the CLI. 
Check for nightly builds, ideally should see a build fail due to an incompatible change to the webservice. 
**Issue** …
> ui2 - run against webservice develop

- cypress/e2e/group2/myworkflows.ts
- cypress/e2e/immutableDatabaseTests/toolDetails.ts
- cypress/e2e/immutableDatabaseTests/workflowDetails.ts
- src/app/source-file-tabs/source-file-tabs.component.html
- src/app/source-file-tabs/source-file-tabs.component.spec.ts
- src/app/source-file-tabs/source-file-tabs.component.ts
This PR changes the UI so that when the user views a source file, its absolute path is added to the URL as the `file` query parameter.  The resulting URL directly references the source file and can be copied/pasted/saved for future use.
Please view this PR locally and try to make it malfunction.
Believe it or not, the private entry page does not track the selected tab in the URL or allow linking to a particular tab, like the public entry page does.  I poked around and it looks like harmonizing the behavior would be hazardous and quite a chore, so I left it as is.  Thus, the new functionality is only available on the public entry page.
When a version changes, source files can potentially disappear.  When a URL references a now non-existent file, the UI displays a message to …
> DOCK-2403: Link to individual source files

- src/app/github-landing-page/github-landing-page.component.html
This PR removes the indent so the codeblock in the GitHub Apps landing page is copyable
Before: 
After:
Go to https://staging.dockstore.org/github-landing-page and verify that the indent is removed.
**Issue**
https://ucsc-cgl.atlassian.net/browse/DOCK-2532
**Security**
> DOCK-2532: remove indent in template

- src/app/about/about.component.html
- src/app/about/about.component.ts
The PCAWG data portal recently shut down:
https://dcc.icgc.org/
Thus, the PCAWG link on the "about" page no longer works, causing the ui2 "link check" test to fail.
This PR changes the link to point at the "legacy" data page:
https://docs.icgc-argo.org/docs/data-access/icgc-25k-data
Visit about page and confirm that the PCAWG image links to the "legacy" data page.
**Issue**
none
**Security**
> Point pcawg link at legacy page 

- package-lock.json
- src/app/shared/mastodon/mastodon.component.html
This hotfix PR fixes the `undefined` errors that were a result of pictures in the Mastodon feed. We added our first post yesterday that contained pictures which resulted in the errors. That post with pictures no longer has pictures, so the error is not there anymore, but can happen again if we add pictures. See https://oicr.slack.com/archives/C05EZH3RVNY/p1720052421982209 for more discussion.
- Create a Mastodon post with pictures
- Go to the home page and verify that the Mastodon feed displays the picture
- Click on the account dropdown in the upper right and verify that it expands and you can navigate to one of the pages
**Issue**
https://github.com/dockstore/dockstore/issues/5930
https://ucsc-cgl.atlassian.net/browse/DOCK-2546
**Security**
If …
> Fix media content for mastodon post

- cypress/support/commands.ts
This PR fixes the failing news content tests. The news content was updated yesterday which triggered these failures due to the tests not being able to find the `<a>` element. These tests were not using the best method to get the anchor element and we were just lucky before that the tests were able to get the anchor element. My guess is that `contains('a')` was working before because the most recent news entry had the letter `a` as the text for the anchor element, i.e. "1.15 releAse". After yesterday's news update, the newest anchor element text does not have the letter `a`, "ISMB/BOSC 2024", resulting in the failure.
Builds should pass
**Issue**
n/a
**Security**
If there are any concerns that require extra attention from the security team, highlight …
> Fix news content tests

- cypress/support/commands.ts
- package-lock.json
- src/app/container/container.component.ts
After viewing a workflow's page and navigating to an old-style tool's page, the status bar will get stuck in the "updating" animation.  This PR fixes the bug.
Targeted to the hotfix branch, because this bug could appear during normal usage, and the fix is minimally invasive.
Cherry picks https://github.com/dockstore/dockstore-ui2/pull/1990 to pass the tests.
Navigate to a workflow's page, then navigate to an old-style tool's page.  Confirm that the status bar stops "updating" a split-second after the page is loaded.
**Issue**
https://ucsc-cgl.atlassian.net/browse/DOCK-2544
**Security**
Please make sure that you've checked the following before …
> Fix "infinite status" workflow-to-tool bug

- src/app/search/map-friendly-values.pipe.ts
Adds a new key-value in order to have a user-friendly display for release events.
1. Do a release on GitHub for a repo that you have a corresponding workflow.
2. Click the App Logs button, and look for a release event, whose type should be displayed as `Release`, not `RELEASE`.
**Issue**
SEAB-6466
**Security**
> Update pipe for release event

- src/app/shared/entry/info-tab-checker-workflow-path/info-tab-checker-workflow-path.component.html
This PR fixes the issue where the checker workflow field briefly disappears when toggling between the different topic sentences.
Go to one of your workflows and change the topic sentence from Automatic to Manual. The checker workflow field should not disappear.
**Issue**
https://ucsc-cgl.atlassian.net/browse/DOCK-2137
**Security**
> DOCK-2137: fix checker workflow field refresh issue

- angular.json
- src/app/gravatar/gravatar.service.ts
- src/app/shared/auth.guard.ts
This PR suppresses the module warnings shown on build. Example is below.
```
Warning: /home/nhyun/Documents/dockstore-ui2/src/app/gravatar/gravatar.service.ts depends on 'ts-md5/dist/md5'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
Warning: /home/nhyun/Documents/dockstore-ui2/src/app/search/query-builder.service.ts depends on 'bodybuilder'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
```
Build the UI and you shouldn't see these warnings on the bottom.
**Issue**
https://ucsc-cgl.atlassian.net/browse/DOCK-2335
**Security**
If there are any concerns …
> DOCK-2335: Suppress CommonJS module warnings during build

- src/app/shared/entry/descriptor-language-versions.pipe.ts
- src/app/shared/entry/descriptor-language-versions.spec.ts
- src/app/workflow/versions/versions.component.html
- src/app/workflow/versions/versions.component.ts
This PR displays the Engine Versions column instead of Language Versions for Nextflow workflows.
On QA, navigate to https://qa.dockstore.org/workflows/github.com/nf-core/rnaseq:dev?tab=versions and verify that there's an Engine Versions column and no Language Versions column for Nextflow workflows. Go to a non-Nextflow workflow, click the Versions tab and verify that it has a Language Versions column.
**Issue**
https://github.com/dockstore/dockstore/issues/5918
https://ucsc-cgl.atlassian.net/browse/DOCK-2536
**Security**
> Display engine version for Nextflow workflows

- src/app/shared/entry/info-tab-topic/display-topic/display-topic.component.html
- src/app/shared/entry/info-tab-topic/edit-topic/edit-topic-dialog.component.html
- src/app/shared/entry/info-tab-topic/edit-topic/edit-topic-dialog.component.ts
This PR changes the badge from Automatic to GitHub.
Verify that the topic badge in My Workflows is changed to GitHub and also in the edit topic dialog component.
**Issue**
https://ucsc-cgl.atlassian.net/browse/DOCK-2551
**Security**
> DOCK-2551: change automatic topic badge

- src/app/loginComponents/onboarding/downloadcliclient/downloadcliclient.component.ts
Following on discussion in https://github.com/dockstore/dockstore/pull/5958 and at the suggestion of @mr-c we now suggest using pipx over pip3 (it manages virtual environments for the user).
Successfully install cwltool using the instructions described in the onboarding.
**Issue**
https://ucsc-cgl.atlassian.net/browse/DOCK-2539
**Security**
> Change pip3 to pipx

- cypress/e2e/smokeTests/sharedTests/basic-enduser.ts
In the 1.14 release, which included partial notebooks support, we added some code to the smoke tests which would partially test the notebooks functionality.  Some of the code special-cased "random notebook" selection, and the plan was to revert to the general-purpose code path after the full notebook UI was completed (which happened in the 1.15 release).
Per the above, this PR removes the special-case notebook code. 
Confirm that the `basic-enduser` smoke test is passing.
**Issue**
https://ucsc-cgl.atlassian.net/browse/SEAB-5553
**Security**
> SEAB-5553: Remove stopgap notebook smoke test code

- .circleci/config.yml
- package.json
Noticed error https://github.com/CircleCI-Public/browser-tools-orb/pull/109 in the CircleCI logs. 
Seems unlikely to fix qa (affects all environments), but may as well fix
See "Install ChromeDriver" step in Circle CI and see that linked syntax error no longer shows up.
**Issue**
n/a
**Security**
> Fix ChromeDriver syntax error on install

- src/app/shared/entry/doi/manage-dois/manage-dois-dialog.component.html
- src/app/shared/entry/doi/manage-dois/manage-dois-dialog.component.scss
- src/app/shared/entry/doi/manage-dois/manage-dois-dialog.component.ts
- src/app/shared/entry/info-tab-topic/edit-topic/edit-topic-dialog.component.html
- src/app/shared/entry/info-tab-topic/edit-topic/edit-topic-dialog.component.scss
- src/app/shared/entry/info-tab-topic/edit-topic/edit-topic-dialog.component.ts
- src/app/shared/styles/radio-button-cards.scss
FYI, I recommend hiding whitespace when reviewing because I removed some divs that didn't need to be there.
This PR improves the Edit Topic dialog by:
- Making the AI topic copyable with a copy button
- Previously, clicking any area of the mat card selected the radio button. This prevented the topic content from being selectable. This PR changes it so only the top part of the card with the label is selectable. This allows for better interaction with the rest of the card content that may contain buttons or links. 
- Improving the manual topic description for GitHub App entries by using active voice and including an info button to the documentation
There are also miscellaneous improvements while I was testing the changes:
- The card with the selected radio button has a …
> Edit topic dialog improvements to manual and AI topics

- cypress/e2e/group2/myworkflows.ts
- cypress/e2e/group3/githubAppTools.ts
- src/app/myworkflows/sidebar-accordion/github-apps-logs/github-apps-logs.component.html
This PR changes the UI to display the text "Warnings" in the "Success" column of the lambda logs, when the event is successful (`success` == true) and a message is included.  This approach works because currently, lambda log messages are composed solely of warnings and errors.
In the longer term, we might want to implement a more "correct"/robust solution, which might involve collapsing the four existing "outcomes" of a lambda event ("Success", "Failed", "Warnings", and "Ignored") into a single enum/column.
But the latter is a lot more work than what's implemented here, which works fine in the meantime and helps us to hit our 1.16 release date.
View the lambda logs, and confirm that for events that were successful but have a message, "Warnings" is …
> DOCK-2469: Display "Warnings" indicator in lambda logs

- cypress/e2e/smokeTests/sharedTests/auth-tests.ts
Per these slack threads https://ucsc-gi.slack.com/archives/C05EZH3RVNY/p1723669795506039 https://app.slack.com/client/T09P9H91S/C05EZH3RVNY, in June 2024, the prod auth smoke tests began causing the webservice to sporadically 500 and produce corresponding Slack alerts.  After adding some logging, we determined that the webservice was occasionally throwing a database-consistency-related exception, which was triggered by overlapping restub and refresh requests.
This PR adds a bit of code to the auth smoke tests to delay the responsible refresh until after the preceding restub is complete, thus avoiding any overlap and preventing the database inconsistency and resulting exception.
Since the exceptions/500s happened only occasionally, and were sometimes separated by weeks of …
> SEAB-6535: Fix auth-smoke-test-triggered 500s

- src/app/shared/entry/descriptor-language.service.spec.ts
- src/app/shared/entry/descriptor-language.service.ts
As detailed in https://ucsc-cgl.atlassian.net/browse/DOCK-2586, "Jupyter" was appearing in several locations in our UI, all related to "manual" workflow registration, as a possible value for a workflow descriptor language.  This PR changes the UI so that "Jupyter" no longer appears in those locations.
The primary change is to modify the code that calculates the `filteredDescriptorLanguages$` observable of `DescriptorLanguageService`, which is used by the errant UI elements, so that "Jupyter" is not included in the returned list of workflow languages.
Turns out that the related unit tests were not working because the `entryType$` property of the mocked `WorkflowQuery` was not set, causing the tests to [effectively silently, except for some warnings on the console] not test …
> DOCK-2586: Remove "Jupyter" from workflow-related UI

- cypress/e2e/smokeTests/sharedTests/basic-enduser.ts
- src/app/search/search-entry-table.ts
- src/app/search/search-notebook-table/search-notebook-table.component.html
- src/app/search/search-notebook-table/search-notebook-table.component.scss
- src/app/search/search-notebook-table/search-notebook-table.component.ts
- src/app/search/search-tool-table/search-tool-table.component.html
- src/app/search/search-workflow-table/search-workflow-table.component.html
- src/app/search/search.component.scss
- src/app/shared/styles/entry-table.scss
- src/styles.scss
This PR makes some relatively-minor changes to the presentation of Dockstore's Search page results, with the overarching goal of making each hit's topic sentence more prominent. readable, and completely-displayed.
This Slack thread contains some of the related discussion:
https://ucsc-gi.slack.com/archives/C05EZH3RVNY/p1727899641002089
Specifically, this PR:
* increases topic font size
* removes "Verified" and "Links" columns
* decreases "Author" value font size and column width
* tightens line height
* fixes vertical alignment of authors block and horizontal alignment of star counts
* increases truncation limit of topic and authors values to three lines
* adds a small "entry" icon in front of each hit
* fixes a smattering of inconsistencies
The net effect is to widen the …
> SEAB-6696: Improve search result presentation

- src/app/search/query-builder.service.ts
- src/app/shared/ai-bubble/ai-bubble.component.html
This PR changes the UI's Elasticsearch query-construction code to add OR subqueries in such a way that they produce correct results when included in complex queries.
In an ES query, `must` clauses corresponds to ANDs, and `should` clauses correspond to ORs.  We assemble a query as a collection of `musts` and `shoulds`, the `musts` corresponding to a facet with a single value selected, and the `shoulds` to a facet with multiple values selected.
Things work more or less as you'd expect, except for a quirk: if a query contains both `musts` and `shoulds`, the `shoulds` are effectively ignored for hit selection purposes (used only for ranking), and the query returns all hits that match the `musts`.  For example, in the case of the bug reported in the ticket, the query returned …
> DOCK-2592: Fix faceted search for complex queries involving ORs

- src/app/search/search-notebook-table/search-notebook-table.component.html
- src/app/search/search-tool-table/search-tool-table.component.html
- src/app/search/search-workflow-table/search-workflow-table.component.html
AI tooltip in search just repeats what's already there.
Search results appear as normal without a tooltip.
**Issue**
N/a
**Security**
> Remove ai tooltip

- src/app/workflow/info-tab/info-tab.component.ts
- src/app/workflow/info-tab/info-tab.service.spec.ts
- src/app/workflow/info-tab/info-tab.service.ts
This PR fixes the "copy" button (on the workflow page, in the "Workflow Information" section, at the right end of the "TRS" line) so that when two workflows are viewed successively, the copied value is correct.  Previously, if you visited the pages for two workflows A and B, if you used the button to copy the TRS ID on workflow B's page, the copied value was the TRS ID for workflow A.
The cause was that we were updating the TRS ID field of the component when an "entryType" observable issued forth a new value.  The assumption was probably that if we visited successive workflows, we'd see successive "workflow" entry type values on the line.  But, for whatever reason, that's not how it was working...
Editorial: this type of bug suggests that our UI code (and more …
> DOCK-2594: Fix TRS ID "copy button" bug

- src/app/search/search-notebook-table/search-notebook-table.component.html
- src/app/search/search-tool-table/search-tool-table.component.html
- src/app/search/search-workflow-table/search-workflow-table.component.html
- src/app/shared/styles/entry-table.scss
This PR addresses the first usability feedback point in this [document](https://docs.google.com/document/d/1nKpw3D-BajzwgpSWipUGgDWCv9YRUXt4BQHfPTtj8iE/edit?tab=t.0):
> In each hit on the search page, the "AI bubble" (displayed prior to the topic) and the new "entry bullet" icon are very close to each other, and both lead their respective lines, causing readability issues, because the confluence of the two elements is very busy, and they cause the apparent indentation of the first word on each line to be different, and neither first word to align with the left margin.
Possible alternative: display "AI bubble" at the end of the topic. 
Following https://github.com/dockstore/dockstore-ui2/pull/2036, we no longer display the tooltip for the topics on the search page because …
> Don't truncate topics on search page, move AI bubble to the end of topic

- .circleci/config.yml
- src/app/workflow/versions/versions.component.html
This PR updates the public Versions table so that it uses the same DOI icon as the private Versions table. The public Version previously had a check mark to indicate if it has a DOI. Now it has a DOI initiator icon which also indicates the source of the DOI.
Before:
After:
Go to a public workflow with DOIs, navigate to the Versions tab, and verify that the DOI column uses the same icon as the private Versions page. Note that the public page will only show 1 DOI icon for each version because it only displays information about the DOIs with the selected DOI initiator.
**Issue**
dockstore/dockstore#6026
[DOCK-2595](https://ucsc-cgl.atlassian.net/browse/DOCK-2595)
**Security**
If there are any concerns that require extra attention from the security …
> Display same DOI icon on public Versions tab

- src/app/home-page/home-logged-out/home.component.html
Typo, notice the apostrophe
I fear no one ever tried this
**Issue**
n/a
**Security**
> Typo in landing page

- src/app/test/service-stubs.ts
- src/app/workflow/launch-third-party/launch-third-party.component.ts
- src/app/workflow/launch/launch.component.ts
This PR fixes the "has no content" launch-with button bug, which is described in https://ucsc-cgl.atlassian.net/browse/SEAB-6767.
The bug is caused by the complicated, asynchronous information flow through our UI, due to the web of Observables and Subscriptions that we have woven.  We have discussed removing Akita, and if/when we do, we should consider reevaluating this part of our UI's information management model. 
Because our UI code sets the workflow and version name at different clicks, `ngOnChanges` is called twice when the launch-with component is initialized, and the second call has consistent/correct values.  We move the primary/secondary descriptor retrieval code to `ngOnChanges` to more closely couple it to the final `ngOnChanges` call. …
> SEAB-6767: Fix launch-with button "has no content" bug

- src/app/container/container.component.html
- src/app/container/container.component.ts
- src/app/shared/entry.ts
- src/app/workflow/launch-third-party/launch-third-party.component.ts
- src/app/workflow/workflow.component.ts
This PR fixes the "Flash Of Previous Entry" (FOPE) bug for non-tool/AppTool entry types, by restoring an `Entry.clearState` call for those entry types, which is called at component initialization time.  This call was commented out in a PR that added support for AppTools: https://github.com/dockstore/dockstore-ui2/pull/1388#discussion_r761229496
Indeed, consistent with the accompanying comment that was added in that PR, if you simply restore the `clearState` call for all entry types, the tool pages get messed up (nothing is displayed).  There might be a smallish fix for tools/AppTools which mostly works, but it would be very risky, there's lots of looping information and hard-to-quantify data dependencies in this part of the code.
Fixing the problem for all entry types …
> SEAB-6748: Fix "Flash Of Previous Entry" for some entry types

- src/app/workflow/versions/versions.component.html
- src/app/workflow/versions/versions.component.scss
This PR improves the workflow page's "Versions" table so that it fits horizontally into our UI when the browser window is wide.  Previously, the table was too wide for space afforded to it by our UI, causing the rightmost elements to be hidden behind other elements, wide content to be wrapped over multiple lines, and a scrollbar to appear at bottom.
Specifically, this PR:
1. removes the "sort" control from all but the "Git Reference" and "Date Modified" columns.
2. decreases the padding between adjacent columns.
These changes allow the column headers to fit within the available space, and provide extra horizontal space that columns containing wide content can scale into.
These changes make a big difference, improving the spacing and flow of the table for most workflows. …
> SEAB-6777: Improve formatting of workflow "Versions" table

- cypress/e2e/group3/githubAppTools.ts
- cypress/e2e/immutableDatabaseTests/linkCheck.ts
Recently, the ui2 integration tests have been flaking a lot in `cypress/e2e/group3/githubAppTools.ts`, and in the linkcheck, when checking the URL https://doi.org/10.1093/nar/gkab346, which was consistently responding with a Cloudflare challenge.
And, as it turns out, beyond the flake sites, the tests were actually broken due to commit https://github.com/dockstore/dockstore/commit/4786a289a70a7eceb7e3b069572f75a54a455663 on Dec 9, which changed the default ordering of workflow versions.  The UI was coded so that the new search order was used by default, which violated an assumption in one of the tests.
This PR:
1. adds some `cy.wait`s to avoid race conditions.
2. changes the linkcheck so that it does not "fail" a url that responds with a cloudflare challenge.
3. fixes a …
> Fix ui2 integration tests

- cypress/e2e/group1/checkerWorkflowFromWorkflow.ts
- cypress/e2e/group2/myworkflows.ts
- cypress/fixtures/getWorkflowWithDoi.json
- cypress/fixtures/versionWithDoi.json
- src/app/workflow/versions/versions.component.html
As it turns out, the UI was already using the webservice-defined sort order when the versions table was loaded.  I confirmed this by observing that the request to the webservice did not include a `sortCol` parameter, and that initially, the default version always appeared at the top, no matter when it was last updated.  However, the UI was incorrectly indicating that it was sorting by "Last Modified" in descending order (the black arrow appeared next to the "Last Modified" header).
This PR changes the UI so that the version table sort controls now have three states ("none", "ascending", and "descending"), they start off set to "none". and they display their state correctly.
This is similar to how the search table works: the controls initially don't specify any sort …
> DOCK-2591: Use webservice-defined sort ordering in workflow versions table by default

- cypress/e2e/group2/myworkflows.ts
- cypress/e2e/group2/notebooks.ts
- cypress/e2e/group3/mytools.ts
- cypress/fixtures/myTools.json
- src/app/mytools/my-tool/my-tool.component.html
- src/app/myworkflows/my-workflow/my-workflow.component.html
This PR removes the redundant "More" dropdown in the My Workflows and My Tools pages. 
Before: 
After:
Verify that the dropdown is removed
**Issue**
https://ucsc-cgl.atlassian.net/browse/SEAB-6840
**Security**
> SEAB-6840: remove redundant "More" dropdown

- cypress/e2e/smokeTests/sharedTests/basic-enduser.ts
- cypress/e2e/smokeTests/sharedTests/search.ts
- cypress/support/commands.ts
This PR fixes the failed search page tests in staging and prod. PR https://github.com/dockstore/dockstore-ui2/pull/2055 added search cards in QA and modified the smoke tests, which caused the smoke tests to fail in staging and prod because those search card elements don't exist. I'll create a follow-up ticket to remove the staging/prod code when the search cards are deployed to staging and prod.
Smoke tests should pass
**Issue**
n/a
**Security**
> Fix search smoke tests in staging and prod

- src/app/shared/entry/doi/manage-dois/manage-dois-dialog.component.html
This PR fixes the typo in the auto DOI generation opt out instruction for GitHub App entries. This PR also bolds that instruction to make it more prominent and specifies that an author is required.
Before:
After:
See https://github.com/dockstore/dockstore-ui2/pull/2059
**Issue**
https://ucsc-cgl.atlassian.net/browse/SEAB-6807
**Security**
> Fix auto DOI opt out instruction typo and make it bold

- src/app/mytools/my-tool/my-tool.component.html
- src/app/myworkflows/my-workflow/my-workflow.component.html
This is a PR to fix the text positioning of the Discover workflows button.
Before:
After:
Go to my workflows and My Tools and verify the text in the Discover Workflows button aligns with the text in the "Register a Workflow" button
**Issue**
https://ucsc-cgl.atlassian.net/browse/SEAB-6840
**Security**
> SEAB-6840: button text position fix

- .github/workflows/accessibility_test.yml
- .github/workflows/npm_audit_test.yml
- .github/workflows/update_license.yml
Bumps three workflows
npm audit test - akita legitimately shows a broken signature, will need to unblock https://github.com/dockstore/dockstore-ui2/pull/2047 think this is broken for everyone
accessibility: seems to work
update license file: seems to work
Look at these builds in github actions
**Issue**
https://ucsc-cgl.atlassian.net/browse/SEAB-6965
**Security**
None
> bump versions for github actions

- src/app/about/about.component.ts
- src/app/footer/footer.component.ts
- src/app/search/search-entry-table.component.ts
This PR adds the relevance sort back to the search page and adds it as default.
Screenshot example when searched for "test"
When set back to Most stars
Go to the search page on qa and verify the relevance sort works
**Issue**
https://ucsc-cgl.atlassian.net/browse/SEAB-6966
**Security**
> SEAB-6966: add relevance sort in search

- src/app/about/about.component.html
- src/app/home-page/home-logged-out/home.component.html
- src/app/shared/launch.service.ts
- src/app/workflow/launch/launch.component.html
- src/app/workflow/launch/launch.component.ts
- src/app/workflow/launch/workflow-launch.service.ts
- src/app/workflow/workflow.component.html
Ticket https://ucsc-cgl.atlassian.net/browse/DOCK-2610 prescribes that we append the version to the TRS ID in our UI, so that when it's copied into a Toil command, there's enough information to download the correct version and run it.  However, a TRS ID containing the version is not spec compliant, and we determined that it would break Galaxy's import page, and perhaps other software.
So, instead, as agreed upon, this PR adds Toil launch instructions to the workflow page "Launch" tab for published CWL and WDL workflows.
Also, this PR:
* Removes AGC instructions from the "Launch" tab.
* Changes "www.dnastack.com" to "dnastack.com"  in links, because the former was hanging and causing the tests to fail.
The new Toil instructions are an abbreviated form of what Adam suggested …
> DOCK-2610: Include Toil launch instructions

- src/app/header/header.component.html
- src/app/header/header.component.ts
- src/styles.scss
The app headers for non-”My Entry” pages are not padded properly. This PR fixes that so that the app header is properly padded with a consistent height for all pages. Discovered during [usability test](https://docs.google.com/document/d/1vKoDCVQXEWG8AefEiLdr5tw44LLDzRY9LFH6bK3sEvk/edit?usp=sharing). 
Problematic app headers before fix:
App headers after fix:
Navigate to different pages and verify that the app header is properly padded.
**Issue**
https://ucsc-cgl.atlassian.net/browse/SEAB-6279
**Security**
> Fix app header

- src/app/container/container.component.html
- src/app/workflow/workflow.component.html
This PR modifies the tool/workflow pages so that colons appear at the end of the "Categories" and "Labels" text that precede the corresponding bubbles.  I went with colons (rather than "no colons") because there was some adjacent "coloned" text, and it looked weird otherwise.
Bask in the glow of the colons.
**Issue**
https://ucsc-cgl.atlassian.net/browse/SEAB-7086
**Security**
> SEAB-7086: Add some colons

- src/app/workflow/launch-third-party/launch-third-party.component.html
- src/app/workflow/launch-third-party/launch-third-party.component.scss
This PR tweaks the `img.partner-launch` style so that svgs are displayed correctly, thus making the Sequera icon appear in its launch-with button appear, and corrects the style used on a couple of Terra icons.
Confirm that the "launch-with" buttons look right, for all workflow types (Nextflow, WDL, etc), in a couple of different browser (to make sure they handle the styling the same way).  
**Issue**
https://ucsc-cgl.atlassian.net/browse/SEAB-7086
**Security**
> SEAB-7086: Fix nextflow/Sequera launch-with button image

- src/app/home-page/widget/entry-box/entry-box.component.html
- src/app/home-page/widget/organization-box/organization-box.component.html
- src/app/home-page/widget/starred-box/starred-box.component.html
- src/styles.scss
This PR changes the UI so that the card headers are now centered vertically in the available space.  Essentially, this is a couple of style changes pulled from the pre-migration UI.
Mouse around the UI and confirm the above.  Try to find card headers that were missed.
**Issue**
https://ucsc-cgl.atlassian.net/browse/SEAB-7086
**Security**
> SEAB-7086: Center card headers vertically

- src/app/search/search-authors-html.pipe.spec.ts
- src/app/search/search-authors-html.pipe.ts
- src/app/search/state/search.service.spec.ts
- src/app/search/state/search.service.ts
This PR changes the UI so that in the search results table, results corresponding to values that are not available, denoted by "n/a", appear last, when said "n/a" values are used as the sort key.  At present, the main [only?] case where this applies is the "by 'Author'" sorting option.
View the search results for a keyword that has lots of, but less than 200, matches, and sort by "Author, A-Z" and "Author, Z-A".  Confirm that "n/a" values always appear last in the list.
**Issue**
https://ucsc-cgl.atlassian.net/browse/SEAB-7113
**Security**
> SEAB-7113: Sort "not available" values last in search results

- cypress/e2e/smokeTests/sharedTests/basic-enduser.ts
- cypress/e2e/smokeTests/sharedTests/search.ts
- cypress/support/commands.ts
This PR fixes the failing no-auth tests for staging that are related to the search card changes (see https://github.com/dockstore/dockstore-ui2/pull/2062). The fix for the failing auth tests in QA/staging are a bit more involved, so I'm separating the PRs.
We will need a similar fix for when 1.17 is deployed to prod and prod has the new search cards. After this is merged, I can prepare a PR in anticipation of the deploy to prod. The change would essentially remove all the environment checks since all environments will have the search cards.
No auth smoke tests in staging and QA should pass.
**Issue**
n/a
**Security**
Please make sure that you've …
> Fix search tests for staging

- src/app/workflow/launch-third-party/launch-third-party.component.scss
This PR tweaks the CSS so that the Sequera launch-with button appears in all browsers.  The previous fix worked in Chrome, but  not in Firefox, the button did not appear.
I am not a CSS expert, so I do not fully understand why this works and the previous solution did not.
See https://github.com/dockstore/dockstore-ui2/pull/2082
**Issue**
https://ucsc-cgl.atlassian.net/browse/SEAB-7086
**Security**
> SEAB-7086: Fix sequera launch-with button

- src/app/test/service-stubs.ts
- src/app/workflow/versions/versions.component.ts
*Important note: please read the "Important Note" section below.*
This PR fixes the bug wherein the workflow "Versions" tab would appear empty (no versions listed), after first visiting the "Versions" tab, then clicking and viewing the "stargazers" list, then clicking "Back to details" to return to the "Versions" tab.
The cause related to the order in which various parts of `VersionsWorkflowComponent` are initialized and called.
Per the Angular component lifecycle docs https://v17.angular.io/guide/lifecycle-hooks, `ngOnChange` is called before `ngOnInit`.  Thus, due to way that our UI is coded, upon the first display of  `VersionsWorkflowComponent`, those methods are invoked in the following order:
```
ngOnChange
ngOnInit
ngOnChange
```
The first `ngOnChange` tries to use …
> DOCK-2618: Fix empty version list after viewing stargazers

- cypress/e2e/smokeTests/sharedTests/basic-enduser.ts
- cypress/e2e/smokeTests/sharedTests/search.ts
Similar to https://github.com/dockstore/dockstore-ui2/pull/2089, now that the search cards are in prod, we need to update the smoke tests which will fix the failing prod no auth tests.
No auth smoke tests on prod should pass
**Issue**
n/a
**Security**
> Update prod smoke tests for search cards

- src/app/workflow/workflow.component.ts
A while back, we added a feature wherein Dockstore displays a warning message on the private entry page when it detects that our GitHub app may have been uninstalled.  Intermittently, this warning was appearing erroneously, for a split second when a workflow was first displayed, when switching between workflows.
The solution was to unset the controlling flag upon a change of workflow.  Based on the declared type of the flag in the existing code, it appears that I probably intended the flag to be unset, but forgot to add the code to do it. 
To improve the type consistency, I changed the "unset" value from `null` to `undefined`.
Switch between private workflows in the dashboard, being sure to include some  `.dockstore.yml`-based workflows, and confirm …
> DOCK-2601: Fix flash of "may not be automatically updating" notice

- package.json
- src/app/myworkflows/sidebar-accordion/github-apps-logs/recommended-actions.component.ts
- src/app/navbar/navbar.component.html
- src/app/navbar/navbar.component.ts
- src/app/notifications/state/notifications.service.ts
This PR updates the UI to hide a user notification when the user "deletes" it.  It also addresses a pair of bugs in the user notification code:
* The notification count (displayed on the bell) is now updated on user login and when the user "deletes" a notification.
* The bell no longer briefly flashes a "0" count, ever.
On staging, create a github app notification.  Hide the notification via the UI, and confirm that the notification count on the bell is correct.  Load the UI on various browsers and confirm that the "0" flash is fixed. 
**Issue**
https://ucsc-cgl.atlassian.net/browse/SEAB-7286
https://ucsc-cgl.atlassian.net/browse/SEAB-7288
**Security**
If there are any concerns that require extra attention from the security team, highlight them …
> SEAB-7286:  Update bell when notification is deleted or user logs in
